### PR TITLE
publish raw data for unsupported devices

### PR DESCRIPTION
**Pull request by supby**

### CODE REVIEW

**Comment by Koenkk** [comment]
What would be the use-case of this?

**Comment by sjorge** [comment]
I guess it would make supporting new devices easier? On that regard, would the default read/write converters also work on those? I guess they don't? But it would maybe be nice if they did if this is set.

**Comment by Koenkk** [comment]
The thing I don't like is exposing such internal data structures via MQTT. The whole point is that everything published to MQTT is human friendly.

**Comment by sjorge** [comment]
> The thing I don't like is exposing such internal data structures via MQTT. The whole point is that everything published to MQTT is human friendly.

Are they currently logged at debug level? I think they are right? If so, maybe make this move them to info level for unsupported devices only. (As on debug yo uget so much info it's hard to pick out what you want.)

**Comment by supby** [comment]
> What would be the use-case of this?

To use data from unsupported device without need to make converters. Herdsman already sends data with i can use in NodeRed and i need only retransmit it to mqtt without creating layer of abstraction with another data format and conversation.
Use case: i got motion sensor which is not supported and z2m cannot read its model with undefined in logs but data from herdsman is already there. I can use it further without need to fix this undefined thing.

**Comment by nurikk** [comment]
> > What would be the use-case of this?
> 
> To use data from unsupported device without need to make converters. Herdsman already sends data which i can use in NodeRed and i need only retransmit it to mqtt without creating layer of abstraction with another data format and conversation.
> Use case: i got a motion sensor which is not supported and z2m cannot read its model with undefined in logs but data from herdsman is already there. I can use it further without need to fix this undefined thing.

Why don't we just implement converter for your device? If z2m can’t read model name we might be able to use other properties with device fingerprinting. Can you share your database 
.db?

**Comment by supby** [comment]
> > > What would be the use-case of this?
> > 
> > 
> > To use data from unsupported device without need to make converters. Herdsman already sends data which i can use in NodeRed and i need only retransmit it to mqtt without creating layer of abstraction with another data format and conversation.
> > Use case: i got a motion sensor which is not supported and z2m cannot read its model with undefined in logs but data from herdsman is already there. I can use it further without need to fix this undefined thing.
> 
> Why don't we just implement converter for your device? If z2m can’t read model name we might be able to use other properties with device fingerprinting. Can you share your database
> .db?

this is data from device:
` MQTT publish: topic 'zigbee2mqtt/0x00124b000724ae04', payload '{"cluster":"ssIasZone","data":{"batteryPercentageRemaining":200,"batteryVoltage":30,"zoneStatus":1},"device":{"friendlyName":"0x00124b000724ae04","ieeeAddr":"0x00124b000724ae04","model":"unknown","networkAddress":31211,"type":"Unknown"},"endpoint":{"ID":1,"_binds":[],"_configuredReportings":[],"clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}},"ssIasZone":{"attributes":{"zoneStatus":1}}},"deviceIeeeAddress":"0x00124b000724ae04","deviceNetworkAddress":31211,"inputClusters":[],"meta":{},"outputClusters":[]},"groupID":0,"linkquality":52,"meta":{"frameControl":{"direction":1,"disableDefaultResponse":true,"frameType":0,"manufacturerSpecific":false,"reservedBits":0},"manufacturerCode":null,"zclTransactionSequenceNumber":219},"type":"attributeReport"}'`

**Comment by Koenkk** [comment]
@supby what device is this? If TuYa, there are some improvements for this in z2m 1.21.0. If reading the model ID also fails with that please share the herdsman debug log when pairing that device.

See https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by supby** [comment]
@Koenkk This is TuYa ZM-35ZH-Q device. I updated z2m to 1.21 but result the same, model is undefined. This is actually what I was taking about, instead of using raw data from device it needs to figure out why modelId cannot be read by herdshman.
Anyway if the PR is not an option it can be closed and I will try to fix this model=undefined issue.

**Comment by Koenkk** [comment]
@supby please create a new issue with the herdsman debug log when pairing the device close to the coordinator. I will close this pr.

**Pull request closed without merging**
