### PR TITLE
Group configuration via configuration.yaml and group state.

### PR DESCRIPTION
**Pull request by Koenkk**
- Allow to configure members of groups in `configuration.yaml`.
- Change group state when one of it's members changes state.

### CODE REVIEW

**Comment by andreasbrett** [comment]
I'd suggest using a different file name for the group cache. Having `groups.yaml` right besides `groups.json` might be confusing. How about `state_groups.json`?

**Comment by RaymondMouthaan** [comment]
I have been playing around with groups too. As with devices, I created a separate file (groups.yml) for groups to define all groups. However when trying to add devices to one of those groups, z2m didn't recognise that group. So currently I moved all groups back to configuration.yml

Also I like to note that when changing the color (hsv based) of a group, nothing is publish to `zigbee2mqtt/<friendly_group_name>`. While changing it's state or brightness does.

**Comment by Koenkk** [comment]
@andreasbrett I don't understand what you mean:
- There is no `groups.yaml`
- The cache in a separate hidden folder (`data/.storage`)

**Comment by andreasbrett** [comment]
Ah okay, I see. I thought the file would be in the data folder. 

Koen Kanters <notifications@github.com> schrieb am 23.04.2019:
>@andreasbrett I don't understand what you mean:
>- There is no `groups.yaml`
>- The cache in a separate hidden folder (`data/.storage`)

**Pull request merged**
