### PR TITLE
availability_whitelist

### LINKED ISSUE #2204: availability_whitelist ?
do you think it would also make sense to have an advanced param "availability_whitelist" ?

I still have one bulb behind a real switch, it would be easier to whitelist one device instead of blacklisting all existing routers and the new ones to come.

### PR DESCRIPTION
**Pull request by Kryzek**
As requested at https://github.com/Koenkk/zigbee2mqtt/issues/2204

Tested with my environment

With
```
  availability_timeout: 120
  availability_whitelist: ['0x00124b001d3ab1b9','0x001788010278b40a']
```
in configuration.yaml

I get this behaviour as wanted:
```
zigbee2mqtt:debug 2019-11-22 14:08:09: Received Zigbee message from '0x00124b001d3ab1b9', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 11 with groupID 0
zigbee2mqtt:debug 2019-11-22 14:08:09: Successfully pinged '0x00124b001d3ab1b9'
...
zigbee2mqtt:info  2019-11-22 14:08:19: MQTT publish: topic 'zigbee/0x001788010278b40a/availability', payload 'offline'
zigbee2mqtt:error 2019-11-22 14:08:19: Failed to ping '0x001788010278b40a'
...
zigbee2mqtt:debug 2019-11-22 14:18:11: Successfully pinged '0x00124b001d3ab1b9'
zigbee2mqtt:debug 2019-11-22 14:18:49: Failed to ping '0x001788010278b40a'
```
Hope I did not break anything else while at it.

Closes #2204

### CODE REVIEW

**Comment by Koenkk** [comment]
This feature looks good to me, if you can add the missing tests than this can be merged, see https://github.com/Koenkk/zigbee2mqtt/blob/master/test/deviceAvailability.test.js#L207 for inspiration.

**Comment by Kryzek** [comment]
If my Google-Fu is not terribly bad, the goal is to get `npm test -- --coverage` to run without errors?

**Comment by Koenkk** [comment]
Yes: `npm run test-with-coverage`. The coverage report (`index.html`) can be found after this in the `coverage` folder.

**Comment by Kryzek** [comment]
I'll be damned! Tests passed! 💪

**Comment by Kryzek** [comment]
Also updated documentation https://github.com/Koenkk/zigbee2mqtt.io/pull/165

**Comment by Koenkk** [comment]
I reshuffled the logic a bit, tests are still passing, is this OK for you?

**Comment by Kryzek** [comment]
Wow... I really overthought this. ’return this.whitelist.includes(device.ieeeAddr);’ does return also false... So much cleaner now. 

How about those forcePinged devices, should those be checked before?

**Comment by Koenkk** [comment]
Forced pinged devices is a list of end devices which can be pinged, however the whitelist does basically the same. It would be strange if a device is NOT in the whitelist but is still pinged.

**Comment by Kryzek** [comment]
Makes sense. 

I’m happy with your changes since they make same as mine but just much more elegant way.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
