### PR TITLE
Update settings.schema.json

### PR DESCRIPTION
**Pull request by timoline**
added setting ikea_ota_use_test_url

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by timoline** [comment]
@Koenkk , I will check and create Pr's for all "missing" settings and descriptions for the json schema.
But I think we should re arrange some settings.
Like logging should have his own section and Adapter also, maybe HA too.
Some settings should be moved from advanced, like baudrate and rts/cts to serial...
There is more, but i'm affraid this is a tricky change which isn't just changing the schema?
I hope you guys can help with that, if you also find its a good idea

**Comment by Koenkk** [comment]
@timoline changing that would be a breaking change so not possible for now (maybe for Zigbee2MQTT 2.0.0)

**Comment by timoline** [comment]
> @timoline changing that would be a breaking change so not possible for now (maybe for Zigbee2MQTT 2.0.0)

Ok good to know, for now it's fine... But for a 2.0.0 please consider it

**Comment by Koenkk** [comment]
Definitely! (but that won't be any time soon)

**Comment by timoline** [comment]
@Koenkk is this gonna happen after 2.x release?

**Comment by Nerivec** [comment]
The schema has changed a lot since then.
2.0.0 cleans up deprecated properties and migrates everything to their new location. The new migration system will make these changes non-breaking for the future too.
https://github.com/Koenkk/zigbee2mqtt/blob/dev/lib/util/settings.schema.json

**Pull request merged**
