### PR TITLE
feat: add curl on the Docker image

### PR DESCRIPTION
**Pull request by rockyluke**
Thanks for your amazing work!

Add curl to be able to manage health check with Docker.

```shell
$ docker ps
koenkk/zigbee2mqtt:1.32.1 "docker-entrypoint.s…" 3 hours ago Up 3 hours (healthy) zigbee2mqtt
```

This MR need to be squashed 🙏

### CODE REVIEW

**Comment by sjorge** [comment]
The frontend is optional, so this will fail for people that chose not to enable the frontend.

**Comment by rockyluke** [comment]
My bad !

Could keeping curl embed be an acceptable solution for you ? It will allow people using docker and docker compose to get the status easily ?

```yaml
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:8080/#/" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
```

**Comment by Koenkk** [comment]
@sjorge while the frontend is indeed optional, I don't see a better way to do a healthcheck

**Comment by sjorge** [comment]
> @sjorge while the frontend is indeed optional, I don't see a better way to do a healthcheck 

Is there an easy way to see if it’s enabled? And then pick the curl check or /bin/true otherwise?

**Comment by Koenkk** [comment]
@sjorge this config is not done from the z2m side but in the docker-compose.yml (so user has to make sure frontend is enabled when deciding to add this healthcheck)

**Comment by skarcha** [comment]
Maybe a solution could be using a MQTT message. Ask zigbee2mqtt for its status using a MQTT message an read its response using another topic.

**Comment by alex3305** [comment]
Why don't you just use `wget`? That's already available by default on alpine. That healthcheck would be something like:

```yaml
    healthcheck:
      test: [ "CMD", "wget", "-O-", "http://127.0.0.1:8080/#/" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
```

Or just check if the process is running with `pgrep`:

```yaml
    healthcheck:
      test: [ "CMD", "pgrep", "node" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
```

Both solutions are untested, but should theoretically work.

**Comment by Koenkk** [comment]
@alex3305 wget seems to be available indeed so curl is not needed.

```
ubuntu@j3455:~$ docker exec -it zigbee2mqtt /bin/sh
/app # wget
BusyBox v1.36.1 (2023-07-27 17:12:24 UTC) multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
	[--post-data STR | --post-file FILE] [-Y on/off]
	[-P DIR] [-U AGENT] [-T SEC] URL...
```

**Pull request closed without merging**
