### PR TITLE
added moving state to home assistant for TS130F Curtain/blind switch

### PR DESCRIPTION
**Pull request by cmiguelcabral**
Does this seem less intrusive?

I would like to have someone with different covers test this version.
But people need to be willing to do it as I have more than 30 covers of this model, but don't have any other.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks, asked for validation in https://github.com/Koenkk/zigbee2mqtt/issues/15873#issuecomment-1374763235

**Comment by cmiguelcabral** [comment]
> Thanks, asked for validation in [#15873 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/15873#issuecomment-1374763235)

Don't you intend to integrate this into the master?

**Comment by Koenkk** [comment]
@cmiguelcabral dev will be merged to master with every new 1st of the month release.

**Comment by cmiguelcabral** [comment]
> @cmiguelcabral dev will be merged to master with every new 1st of the month release.

Hi,
Yes, I know, it's not what I meant.
I meant to ask if you intend to integrate this on zigbee2mqtt. :-)

**Comment by Koenkk** [comment]
@cmiguelcabral yes, the changes are already in the dev branch since 8 Jan: https://github.com/Koenkk/zigbee2mqtt/commit/9c4abb64c3c32f4ba49bf43a25f62186956fdda1

**Comment by Drafteed** [comment]
I don't really understand the purpose of this change - we introduce a duplicate state. Why not just rename the `moving` to `motor_state` in TS130F Curtain/blind?

**Comment by Drafteed** [comment]
@Koenkk Can you revert this PR? I'll made new.

**Comment by Drafteed** [comment]
#16324

**Pull request merged**
