### PR TITLE
Automatic edge build trigger for zigbee2mqtt org

### PR DESCRIPTION
**Pull request by ciotlosm**
Automatic edge build trigger for zigbee2mqtt/hassio-zigbee2mqtt #5065

### CODE REVIEW

**Comment by ciotlosm** [comment]
@Koenkk I hope this is correct now.

**Comment by Koenkk** [comment]
Yes, thanks!

**Comment by ciotlosm** [comment]
@Koenkk For some reason this step doesn't trigger on dev pushes. It doesn't even show as failed or something in the Actions tab on CI for dev pushes. I'm unsure what to check :)

**Comment by Koenkk** [comment]
Seems ci.yml in dev branch also had to be updated + I needed to setup token a little different. It's working now (https://dev.azure.com/zigbee2mqtt/Zigbee2mqtt%20Add-on/_build/results?buildId=242&view=results)

**Pull request merged**
