### PR TITLE
Added presets (hold_modes) to climate sensor #3821

### PR DESCRIPTION
**Pull request by mgrom**
Added presets (hold_modes) to climate sensor #3821
and removed thermostatHeatCool as it was partially redundant

### CODE REVIEW

**Comment by mgrom** [comment]
@Koenkk how to manage changes in zigbee-herdsman-converters that are related to this PR? Should I make them later or now but with some tag or something?

**Comment by Koenkk** [comment]
@mgrom just make a pr to zigbee-herdsman-converters and mention this pr there, I will merge it after that is merged.

**Comment by Koenkk** [comment]
Thanks!

**Comment by presslab-us** [comment]
@mgrom with the removal of `thermostatHeatCool` there is now no longer a way to set separate heating and cooling temperatures on a thermostat that supports both.

Also the new `climate` does not use `temperature_unit` so those of us that use Fahrenheit do not get the right values.

**Comment by mgrom** [comment]
@presslab-us this wasn't just removal. I've merge it to `thermostat`:

 ```
const climate = (minTemp=7, maxTemp=30, temperatureStateProperty='occupied_heating_setpoint',
    tempStep=1, systemModes=['off', 'auto', 'heat'], fanModes=[], holdModes=[],
    temperatureLowStateTopic=false, temperatureHighStateTopic=false ) => {
.....

   // use low target temperature
    if (temperatureLowStateTopic) {
        retVal.discovery_payload.temperature_low_state_topic = temperatureLowStateTopic;
        retVal.discovery_payload.temperature_low_state_template = `{{ value_json.occupied_heating_setpoint }}`;
        retVal.discovery_payload.temperature_low_command_topic = 'occupied_heating_setpoint';
    }
    // use high target temperature
    if (temperatureHighStateTopic) {
        retVal.discovery_payload.temperature_high_state_topic = temperatureHighStateTopic;
        retVal.discovery_payload.temperature_high_state_template = `{{ value_json.occupied_heating_setpoint }}`;
        retVal.discovery_payload.temperature_high_command_topic = 'occupied_heating_setpoint';
    }
```

Regarding temperature it was hardcoded 'C' before, so there was no way to use Fahrenheit either.

**Comment by presslab-us** [comment]
I haven't looked deeply into it, but for some reason it's not working any more.  In Home Assistant it only allows for setting one temperature.

On `thermostatHeatCool` it did use `temperature_unit`.  https://github.com/Koenkk/zigbee2mqtt/blob/0db3f3ca0bcbec2eea6b3d72a4bf6a2c768e302d/lib/extension/homeassistant.js#L784

**Comment by mgrom** [comment]
@presslab-us what device are you using? I'll check configuration. Maybe I made some mistake in other place.

**Comment by presslab-us** [comment]
Thanks @mgrom. I use `3157100` and `RC-2000WH`. I think I see the issue, here is a snip of the discovery topic:
```
  "temperature_command_topic": "zigbee2mqtt/lab_thermostat/set/occupied_heating_setpoint",
  "temperature_high_command_topic": "zigbee2mqtt/lab_thermostat/set/occupied_heating_setpoint",
  "temperature_high_state_template": "{{ value_json.occupied_heating_setpoint }}",
  "temperature_high_state_topic": "zigbee2mqtt/lab_thermostat",
  "temperature_low_command_topic": "zigbee2mqtt/lab_thermostat/set/occupied_heating_setpoint",
  "temperature_low_state_template": "{{ value_json.occupied_heating_setpoint }}",
  "temperature_low_state_topic": "zigbee2mqtt/lab_thermostat",
  "temperature_state_template": "{{ value_json.occupied_heating_setpoint }}",
  "temperature_state_topic": "zigbee2mqtt/lab_thermostat",
```

I believe that for devices that support both high and low state/command, there should not be `temperature_command_topic`. `temperature_state_topic`, and `temperature_state_template` defined.

**Comment by mgrom** [comment]
@presslab-us ok, I'll make PR to fix it.

**Comment by presslab-us** [comment]
Great, thanks a lot.  I agree that combining them is the right thing.  Also if you can add the `temperature_unit` that would be good, and it will now work for all devices.

**Pull request merged**
