### PR TITLE
feat!: The big cleanup

### PR DESCRIPTION
**Pull request by Koenkk**
See https://github.com/Koenkk/zigbee2mqtt/discussions/24198

### CODE REVIEW

**Comment by Nerivec** [comment]
For https://github.com/Koenkk/zigbee2mqtt/pull/24200/commits/a2237ed0276ebd68f54bd2293b8e94471e1d9c4f

Removed:

- `'bridge/log'`
- `zigbee2mqtt/bridge/(bind|unbind)/`
- `zigbee2mqtt/bridge/group/(.+)/(remove|add|remove_all)`
- `zigbee2mqtt/bridge/group/remove_all`
- `bridge/networkmap/${data.message}`
- `zigbee2mqtt/bridge/ota_update/`
- `update_available` from OTA update payload/state
- default group converters (uses members converters instead)
- `retrieve_state` from Device/Group options

Fixed:

- Typing for `getEntityPublishPayload` in `OTAUpdate`

**Comment by Nerivec** [comment]
For https://github.com/Koenkk/zigbee2mqtt/pull/24200/commits/7b402b4c9ce39f534758f883747ee8e2d0e10c96

Removed:
- `/bridge/config/*`
- Settings in `advanced`:
  - availability_timeout
  - availability_blocklist
  - availability_passlist
  - availability_blacklist
  - availability_whitelist
  - soft_reset_timeout
  - report
- Unused zigbee-herdsman wrapper API `reset`
- Unused device API `isIkeaTradfri`
- Unused utils

**Comment by Nerivec** [comment]
For https://github.com/Koenkk/zigbee2mqtt/pull/24200/commits/7f4e15f39012cea3b23fde57ac53fe2c29f12cc8

Removed:
- `/bridge/configure`
- `legacy_availability_payload` setting
- `legacy_api` setting
- Legacy stuff from `configure` (previously missed, wasn't using `legacy_api` setting)

---

@Koenkk I'll let you do the stuff for HA. _A search for `legacy` (whole-repo) should identify most remaining points._

**Comment by Koenkk** [comment]
Removed some leftovers and create a PR for the docs: https://github.com/Koenkk/zigbee2mqtt.io/pull/3094

Ready for merge?

**Comment by Nerivec** [comment]
There's the HA `legacy` stuff left to do. You're going to do that in a separate PR?

**Comment by Koenkk** [comment]
Yes will do the HA stuff in a separate PR

**Comment by Nerivec** [comment]
How about these?
https://github.com/Koenkk/zigbee2mqtt/blob/e06848db8c5ad247c27e959eb85465a30134769f/lib/extension/bridge.ts#L73-L77

**Pull request merged**
