### PR TITLE
Add ieee_address to the exposed fields

### PR DESCRIPTION
**Pull request by CBSalem**
I think that every published topic by zigbee2mqtt should contain the  IEEE ADDRES of the device that the payload is coming from, because using only the topic and the friendly name (topic/FRIENDLY_NAME) we will not be able to identify the device. Say we are inserting all the payloads of all devices coming from 2 different zigbee networks, we can have duplicate topic/FRIENDLY_NAME but having the IEEE_ADDRESS as a part of the payload and extracting that address will make a UNIQUE ID in the database.
example :
now : 'zigbee/switch', payload '{"action":"single","battery":100,"linkquality":255,"voltage":3100}'
it shoudl be:  'zigbee/switch', payload '{"ieee_address": "0x12345678","action":"single","battery":100,"linkquality":255,"voltage":3100}'

### CODE REVIEW

**Comment by sjorge** [comment]
This information is already included if you set `include_device_information: true`. This should definitely not be included by default as a lot of people won't need it and it just clutters up the payload.

**Comment by ChihebBenSalem** [comment]
I have to agree with you that not all the people need to know the ieeeAddr, but 31 bytes "ieeeAddr":"0x00XXXXXXXXXXXXXX" won't really clutter the payload. 
But 283 bytes ==> "device":{"applicationVersion":5,"dateCode":"20211103","friendlyName":"thermometer",
"hardwareVersion":1,"ieeeAddr":"0x00XXXXXXXXXXXXXX","manufacturerID":0,"manufacturerName":"eWeLink",
"model":"SNZB-02","networkAddress":27767,"powerSource":"Battery","type":"EndDevice","zclVersion":1}"
definitely would. Of course that goes without saying, the CPU cycles wasted and the overhead to extract 
the information from the second level of the payload.
So I still think that adding 31 bytes to the payload is still defendable.
Maybe add one more setting "include_ieee_information" to include only IEEE address if we still think that 31 bytes is too much.

**Comment by sjorge** [comment]
I think there should definitely be a way to disable/enable this. (And probably have it disabled by default)

Perhaps something like always using ieeeAddr instead of friendlyName in the topic, even when one is configure could also work.

**Comment by ChihebBenSalem** [comment]
Either way is fine. But we might break someone's logic if we hardcode the topic name like "topic/ieeeAddress" and he used to reason on "topic/FRIENDLY_NAME". So I think definitely that what you suggested at first {"I think there should definitely be a way to disable/enable this. (And probably have it disabled by default)"}  is way more elegant and trouble free, it won't cause any noticeable changes unless the new feature/setting is set to true.

**Comment by Koenkk** [comment]
I don't see the advantage of this over `include_device_information: true`

**Comment by ChihebBenSalem** [comment]
Since IEEE address is the unique identifier of each and every device in the world of ZIGBEE, in MHO, it is worth exposing (one way or the other suggested by Jorge) so it can be used first hand as Primary Key in a table of devices.

**Comment by Koenkk** [comment]
Let's see how many people are interested in this feature. So if you are interested please 👍 the OP.

**Comment by sjorge** [comment]
I guess another alternative implementation would be a `minimal` value for `include_device_information` that just does ieeeAddr and maybe modelId. I'm 👎 on including the ieeeAddr always without a way to turn this off.

**Comment by Koenkk** [comment]
> I'm 👎 on including the ieeeAddr always without a way to turn this off.

I completely agree, if this ever gets merged it should be opt-in, not opt-out.

**Comment by ChihebBenSalem** [comment]
I totally agree of course that it should be opt-in 👍, so nothing changes unless some wants that info in the payload.

**Comment by ChihebBenSalem** [comment]
patch to include IEEE Address in the list of exposed fields (opt-in)

diff -ruN /home/pi/zigbee2mqtt/lib/controller.ts /opt/zigbee2mqtt/lib/controller.ts
--- /home/pi/zigbee2mqtt/lib/controller.ts      2022-12-13 22:40:25.297311929 +0100
+++ /opt/zigbee2mqtt/lib/controller.ts  2022-12-11 14:19:26.965304342 +0100
@@ -256,7 +256,10 @@
         if (entity.isDevice() && lastSeen !== 'disable' && entity.zh.lastSeen) {
             message.last_seen = utils.formatDate(entity.zh.lastSeen, lastSeen);
         }
-
+        // Add ieeeAddr
+        if (entity.isDevice() && settings.get().mqtt.include_ieee_information) {
+            message.ieeeAddr = entity.ieeeAddr;
+        }
         // Add device linkquality.
         if (entity.isDevice() && entity.zh.linkquality !== undefined) {
             message.linkquality = entity.zh.linkquality;
diff -ruN /home/pi/zigbee2mqtt/lib/types/types.d.ts /opt/zigbee2mqtt/lib/types/types.d.ts
--- /home/pi/zigbee2mqtt/lib/types/types.d.ts   2022-12-13 22:40:25.309311922 +0100
+++ /opt/zigbee2mqtt/lib/types/types.d.ts       2022-12-11 11:58:19.270175193 +0100
@@ -181,6 +181,7 @@
         mqtt: {
             base_topic: string,
             include_device_information: boolean,
+            include_ieee_information: boolean,
             force_disable_retain: boolean
             version?: number,
             user?: string,
diff -ruN /home/pi/zigbee2mqtt/lib/util/settings.schema.json /opt/zigbee2mqtt/lib/util/settings.schema.json
--- /home/pi/zigbee2mqtt/lib/util/settings.schema.json  2022-12-13 22:40:25.313311920 +0100
+++ /opt/zigbee2mqtt/lib/util/settings.schema.json      2022-12-11 12:00:30.670074225 +0100
@@ -189,6 +189,12 @@
           "description": "Include device information to mqtt messages",
           "default": false
         },
+        "include_ieee_information": {
+          "type": "boolean",
+          "title": "Include device IEEE address",
+          "description": "Include device IEEE address to mqtt messages",
+          "default": false
+        },
         "version": {
           "type": ["number", "null"],
           "title": "Version",
diff -ruN /home/pi/zigbee2mqtt/lib/util/settings.ts /opt/zigbee2mqtt/lib/util/settings.ts
--- /home/pi/zigbee2mqtt/lib/util/settings.ts   2022-12-13 22:40:25.313311920 +0100
+++ /opt/zigbee2mqtt/lib/util/settings.ts       2022-12-11 11:59:06.082137883 +0100
@@ -38,6 +38,7 @@
     mqtt: {
         base_topic: 'zigbee2mqtt',
         include_device_information: false,
+        include_ieee_information: false,
         force_disable_retain: false,
     },
     serial: {

**Pull request merged**
