### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Koenkk**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by ChadiEM** [comment]
Hey @Koenkk, I have some experience with [Renovate](https://github.com/renovatebot/renovate) for automated dependency updates and can help set it up if that's something you would be interested in.

**Comment by Koenkk** [comment]
@ChadiEM thanks for the offer, but I don't like the Renovates approach, it's spamming PRs as crazy (see e.g. https://github.com/nurikk/zigbee2mqtt-frontend/commits/dev/). An automatic weekly update seems like a much easier approach (this PR is created automatically every week).

**Comment by ChadiEM** [comment]
@Koenkk Renovate is still configurable to group PRs by certain criteria and the PR opening frequency can be modified as desired. 

But sure, it's your call ;-)

**Comment by Koenkk** [comment]
If it can create 1 PR every week that would be fine (same behaviour as now)

**Pull request merged**
