### PR TITLE
add Sengled E11-G13 bulbs to deviceAvailability.js

### PR DESCRIPTION
**Pull request by Iv4nS**

### CODE REVIEW

**Comment by Iv4nS** [comment]
#775 added Sengled E11-G13 bulb

**Comment by Koenkk** [comment]
Thanks, did you verify that it worked?

**Comment by Iv4nS** [comment]
@Koenkk  I wasn't able to, I'm running hassio and can't modify that specific file in my setup. I did try forking hassio-zigbee2mqtt and zigbee2mqtt and changing the referencing URLs and repos to point to my forks but it still pulled the original "Koenkk/zigbee2mqtt/dev"

If you have any directions on how to test it, let me know.

**Comment by Iv4nS** [comment]
I've found the way to test it locally in the docs! will test first and confirm here.

**Comment by Iv4nS** [comment]
@Koenkk tested and working! I'm liking the results of the feature!

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
