### PR TITLE
fixes related to #4070

### PR DESCRIPTION
**Pull request by mgrom**
fixes related to #4070

### CODE REVIEW

**Comment by presslab-us** [comment]
I tested this and there is another problem I didn't notice before.  `occupied_heating_setpoint` is used for both high and low topic settings, looks like just a typo.  The `occupied_cooling_setpoint` should be used for the high topic settings.  With that change it is working.

Maybe you could change the `temperatureStateProperty` for all the heat/cool devices to null, as it's not being used at all, but just a thought.  Like this
```javascript
'3157100':` [climate(10, 30, null, 1, ['off', 'heat', 'cool'],
```

**Comment by mgrom** [comment]
@presslab-us was it working before?
```
            temperature_low_state_topic: true,
            temperature_low_state_template: `{{ value_json.occupied_heating_setpoint }}`,
            temperature_high_state_topic: true,
            temperature_high_state_template: `{{ value_json.occupied_cooling_setpoint }}`,
            temperature_low_command_topic: 'occupied_heating_setpoint',
            temperature_high_command_topic: 'occupied_cooling_setpoint',
```
Seems like `occupied_heating_setpoint` was used for both even before.

**Comment by Koenkk** [comment]
Added the tests.

**Comment by mgrom** [comment]
thanks!

**Pull request merged**
