### PR TITLE
Add advanced.availability_lag option that will be random part of total availability timeout

### PR DESCRIPTION
**Pull request by andrewostroumov**
I think it's a good idea because it theoretically decrease network load

### CODE REVIEW

**Comment by andrewostroumov** [comment]
Add tests soon...

**Comment by Koenkk** [comment]
If I understand correctly, the goal of this PR to add a small random time to the availability timeout? 

If yes, I don't think you have to add an option for this, just enable it by default.

**Comment by andrewostroumov** [comment]
Sometimes you can’t rely on rand so it’s up to user to enable or no this

**Comment by Koenkk** [comment]
> Sometimes you can’t rely on rand so it’s up to user to enable or no this
> […](#)
> On 7 Feb 2021, 14:09 +0200, Koen Kanters ***@***.***>, wrote: If I understand correctly, the goal of this PR to add a small random time to the availability timeout? If yes, I don't think you have to add an option for this, just enable it by default. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Why not?

**Comment by andrewostroumov** [comment]
> > Sometimes you can’t rely on rand so it’s up to user to enable or no this
> > […](#)
> > On 7 Feb 2021, 14:09 +0200, Koen Kanters _**@**_.***>, wrote: If I understand correctly, the goal of this PR to add a small random time to the availability timeout? If yes, I don't think you have to add an option for this, just enable it by default. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Why not?

So let's add for example 10% of timeout as random part for default?

**Comment by Koenkk** [comment]
I'm fine with that!

**Comment by aureliosaraiva** [comment]
I really like having this feature. Today with many devices every 60s my network is extremely overloaded.

Having a random spacing helps a lot to discriminate over time.

**Comment by andrewostroumov** [comment]
So everybody agree to have 10% space?

**Comment by Koenkk** [comment]
@andrewostroumov yes, please. If you remove the settings part from the MR I will merge it.

**Comment by andrewostroumov** [comment]
So if you don't mind it's ready to merge

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
