### PR TITLE
Added log_file name setting

### PR DESCRIPTION
**Pull request by svh1985**
Added log_file to schema while preserving the default log.txt setting.
Added option to logger to use the filename and support for the %timestamp% var.

Still needs some testing.
```
  log_level: info
  log_directory: /var/log/
  log_filename: zigbee2mqtt.log # also allowes zigbee2mqtt_%TIMESTAMP%.log
  log_output:
    - console
    - file
```

Ref: https://github.com/Koenkk/zigbee2mqtt/issues/2889

### CODE REVIEW

**Comment by svh1985** [comment]
Just checked and verified:
- [x] Without setting it uses the default log.txt
- [x] Adding setting changes filename
- [x] Adding %TIMESTAMP% will add the timestamp
- [ ] Add filename to log and console.

**Comment by Koenkk** [comment]
Looks good, let me know once you are finished.

**Comment by svh1985** [comment]
@Koenkk done! I'm guessing you should update the doc's right?

**Comment by Koenkk** [comment]
Added it to the docs, thanks!

**Pull request merged**
