### PR TITLE
Update to new Home Assistant MQTT Fan discovery

### PR DESCRIPTION
**Pull request by cmccambridge**
Raising this pull request as a draft fix for #7318, but would like to get feedback on the approach. See questions below...

I've attempted to change **only** the presentation of the exposed `fan` objects to Home Assistant (of which the Hampton Bay 99432 is the only supported device today). This should not change:
- How fan modes of `climate` objects are presented
- Any interface other than the Home Assistant discovery

This draft pursues the solution where zigbee2mqtt presents to Home Assistant MQTT fan integration:
1. The ZCL fan speeds of `low`, `medium`, `high`, and `on` as four possible speed values. These will be mapped by the integration to 25%, 50%, 75%, and 100% respectively on the 2021.3+ fan entity. (0% is implicitly mapped to `OFF` state).
2. The ZCL fan presets of `auto` and `smart` as two `preset_modes`.

In the UI, this results in a fan entity like this:
image

Two specific open questions yet to resolve:
- [x] Is this modeling acceptable from the zigbee2mqtt side, given how Home Assistant is [defining fan entities](https://developers.home-assistant.io/docs/core/entity/fan/) going forward?
- [x] The specific fan that exists in `zigbee-herdsman-converters` today is the Hampton Bay 99432, which in my testing so far does not appear to actually do anything when set to Fan Mode `5` / `auto`. If it is indeed the case that this fan does not respond to `auto` mode, we may want to avoid exposing that mode in this or a separate PR, since it results in seemingly "broken" UI where the fan state is `ON` and fan mode is `auto`, and yet the fan itself does not rotate.

PR mechanics:
- [x] Tests are updated and passing
- [x] `eslint` clean
- [x] 100% coverage

### CODE REVIEW

**Comment by cmccambridge** [comment]
**Just** realized that there is likely a precedent to examine to help answer the first question: how to represent this fan in the Home Assistant fan entity model. Home Assistant's own ZHA integration may have support for this 99432 fan. I'll take a look at that tomorrow.

**Comment by cmccambridge** [comment]
The [`zha` fan in Home Assistant](https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/fan.py#L39) chooses a similar but slightly different approach:

1. The ZCL fan speeds of `low`, `medium`, and `high` (but **not** `on`) are modeled as **three** possible speed values. These will be mapped by the integration to 33%, 67%, and 100% respectively. (0% is still implicitly mapped to OFF state).
2. The ZCL fan modes of **`on`**, `auto`, and `smart` are modeled as three preset modes.

This is perhaps not as natural for the 4-speed Hampton Bay / Wink / King of Fans 99432 fan, but does seem like a more generic reading of the ZCL, since ZCL really _doesn't_ define "on" as a faster speed than "high". The 99432 fan seems to have stretched the spec a bit to get the features they wanted. Home Assistant acknowledges this weirdness:
```
# Spec is unclear as to what this value means. On King Of Fans HBUniversal
# receiver, this means Very High.
PRESET_MODE_ON = "on"
```

@Koenkk - do you have a preference there? To follow the Home Assistant lead, or to match the "4-speed" behavior of the 99432?

I'm happy to update the PR either direction: While the "4-speed" option that matches the specific fan I happen to own... the more generic interpretation from Home Assistant does make some logical sense as well, and I'm fine with that too.

**Comment by Koenkk** [comment]
@cmccambridge thanks for the PR, the generic HA way looks better IMHO

**Comment by cmccambridge** [comment]
Thanks for the input!

I've updated the PR to the generic 3-speed way that HA uses, which looks like this in practice:
image

I'd like to defer doing anything about the `auto` fan mode which doesn't appear to do anything on the 99432 fan, since that's not a change in behavior from this PR, and the HA implementation exposes that preset mode as well.

## Remaining TODOs
- [ ] Wait for upstream merge to support using a single MQTT topic for all state, percentage, and preset_mode interfaces: https://github.com/home-assistant/core/pull/50122
- [ ] Discuss backward compatibility

## Backward compatibility
Once merged, this PR as written would _require_ the user to be running a yet-to-be released HA build that incorporates the shared topic PR. A user could run a slightly older build with warnings (e.g. 2021.3 or 2021.4 I believe)... but for a good experience should be on that future one. A user running an _older_ build (2021.2 and older) would have their fan _break_.

How do you like to handle this for zigbee2mqtt?An alternative that _should_ work is to retain the old MQTT configuration in parallel for now, which would keep older HA instances running, and then remove the backward compatibility code at a future date. I would need to test whether the _new_ topics added by this PR cause any negative effect in older HA versions.

**Comment by Koenkk** [comment]
> A user could run a slightly older build with warnings (e.g. 2021.3 or 2021.4 I believe)... but for a good experience should be on that future one. A user running an older build (2021.2 and older) would have their fan break.

We've dealt with this situation before. It's simply waiting for the next HA release which will contain this + adding this to the release notes (e.g. 1.18.3 https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.18.3)

**Comment by mwav3** [comment]
As a user of the fan I figured I would chime in. I would much prefer to get support of all 4 speeds and breeze/smart mode then try and follow Home Assistant's ZHA lead. Zigbee2mqtt is superior to ZHA in my opinion which is why I use it over that. I would prefer 25% low, 50 medium, 75 medium high, 100 high, even though 100 maps to "on" vs high. Having only 3 speeds omits control of one of the speeds and reduces functionality of the fan. The home assistant fan template supports more then 3 speeds, I've seen users with 10 speed fans using the template.

Ultimately a custom fan template could be added by the user to get all 4 speeds working, but it would be nice to work properly "out of the box".

**Comment by cmccambridge** [comment]
@Koenkk Thanks - Home Assistant 2021.5.1 [includes the necessary fix](https://github.com/home-assistant/core/pull/50243):
> Ignore empty output from MQTT fan's value template

@mwav3 Agree. As a user of two of these controllers, I would also want my HA experience to include all 4 speeds on the slider, even if that isn't what ZHA does. If we merge this zigbee2mqtt PR as-is, I would be planning to write a template fan on the HA side to abstract it.

You're correct that the HA fan template in general allows an arbitrary number of speeds, e.g. 10, as does the MQTT fan integration. The core difficulty in this PR is that the zigbee protocol does _not_- the Zigbee Cluster Library Spec defines very specific modes... and doesn't define what they should _mean_.  (`off`, `low`, `medium`, `high`, `on`, `auto`, and `smart`).  The Hampton Bay/Wink/King of Fans 99432 controller has arbitrarily decided to use `low`, `medium`, `high` and `on` as 4 distinct speeds, plus `smart` to mean the "comfort breeze" feature... but this isn't a generic statement for the ZCL protocol, e.g. for fans integrated into climate controllers, or for a hypothetical future zigbee fan controller from another company.

So the trade off is... Implement the protocol in a generic way to be more correct, versus implementing something 99432-specific to meet the needs of the only fan that actually exists right now 😄. The first commit here did the 99432-specific interpretation (but for all exposed `fan`s), while the second commit moves in the direction of more generic.

@Koenkk - I saw a few model-specific tweaks in the `homeassistant` extension today, though both blocks are marked with a "deprecated" comment. If we do want to implement something 99432-specific _on top of_ the generic `fan` support... is there a preferred way to do that? I could write this into the `homeassistant` extension like the two lists of `model`s today... I believe it would also be possible to write an `external_converter` module to override on a single-device basis. Are there other options to look at as well? Is there a plan to support `zigbee-herdsman-converters` supplying device-specific discovery entries like external convertors can?

**Comment by Koenkk** [comment]
> Is there a plan to support zigbee-herdsman-converters supplying device-specific discovery entries like external convertors can?

zigbee-herdsman-converter and external converters are the same. I think we should fix the possible modes for this fan. Prepared a PR here: https://github.com/Koenkk/zigbee-herdsman-converters/pull/2565

**Comment by cmccambridge** [comment]
Hi @Koenkk ,

After a bit of delay I've gotten this PR updated to use the new support from the Home Assistant MQTT team (see discussion on #7318) which makes the 99432 fan possible to precisely model without any workarounds 😄 .

I rebased on latest `dev` branch and refactored the change into two commits:

1. First commit updates the Home Assistant discovery capability in general:
    - Move from deprecated "speeds" list to the new "percentage" + "presets" model.
    - Map each fan mode in [low, medium, high] to the percentage values.
    - Map each fan mode in [on, auto, smart] to a preset value.
    - Update tests accordingly. This commit makes the 99432 fan look like: "low, medium, high" + "on, smart" based on latest zigbee-herdsman-converters including your most recent PR.
2. Second commit adds the 99432-specific tweak to `homeassistant.js` to expose 4 speeds + 1 mode instead of 3 speeds + 2 modes.
    - Add a model-specific tweak to report the 99432 fan as: "low, medium, high, on" + "smart".
    - Update tests accordingly.

Each PR passes `eslint` and `test-with-coverage`, though I do want to note that there is no other fan to test the generic support with. The code works (can test it by disabling the 99432 tweak or testing the first commit in this PR) but I don't know if you'd like to see any additional testing on the generic support in case a second fan comes out some day?

Otherwise the testing as-is works correctly for 99432, and results in this end-to-end Home Assistant experience:
fan_smart

This PR must not be merged until upstream Home Assistant incorporates https://github.com/home-assistant/core/pull/50565 into a release, which would likely be 2021.6.

**Comment by Koenkk** [comment]
@cmccambridge thanks, I've set a reminder for 1 July.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
