### PR TITLE
fix: Improve permit join

### PR DESCRIPTION
**Pull request by Nerivec**
- Remove `permit_join` setting.
- Requires https://github.com/Koenkk/zigbee-herdsman/pull/1214

TODO:
- [x] https://github.com/nurikk/zigbee2mqtt-frontend/pull/2158
- [x] https://github.com/Koenkk/zigbee2mqtt.io/pull/3092
- [x] Update https://github.com/Koenkk/zigbee2mqtt/pull/24245 to new API
- [x] Re-check tests (and coverage) once rebased after legacy extensions are removed (_a few tests will fail until then_)

### CODE REVIEW

**Comment by Koenkk** [comment]
Merged `feat/2.0.0` into this and update `homeassistant.ts`

**Comment by Nerivec** [comment]
Will have to link the various branches (built) in package.json for all repos to sync up (at least for tests).

**Comment by Koenkk** [comment]
I think it would be the best to publish pre-release packages of the deps. Npm supports installing from Git but it won't contain the compiled TS code.

**Comment by Nerivec** [comment]
Do we want to implement the remaining TODO in https://github.com/Koenkk/zigbee-herdsman/pull/1214 ? It would be the only change left in ZH I think (need zh+frontend+z2m change).
I was thinking something along these lines:
```ts
interface PermitJoinChangedPayload {
    time: number; // [0-254]
    device?: Device; // not used at this time but aligns the API
}
```
And this gets emitted only on open and close, frontend does the ticking logic. `permitJoinTimeoutTimer` becomes a `setTimeout` instead of `setInterval`.
It removes ~`time * 1` mqtt publish of `/bridge/info`...

**Comment by Koenkk** [comment]
I'm not sure if we should solve that one, it will also break the HA permit join timeout (https://github.com/Koenkk/zigbee2mqtt/blob/e06848db8c5ad247c27e959eb85465a30134769f/lib/extension/homeassistant.ts#L2132). 1 message every sec shouldn't be heavy and permit join is off most of the time anyway.

**Pull request merged**
