### PR TITLE
Fix missing retain on add_group, allow specifying of groupID

### LINKED ISSUE #2264: Groups added with bridge/config/add_group are missing the 'retain' property
# Bug Report
## What happened
Added a test group by publishing
`test` to `zigbee2mqtt/bridge/config/add_group`, this resulted in

```
groups:
  '1':
    friendly_name: 'test'
```

To be added to the configuration (so far so good), however on restart zigbee2mqtt fails to start with the following error:

```
zigbee2mqtt:error 2019-11-03T19:38:49: Refusing to start, configuration.yaml is not valid, found the following errors:
zigbee2mqtt:error 2019-11-03T19:38:49:   - groups['1'] should have required property 'retain
```

This makes sense as 'retain' seems to be a required property for groups.

## What did you expect to happen
The group to have retain set to either 0 or 1

## How to reproduce it (minimal and precise)
Add a new group via mqtt

## Debug Info
zigbee2mqtt version: 1.6.0 @ dev from 20191103
CC253X firmware version: n/a

### PR DESCRIPTION
**Pull request by sjorge**
This PR fixes #2264, it also now accepts json input for add_group in the format of

```json
{
  "friendly_name": "my_group",
  "id": 123"
}
```

It is also possible to just provide and id, the friendly_name will then be `group_${id}` or just a friendly_name and the behavior will be the same as just sending the friendly_name as a string.

~~I still need to figure out how to get the tests to run so I can update them.~~ `npm run test` apparently ...

### CODE REVIEW

**Comment by sjorge** [comment]
All tests should work again, I also added extra tests to cover the new/changed parts. Hopefully.

**Comment by sjorge** [comment]
Oops a commit got cherry-picked that shouldn't be there, I don't think anyone but me is running this on SmartOS...

**Comment by sjorge** [comment]
Hurray! Green checkmarks all around! Time for bed.

**Comment by Koenkk** [comment]
Awesome, big thanks!

**Pull request merged**
