### PR TITLE
Mt api set time

### PR DESCRIPTION
**Pull request by tb-killa**
This implements the SYS_SET_TIME (setTime) Functionality for the Coordinator Stick via Z Stack MT API.
It allows the right time in TI-Stack and maybe we could use it for another stuff in future.
Attention: This is for the first only on hardware side effect.

### CODE REVIEW

**Comment by Koenkk** [comment]
Is there a notable change after this?

**Comment by tb-killa** [comment]
I check if this is the base of the timestamp calculation.

**Comment by tb-killa** [comment]
Hi @Koenkk ... 
i see that @HalleyAssist implement this directly:
https://github.com/HalleyAssist/zigbee-shepherd/commit/541ef60342bc37f75b43fbea1c5edb632b67bb6b
https://github.com/HalleyAssist/zigbee-shepherd/commit/01cc44ae9ba9831bde278b33ddda9ef794b1c348

Maybe @splitice could tell more about what exactly happen now ..?

**Comment by splitice** [comment]
ZCL queries for the time are now accurate.

**Comment by tb-killa** [comment]
@splitice Does this means the End-Device could use the "Time" Cluster to get the actually time?

**Pull request closed without merging**
