### PR TITLE
Added icon and device_class for some Aqara device entities

### PR DESCRIPTION
**Pull request by mrskycriper**
Added `icon` and `device_class` for secondary entities of these Aqara devices:
### SRTS-A01 (Smart Radiator Thermostat E1)
- `setup` with `device_class: 'running'`
- `valve_alarm` with `device_class: 'problem'`
- `window_open` with `device_class: 'window'`
- `valve_detection` with `icon: 'mdi:pipe-valve'`
- `window_detection` with `icon: 'mdi:window-open-variant'`
- `sensor_temp` with `icon: 'mdi:thermometer'`
- `sensor` with `icon: 'mdi:tune'`
- `calibrate` with `icon: 'mdi:tune'`

### SP-EUC01 (EU smart plug)
- `auto_off` with `icon: 'mdi:flash-auto'`
- `overload_protection` with `icon: 'mdi:flash'`

### RTCGQ14LM (P1 human body movement and illuminance sensor)
- `trigger_indicator` with `icon: 'mdi:led-on'`
- `detection_interval` with `icon: 'mdi:timer'`

### WS-EUK01 (Smart wall switch H1 EU (no neutral, single rocker))
- `mode_switch` with `icon: 'mdi:tune'`

### Almost all Aqara devices
- `power_outage_count` with `icon: 'mdi:counter'`

### CODE REVIEW

**Comment by sjorge** [comment]
This can be set on the expose data now, e.g. power_outage_count got it updated in this change https://github.com/Koenkk/zigbee-herdsman-converters/commit/2c08cdc6cae73555f66469036f2dd6c5b0535a14#diff-5ec1d2e171ffffe0fed4b8c16747c7db4925aa15553a4c9fa8d71bbb2c45bf6aR741

**Comment by Koenkk** [comment]
@sjorge you are right, @mrskycriper please use the `withCategory` on the expose instead (`icon` can stay in this PR)

**Comment by mrskycriper** [comment]
Thanks for clarifications @sjorge @Koenkk , I'll update the PR later and make a new one in zigbee-herdsman-converters. Also, should I leave `device_class` here or is there a better way to change it?

**Comment by Koenkk** [comment]
`device_class` can be kept here.

**Comment by mrskycriper** [comment]
@Koenkk I've removed all mentions of `entity_category` from this PR. However, I can't seem to make the necessary changes in the converter. I've copied existing converter for SRTS-A01 into external converter, but no changes ever apply to the device. I've reset, reconfigured and restarted everything multiple times to no avail. Am I missing something?

**Comment by Koenkk** [comment]
@mrskycriper can you try changing the description and see if it is reflected in the z2m frontend?

**Comment by mrskycriper** [comment]
@Koenkk that is the strange part, absolutely no reaction on any change in descriptions. As if the external converter doesn't exist

**Comment by Koenkk** [comment]
Did you add it to your z2m configuration.yaml or do you see an error message about loading the external converter at startup?

**Comment by mrskycriper** [comment]
@Koenkk found it in the logs and fixed the imports. Now it kinda works, but the custom local fromZigbee and toZigbee converters need a custom type `Buffer` and it looks looks like external converter doesn't have the necessary npm package in its environment. And without it I cant test the functionality of re-categorized controls, mentioned [here](https://github.com/Koenkk/zigbee-herdsman-converters/issues/6887)

**Comment by mrskycriper** [comment]
Created PR for continued discussion https://github.com/Koenkk/zigbee-herdsman-converters/pull/6922

**Pull request merged**
