### PR TITLE
Partial fix for #4571, changed current_heating_setpoint

### PR DESCRIPTION
**Pull request by EmilFlach**
New version of the eurotronic hardware doesn't work with `current_heating_setpoint`.
Changing this to `occupied_heating_setpoint` does work and (from the reports in the thread) is backwards compatible with older hardware.

### CODE REVIEW

**Comment by sjorge** [comment]
There are some reports it does brake the old one: https://github.com/Koenkk/zigbee2mqtt/issues/4571#issuecomment-716801787

**Comment by pY4x3g** [comment]
> There are some reports it does brake the old one: [#4571 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/4571#issuecomment-716801787)

I tried the fix again and now its working fine with the old and new devices. Thank you all for the help.

**Comment by EmilFlach** [comment]
To be completely sure we could support the newer hardware as a separate device. Not sure how to do that, but I could spend some time to figure that out. I assume it would be possible to detect the older vs new version based on the `hwVersion`, right?

**Comment by sjorge** [comment]
The other properties are still broken on both versions right?

Might be better to dig and fix it properly instead of splitting.

**Comment by EmilFlach** [comment]
That's also a fair point, this is just a quick fix for one property. I do think setting the temperature is the most important part of the TRV and it warrants a quick fix while investigating the other issues.

**Comment by Koenkk** [comment]
What is the state of this PR, should it be merged? (does setting temperature work on both old and new?)

**Comment by sjorge** [comment]
> What is the state of this PR, should it be merged? (does setting temperature work on both old and new?)

I'm not sure, 'seems' to be fine i think.

But my old one that I repaired to verify is just acting all weird. Starts of with INVALID_VALUE too and no reporting, after a while it started reporting and I could set it with both properties... the display updates but the valve doesn't seem to move. And we're back to no reporting, followed by reporting a few minutes after and the valve moves.

There might have been a change that is somehow making the firmware on the device unhappy, be it new or old?

I also just dropped it when removing it and now it is rattling so not sure I can do more testing with it.

**Comment by EmilFlach** [comment]
To be clear, this change should be fine according to the manual of the device:
image
 
https://eurotronic.org/wp-content/uploads/2019/11/Spirit_ZigBee_BAL_web_EN_November-2019.pdf

**Comment by Koenkk** [comment]
Good, I will merge this.

**Comment by heggink** [comment]
Is this partial fix only applicable for homeassistant or will it work for domoticz as well?

**Comment by pY4x3g** [comment]
Unfortunately, the new devices stopped answering today with this fix. (the old ones still where working fine) Had to restart zigbee2mqtt to work again. Maybe it was just random those two new ones. I will investigate further.

**Comment by sjorge** [comment]
That seems to match the behavior of my old one. It’s fine for a bit with either of them and would them break again.

~ sjorge

**Comment by EmilFlach** [comment]
Do you think it's related to using occupied_heating_setpoint? Your experiences with very inconsistent behavior makes me doubt whether I should purchase more of these thermostats...

**Pull request merged**
