### PR TITLE
fix(ignore): removes cached data/configuration.yaml

### PR DESCRIPTION
**Pull request by mateja176**
Firest reference `.gitignore`:
```
# Ignore config
data/*.yaml
!data/configuration.example.yaml

```

Second reference [Linux configuration docs](https://www.zigbee2mqtt.io/guide/installation/01_linux.html#configuring).

### CODE REVIEW

**Comment by Koenkk** [comment]
I really would like to get rid of this file but it will break existing setups (for those having checkout before https://github.com/Koenkk/zigbee2mqtt/commit/70a72dd32af20d5a391e7d4e9a76364a8a2bc1d9)

**Comment by mateja176** [comment]
> I really would like to get rid of this file but it will break existing setups (for those having checkout before [70a72dd](https://github.com/Koenkk/zigbee2mqtt/commit/70a72dd32af20d5a391e7d4e9a76364a8a2bc1d9)

Let’s imagine that John Doe cloned the repo before ‘70a72dd’. If John pulls the latest commit, following this PR, his local ‘configuration.yaml’ will be preserved. What’s the scenario you’re wary about?

**Comment by Koenkk** [comment]
He will get a merge conflict I believe

**Comment by mateja176** [comment]
> He will get a merge conflict I believe

I've tested a couple of scenarios:
- If `data/configuration.yaml` hasn't been updated, it will get deleted after pulling this commit. Though **no** data is lost, becuase it's straightforward to recreate it by running `cp data/configuration.example.yaml data/configuration.yaml` or copy-pasting its contents from the git history.
- If `data/configuration.yaml` has been updated, it's a prerequisite to backup the changes and discard them from the working directory, in which case it's trivial to recreate the file from the backup. Alternatively, if the changes are stashed before pulling this commit, after poping the stash and choosing the option `Keep their version`, the file will be added to the working directory in conjunction to being ignored by git.

**Comment by Koenkk** [comment]
can you integrate these changes in the update.sh script? I know not all users use this and I still expect a lot of issues to be reported due to this change but at least we tried 😀

**Comment by stefanrenne** [comment]
@Koenkk to get more awareness for the update.sh script, maybe its an idea to update this page ;) https://www.zigbee2mqtt.io/guide/installation/01_linux.html#for-later-update-zigbee2mqtt-to-the-latest-version

**Comment by Koenkk** [comment]
@stefanrenne done!

**Pull request closed without merging**
