### PR TITLE
Add device class for Update Available

### PR DESCRIPTION
**Pull request by robertalexa**
As per title.

This is the link to the documentation for Binary Sensor which shows support for device class `update`
https://www.home-assistant.io/integrations/binary_sensor/

This will change the entity from :
image

To something like this one:
image

### CODE REVIEW

**Comment by robertalexa** [comment]
Koen, the tests are failing with or without my change, I think this must have been introduced by something else?

**Comment by Koenkk** [comment]
Fixed the tests, thanks!

**Comment by Koenkk** [comment]
I just see that this has already been done in the dev branch so this is not needed anymore: https://github.com/Koenkk/zigbee2mqtt/blob/51321affcf726a5d72b341a281249738b04de664/lib/extension/homeassistant.ts#L960

**Comment by robertalexa** [comment]
Oh i didn't realise this, my bad. Thank for looking into this

**Pull request closed without merging**
