### PR TITLE
WIP - Add "components" in devices response

### PR DESCRIPTION
**Pull request by carldebilly**
@Koenkk Here's a proposal...

Current Z2MA (my tool) is parsing topics to find supported "components" of each devices.  It would be a lot easier to have something like this PR.

What do you think?

### CODE REVIEW

**Comment by sjorge** [comment]
This does add a lot of extra clutter for people not using hass.io or z2ma though.

Can't the data be requested from the homeassistant via MQTT or something? Currently if you don't enable the support for homeassistant, is rather clean and non intrusive.

You could probably register a topic like
homeassistant/components/get and make it respond with the list if you send it the device_id or friendly_name ?

**Comment by Koenkk** [comment]
I agree with @sjorge 

What information do you actually need on the z2ma side, the home assistant auto discovery configs?

**Comment by carldebilly** [comment]
@Koenkk @sjorge 
I pushed a new commit, moving the responsibility into the "hass" extension... is it better like that?

**Comment by Koenkk** [comment]
@carldebilly please help me understanding in what you want to accomplish, as far as I can see now you are trying to retrigger and send of the home assistant discovery topics?

**Comment by Kryzek** [comment]
@koenkk I would guess this relates to https://github.com/yllibed/Zigbee2MqttAssistant/issues/130

**Comment by carldebilly** [comment]
@Koenkk Yep.  The goal was mainly to have the ability to remove the requirement to activate the Home Assistant integration.

**Pull request closed without merging**
