### PR TITLE
Edp redy - Power Plug

### PR DESCRIPTION
**Pull request by dgomes**
This is a resubmission of #44 

Smart Plug sold by Portuguese Energy Provider EDP under the power management package RE:DY

### CODE REVIEW

**Comment by dgomes** [comment]
I've configured the plug using:

```js
const ID = '0x00124b000c034c83'
const device = message.endpoints[0].device;
if (device.ieeeAddr === ID) {
    device.epList.forEach((ep) => {
        const dev = this.zigbee.shepherd.find(ID, ep);
        console.log(dev.clusters);
        dev.report('seMetering', 'instantaneousDemand', 3, 60, 1, (err) => console.log(err));
    });
}
```

**Comment by Koenkk** [comment]
Can you check your repository? This pull request contains 31 commits.

**Comment by dgomes** [comment]
I believe you can squash all the commits upon merge

**Comment by dgomes** [comment]
https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits

**Comment by Koenkk** [comment]
I did some refactoring, can you allow me write rights to dgomes/zigbee2mqtt edp_rdy branch? After that I can merge this PR.

**Pull request merged**
