### PR TITLE
feat: Let Home Assistant generate entity name when device_class is present

### PR DESCRIPTION
**Pull request by Koenkk**
Merge after https://github.com/home-assistant/core/pull/95159 is released

### CODE REVIEW

**Comment by lluisd** [comment]
@Koenkk can this fix be related to my opened issue? https://github.com/Koenkk/zigbee2mqtt/issues/18201

**Comment by Koenkk** [comment]
I don't think so, https://github.com/home-assistant/core/pull/95159 is not merged yet. Since you also experience this after a Z2M rollback I think it is caused by HA and not by Z2M

**Comment by lluisd** [comment]
> I don't think so, [home-assistant/core#95159](https://github.com/home-assistant/core/pull/95159) is not merged yet. Since you also experience this after a Z2M rollback I think it is caused by HA and not by Z2M

sorry, I mean that when this PR is merged it will fix my issue as I see. becuase the name of the payload config is with _ underscores and the prefix of the device. With this PR you only uses the device class name as an entity name.

**Comment by Koenkk** [comment]
Nothing has been changed regarding this with 1.32.0, if you want to debug this further I need to know the latest working z2m version

**Comment by BudBundi** [comment]
> Merge after [home-assistant/core#95159](https://github.com/home-assistant/core/pull/95159) is released

Is merged, HA beta is showing a warning, about the naming

**Comment by Koenkk** [comment]
@BudBundi thanks for the ping, do you know if this solves https://github.com/Koenkk/zigbee2mqtt/issues/18445 ?

**Comment by BudBundi** [comment]
Updated the Add on of Zigbee2mqtt Edge, restart HA but the error message reappear. So it seems it is not fixed.

**Comment by BudBundi** [comment]
Okay, I took a quick look at it.

From the linked site 

> The mandatory fields were previously limited to at least one of connection and identifiers, but has now been extended to at least one of connection and identifiers as well as the name.

when looking at one of the entities with an MQTT explorer shows:
```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    },
    {
      "topic": "zigbee2mqtt/Licht_Eingang_draußen/availability"
    }
  ],
  "availability_mode": "all",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x680ae2fffed624f1"
    ],
    "manufacturer": "Gledopto",
    "model": "Zigbee LED Controller RGB+CCT (pro) (GL-C-008P)",
    "name": "Licht_Eingang_draußen",
    "sw_version": "V_1_4"
  },
  "enabled_by_default": false,
  "entity_category": "diagnostic",
  "icon": "mdi:signal",
  "json_attributes_topic": "zigbee2mqtt/Licht_Eingang_draußen",
  "name": "Licht_Eingang_draußen_linkquality",
  "state_class": "measurement",
  "state_topic": "zigbee2mqtt/Licht_Eingang_draußen",
  "unique_id": "0x680ae2fffed624f1_linkquality_zigbee2mqtt",
  "unit_of_measurement": "lqi",
  "value_template": "{{ value_json.linkquality }}"
}
```

I see identifiers and name, but connection is missing
not sure if it means what is stated on https://developers.home-assistant.io/docs/device_registry_index
<html><body>


connections | A set of tuples of (connection_type, connection identifier). Connection types are defined in the device registry module.
-- | --



</body>
</html>

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/18445

**Pull request merged**
