### PR TITLE
Allow no timestamp in log directory

### PR DESCRIPTION
**Pull request by azuwis**
I'd like to use logrotate to manage(rotate, compress) the log, add option to allow no timestamp in log directory.

### CODE REVIEW

**Review by ryanbeaton — COMMENTED** [review]
Becaus of https://github.com/Koenkk/zigbee2mqtt/issues/182 you may need to invert your approach, as in an advanced option for no tinestamping

**Comment by ryanbeaton** [comment]
Yes :)
No timestamp is how it used to be and #182 changed it to timestamp. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by azuwis** [comment]
> Yes :)
> No timestamp is how it used to be and #182 changed it to timestamp.
> 
> Sent with [GitHawk](http://githawk.com)

Done.

**Comment by Koenkk** [comment]
Updated the option to `log_directory_timestamp` (which is `true`) by default.

Thanks!

**Comment by Koenkk** [comment]
in 2fd59cb7efbfc4b0930e6cdc50dfddbdbe37a027 I've removed this option and merged it with the `log_directory` option.

`%TIMESTAMP%` is now used as a placeholder for the timestamp in `log_directory`. 

e.g.
- `/var/log/%TIMESTAMP%` will produce directories with timestamp
- `/var/log` without (which replaced this option).

**Pull request merged**
