### PR TITLE
feat: add support for ingress multiplath

### PR DESCRIPTION
**Pull request by jlpedrosa**
Hi @Koenkk 

I thing the chart is ready to be released, i did the full process on my fork.

Index is available (in my fork) : https://jlpedrosa.github.io/zigbee2mqtt/index.yaml
Package can be downloaded and installed: 
```
zigbee2mqtt            29m   True    Helm install succeeded for release homeassistant/homeassistant-zigbee2mqtt.v1 with chart zigbee2mqtt@1.37.1
```

Deployment seems to work just fine:
image

### CODE REVIEW

**Comment by Koenkk** [comment]
I already trigger a chart release before seeing this PR ([run](https://github.com/Koenkk/zigbee2mqtt/actions/runs/9037283408/job/24835977329)), can this PR go to dev?

**Comment by jlpedrosa** [comment]
Yes, it can be put to dev, no issues. changed.

The release was correct only at 50%. 
The index file was generated correctly: https://github.com/Koenkk/zigbee2mqtt/blob/gh-pages/index.yaml
But the artifact has not been added to the release, it contains only the sources, not the actual helm chart, the ref in the index points to: https://github.com/Koenkk/zigbee2mqtt/releases/download/zigbee2mqtt-1.37.1/zigbee2mqtt-1.37.1.tgz

which doesn't exist... :face_exhaling:

**Comment by Koenkk** [comment]
@jlpedrosa I removed that release, I only want the real z2m releases there. Is that a problem?

**Comment by jlpedrosa** [comment]
yes, that is the URL included in the index, so that is were the charts gets downloaded. I can change the release name so it matches the one you already creates, not sure if it will fail or will add it to yours.

**Comment by jlpedrosa** [comment]
@Koenkk I have been banging my head against the wall with this for a long time. helm-releaser does not support it append the chart to an existing release. I created a patch to fix it upstream. They don't seem to be reviewing PR at all: https://github.com/helm/chart-releaser/pull/407
Options:

Have the two tags in this repo.
Wait for upstream to fix it (we can grow old waiting IMO)
Move the chart to another repo.
Do a lot of code to release here in the same repo.
Stop software engineering and open a bar in the bermudas.

**Comment by Koenkk** [comment]
> Move the chart to another repo.

I guess this option makes the most sense. We can trigger an update similar as we do for the HASS addon: https://github.com/Koenkk/zigbee2mqtt/blob/c02c61dd5698b47fcb83ea5d7de39e627d498e58/.github/workflows/ci.yml#L87

**Comment by jlpedrosa** [comment]
Hi, what ever you want, this is how I set it up for another OSS project: https://github.com/unpoller/helm-chart/ 
We indeed trigger the release from the other repo. 

Let me know when you've created the repo. If you want to give me write-access, I can help you maintain it.

In any case, let me know when you've created the repo. Remeber the gh-pages branch.

**Comment by Koenkk** [comment]
> Hi, what ever you want,

If we don't want multiple tags in this repo, a separate repo is the only solution, right?

**Comment by jlpedrosa** [comment]
There's another way that in theory can be used which is the github packages (not releases) and use it as OCI helm repository. I am not positive, but I think it has the drawback of renovate/dependabot not being able to "crawl" the repo (because there's no index.yaml), note I am not positive.

Other option is to create the index.yaml "manually/script" and upload thr file to the exisisting release.

So yes, there are solutions, but require a decent amount of time.to get it working.

**Comment by Koenkk** [comment]
Then let's go for the separate repo, added you to https://github.com/Koenkk/zigbee2mqtt-chart

**Pull request closed without merging**
