### PR TITLE
Deprecate Home Assistant entity attributes

### PR DESCRIPTION
**Pull request by frenck**
This PR deprecates the use of Home Assistant entity attributes.

There are multiple reasons to deprecate support for this:

- Home Assistant has been actively reducing and rejecting the use of additional/separate states in the entity attributes.
- The entity attributes provided by the Home Assistant discovery in Zigbee2MQTT are duplicates of other entities.
- Attribute updates trigger updates in the Home Assistant state machine for the entity. E.g., the humidity attribute of a temperature entity changes... thus triggers a state update for the temperature entity. This is confusing and unneeded.
- Entity attributes are harder to use in Home Assistant automations. There is no need either, as they are already available as separate entities.
- All state changes are stored in the database, including their attributes (as it is part of the state). This means a lot of additional overhead is stored.

Additionally, it helps to provide a better experience with Zigbee2MQTT out of the box.

An advanced configuration parameter is provided to restore old behavior if needed.

```yaml
advanced:
  homeassistant_legacy_entity_attributes: true
```

Before:

image

After:

image
(ignore the state in this screenshot, it's about the attributes column)

Documentation PR: https://github.com/Koenkk/zigbee2mqtt.io/pull/780

### CODE REVIEW

**Comment by frenck** [comment]
Rebased PR onto the latest `dev` branch to catch up with changes. Adjusted the tests to match those latest changes and pass again.

**Comment by frenck** [comment]
Rebased PR onto the latest dev branch to catch up with changes.

**Comment by Koenkk** [comment]
Thanks! 😄

**Comment by andriej** [comment]
How about remote 'action' attributes on battery entities?
Currently it's the way to do automations based on button pressed in YAML (as device-trigger is UI only or needs separate automation per each button/action).

Will it stay?

**Comment by frenck** [comment]
That is not related to this change.

For your subject, you can find documentation here: <https://www.zigbee2mqtt.io/integration/home_assistant.html#responding-to-button-clicks>

**Pull request merged**
