### PR TITLE
feat: Support automatically generating device definitions

### PR DESCRIPTION
**Pull request by Koenkk**
- Enables the device definition generator implemented by @ffenix113 in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6692
  - This means that; for unsupported devices, standard functionality will now be detected out-of-the-box (without the need of making any code changes)
- As we encourage users to add official support for devices (such that they e.g. appear on the [supported devices page](https://www.zigbee2mqtt.io/supported-devices/)), a generate external definition feature is added:

**TODO**
- [x] Extend device definition generator a bit more to at least support lights and electrical measurements
- [x] Update [How to support new devices page](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html)
- [x] Enable the device definition generator and test
- [x] Check support new devices issue template

**Related PRs**
- https://github.com/Koenkk/zigbee-herdsman-converters/pull/6760
- https://github.com/nurikk/zigbee2mqtt-frontend/pull/1866
- https://github.com/Koenkk/zigbee2mqtt.io/pull/2436

CC: @ffenix113, @kirovilya, @sjorge, @nurikk, @mundschenk-at

### CODE REVIEW

**Comment by sjorge** [comment]
- Should we show the button for supported devices? 
- Maybe add a save option like we do with extensions (although I don't think we have an api endpoint to reload an external definition, would that even make sense?)

**Comment by Koenkk** [comment]
> Should we show the button for supported devices?

Yes, in case e.g. an already supported device does not have all features in the definition, the generated definition can be used instead

> Maybe add a save option like we do with extensions (although I don't think we have an api endpoint to reload an external definition, would that even make sense?)

Ideally you should be able to edit the external definition directly from the frontend for quick prototyping.

**Comment by sjorge** [comment]
> Ideally you should be able to edit the external definition directly from the frontend for quick prototyping.

If the external one takes priority over one from zhc, this would be great when adding new features to a device indeed!

**Comment by Koenkk** [comment]
> If the external one takes priority over one from zhc, this would be great when adding new features to a device indeed!

That's already the case (ext converter always takes priority over ZHC definition)

**Comment by Koenkk** [comment]
Just in time for Christmas, merry Christmas all! 🎄

**Pull request merged**
