### PR TITLE
Add device and groups descriptions

### LINKED ISSUE #7161: Own notes for devices
## Is your feature request related to a problem? Please describe
No

## Describe the solution you'd like
A way to add my own note for device

## Describe alternatives you've considered
Could not find any.

## Additional context
From time to time I get device unavailable , sometimes it is related to mesh changes and connectivity but sometimes it is related to battery which needs to be replaced what is actually fine after 2 years for some devices.

Because not all batteries need to be replaced at the same time so I would like to add note to my device e.g. battery replaced YYYY-MM-DD

If it would be possible to send this information to HA would be even better so I can quickly check that device is unavailable but not because of battery which was replaced month ago.

I tried to find such functionality but I could not

### PR DESCRIPTION
**Pull request by tripplet**
Implements descriptions for devices and groups as options
Fixes #7161

### CODE REVIEW

**Comment by Koenkk** [comment]
@nurikk could you add this to the frontend?

**Comment by nurikk** [comment]
devices - done

**Comment by pepp86** [comment]
Like so much, that this feature is there now. But how to update description through MQTT? Did not find any hint.

**Comment by tripplet** [comment]
@pepp86 You can change a description using the `zigbee2mqtt/bridge/request/device/options` topic, see [documentation ](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-device-options)

Example:
```
mosquitto_pub -h "localhost" -u user -P "password" \
    -t "zigbee2mqtt/bridge/request/device/options" \
    -m '{"id": "ieee_addr or friendlyname", "options": {"description": "the new description"}}'
```

If you want the request the current description you can trigger a new publish of the device info using:
```
mosquitto_pub -h "localhost" -u user -P "password" \
    -t "zigbee2mqtt/bridge/request/device/options" \
    -m '{"id": "ieee_addr or friendlyname", "options": {}}'
```
The options of all devices will then be published to `zigbee2mqtt/bridge/devices` see [documentation ](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-devices)

**Pull request merged**
