### PR TITLE
Read/write exposed enums are now discovered as MQTT Select entities

### PR DESCRIPTION
**Pull request by ruifung**
In Home Assistant 2021.7, a new type of entity (select) was added and can now be configured via MQTT Discovery.

This change makes enums exposed with STATE and SET to be discovered as select entities in home assistant in addition to a sensor (that is a disabled entity by default).

Requires at least home assistant 2021.7 for select entities to work.

### CODE REVIEW

**Comment by Koenkk** [comment]
Looks good, I will merge this after the next z2m release in dev (1 August), then it will be included in the 1 September release. This gives people some time to update HA.

**Comment by ruifung** [comment]
That, and this is likely to be breaking for people that have setups that depend on reading the state of some enum property via a sensor.

**Comment by Koenkk** [comment]
Good point, it will indeed.

Might be better to return both configs for now, can you modify this function to return an array instead of one `discoveryEntry`?

**Comment by ruifung** [comment]
With this change, I don't think you need to wait until september for people to update as the old sensor behavior has been restored, albeit with the enabled_by_default flag set to false to disable new sensor entities by default if select entities are present.

Use cases:
1. Those who have existing sensor entities will still have them, enabled_by_default doesn't affect existing entities..
2. Those who haven't updated, should just get a warning in the HASS log about an unsupported integration 'select', everything else just works as usual.
3. Those who are adding new devices will get disabled sensor entities (and can enable them in HASS if wanted.)

**Comment by Koenkk** [comment]
Yes you are right, thanks!

**Comment by frenck** [comment]
Running this one dev, one comment I have:

image

These entities are not really "common". As in, they can be useful, but probably most people won't use them in their automation or dashboards in general. Therefore, it is recommended to send a disabled by default in Home Assistant. This allows a user to enable them when needed, but not overwhelm the user with entities they do not need or pollute the database unneeded.

Can we adjust this for this feature before release it to the public?

**Comment by frenck** [comment]
Additionally, opened issue #8078, as this PR is generating warnings as it sends in unexpected/invalid values.

**Comment by frenck** [comment]
Extracted my above listed comment/report into its own issue here: #8083

**Pull request merged**
