### PR TITLE
Added new device DTB-ED2004-012 and added new cfg light_switch

### PR DESCRIPTION
**Pull request by swissbyte**
Hi

i would like to add HA support for my new Device DTB-ED2004-012
Since this device does only contains a switch and does usually switch a lamp, i decided to add a new configuration to homeassistant.js

```
    'light_switch': {
        type: 'light',
        object_id: 'light',
        discovery_payload: {
            brightness: false,
            schema: 'json',
            command_topic: true,
        },
    },
```

Unfortunately, there was no "switch only" lamp actually. 

Thanks for your great project.
Regards
Claudio

### CODE REVIEW

**Comment by Koenkk** [comment]
Also depends on the outcome of https://github.com/Koenkk/zigbee-herdsman-converters/pull/1191/files#r416675206, but until now these devices always have been integrated as a switch so I prefer to do the same for this.

**Comment by swissbyte** [comment]
But the sad thing about the switch is, that it will not group to the lights in home assistant. Therefore the user experience would be quite bad if you install a light and it does not appear under lights. I have already tested this modification and it has worked perfectly in HA.

**Comment by Koenkk** [comment]
I think it's possible via https://www.home-assistant.io/integrations/light.switch/

**Comment by swissbyte** [comment]
> 
> 
> I think it's possible via https://www.home-assistant.io/integrations/light.switch/

Hi Koen 
Thank you for this link. 
Ok, you have convinced me. I will change my configtype back to a switch.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
