### PR TITLE
Fix cover state publishing of multi-endpoint devices

### PR DESCRIPTION
**Pull request by Atokulus**
When using multi-endpoint devices with covers, the state for the covers is not published. This results in Home Assistant and other clients to believe the state is "unknown" and the entity to be offline.

### CODE REVIEW

**Comment by Atokulus** [comment]
Just adding some testing.

**Comment by Atokulus** [comment]
Dear @Koenkk
I hope this finds you well.

I am currently trying to fix an important bug, where the cover state is always 'unknown' for each of the cover endpoints on Siglis zigfred plus smart in-wall switch. The bug eventually causes some lovelace cards in Home Assistant to show the device as disabled (e.g. Mushroom cards), or Google Home not showing the entity as reachable (and disabling controls).

So far I seem to have fixed it, and try to add a new Jest test to have coverage on the new code segment. Yet I face some problems:

- The `zigbee2mqtt/zigfred_plus/get` `{state: ""}` command does not call the endpoint read handlers on the mock device in the Jest test. I checked whether this has to do with the dynamic expose, but it does not seem the case. See https://github.com/Koenkk/zigbee2mqtt/pull/14200/files#diff-e5529dd6d95cc6412d41048a450c6d2b3647beaba2e5489a02094ab5b4441d4fR518
- `zigbee2mqtt/zigfred_plus/get` `{position: ""}` or `zigbee2mqtt/zigfred_plus/get` `{tilt: ""}` does not work at all. Is there some filtering beforehand in `homeassistant.ts`? `zigbee2mqtt/zigfred_plus/get` `{brightness: ""}` is working so far for the light endpoints.
- Also, there might be a need for `tz.cover_state` to implement an empty `convertGet`) in the future. As zigfred plus is currently the only device implementing multiple cover endpoints, this is less critical.

I hope you find all the information needed above😄 If not, please ask right away.

Best regards and have a very nice week
Markus

**Comment by Atokulus** [comment]
See also https://github.com/Koenkk/zigbee-herdsman-converters/pull/4709

**Comment by Atokulus** [comment]
I did some more testing and realized that `position` and `tilt` attributes have been wrongfully advertised as `position_l?` and `tilt_l?` to Home Assistant.
The PR should be good to go as soon as there is a release of `zigbee-herdsman-converters`.

Many thanks and best regards
Markus

**Comment by Koenkk** [comment]
The PR should be based against the dev branch but it seems there is a merge conflict now. Can you check that?

**Comment by Atokulus** [comment]
@Koenkk Thanks for the hint! It merged and had to apply some small fix regarding the added `value_template`. I tested it successfully within Home Assistant with actual hardware.

Best regards
Markus

**Pull request merged**
