### PR TITLE
fix: Add secure default config

### PR DESCRIPTION
**Pull request by Koenkk**
Fixes https://github.com/Koenkk/zigbee2mqtt/issues/16188

Other PRs:
- https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/pull/510
- https://github.com/Koenkk/zigbee2mqtt.io/pull/2135

### CODE REVIEW

**Comment by bharvey88** [comment]
Although I am happy about this I was really hoping to get pan_id and ext_pan_id and network_key all randomized not just network_key.

**Comment by Koenkk** [comment]
Why do you want to randomize the pan_id/ext_pan_id? They have nothing to do with security, you can obtain those from every network by sniffing (without knowing the network key)

**Comment by MattWestb** [comment]
> Why do you want to randomize the pan_id/ext_pan_id? They have nothing to do with security, you can obtain those from every network by sniffing (without knowing the network key)

So you can also see it but in in Zigbee and other 802.15.4 network its one part of the security configuration. 
Also you is getting mush problems then users is setting up more Z2M systems in radio range and getting strange problems in there systems then all is badly configuration from start.

**Comment by bharvey88** [comment]
> Why do you want to randomize the pan_id/ext_pan_id? They have nothing to do with security, you can obtain those from every network by sniffing (without knowing the network key)

As matt said in https://github.com/Koenkk/zigbee2mqtt/issues/16188#issuecomment-1642491153 it is still something useful to change for the best "defaults" during install. I will be having my neighbor installing z2m soon and with default install we will have issues due to the same pan id and extended pan id being used correct?

**Comment by MattWestb** [comment]
@bharvey88 It can working OK then both system is up and running but most likely both system is getting problem then joining or rejoining  / jumping devices then they think its the same network but its not working then its not and having different network credentials.

**Comment by bharvey88** [comment]
> @bharvey88 It can working OK then both system is up and running but most likely both system is getting problem then joining or rejoining / jumping devices then they think its the same network but its not working then its not and having different network credentials.

yeah that is not ideal lol

**Comment by Koenkk** [comment]
Agree, @MattWestb do you know if ext_pan_id is also important for this? I would expect that just a new `pan_id` is enough.

**Comment by MattWestb** [comment]
I have red Silanbs recommendations and the CSA-ITO Zigbee base security papers and extended pan id is also needed being unique in radio range for getting association working OK but i think for normal working is the network not using it but if implanting random / unique PAN-ID make the same with the EPAN and it cant being any problems for users in the future.

**Comment by Koenkk** [comment]
Implemented in https://github.com/Koenkk/zigbee2mqtt/pull/18530 !

**Pull request merged**
