### PR TITLE
Network map

### PR DESCRIPTION
**Pull request by clockbrain**
Problem was uncontactable devices were aborting the promise.all collection of scan results. Some googling presented a solution https://stackoverflow.com/questions/48577702/setting-a-timeout-for-each-promise-within-a-promise-all

I've now tested this on my network with a disconnected router and the map is still generated.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by clockbrain** [comment]
I think I've done the rebase to dev ok. Wasn't expecting it to pick up some of your recent commits but I guess you can exclude those if they don't belong. Anyway the network scan changes are ok and I've tested them again.

**Comment by eaxeax** [comment]
bad_network
Its my map, after this pr :(

**Comment by Koenkk** [comment]
Although maybe not perfect yet, I will merge so it can easily be tested further in #652 .

P.S. Maybe it improves when increasing the timeout of `2000` to e.g. `5000`?

**Pull request merged**
