### PR TITLE
fix: Change `MQTT publish` log to `debug`

### PR DESCRIPTION
**Pull request by Koenkk**

### CODE REVIEW

**Comment by mrmaximas** [comment]
No more mqtt messages in info mode?

**Comment by Koenkk** [comment]
Indeed

**Comment by echaritos** [comment]
Does this mean that we will not be able to log info messages?

**Comment by Koenkk** [comment]
> Does this mean that we will not be able to log info messages?

**Comment by martyzeq** [comment]
sorry but this change makes me sad... Is there option to keep previous behaviour somehow ? In my case Info loglevel tells not enough and debug too much - maybe something like syslog loglevel 0-7 would help. Thank you, everything else works great for me.

**Comment by jakwarrior** [comment]
I totally agree with that, the previous system was much better to see mqtt messages through the logs page.

**Comment by echaritos** [comment]
I find the structure of the log messages now more reliable to extract information. The logs webpage does not work on my system.

**Comment by martyzeq** [comment]
I prefer to send logs to remote syslog, but there is a big gap between current Info loglevel and Debug, which I'd like to see filled. Sometimes I just need to backtrace what happened few days ago with some device, and having debug turned on permanently is sledgehammer to crack a nut ...

**Comment by Koenkk** [comment]
> sorry but this change makes me sad... Is there option to keep previous behaviour somehow ?

Could you create a feature request for this? Then we can keep track how many people are interested in this.

**Comment by theDiverDK** [comment]
I support the #22522 improved logging, so we get the info back from before ;-)

**Pull request merged**
