### PR TITLE
Openhab 2.4 compatibility #1588 

### LINKED ISSUE #1588: [homeassistant] Compatibility with OpenHab 2.4
https://github.com/Koenkk/zigbee2mqtt/blob/927c4dbc05e356ab9ebfb49a308f1c9878cd72a7/lib/extension/homeassistant.js#L781
@davidgraeff tells that this needs to be an array according to some spec.

I am trying to solve it on one or another end.
https://github.com/openhab/openhab2-addons/issues/5632#issuecomment-497492341

### PR DESCRIPTION
**Pull request by yozik04**
Resolves #1588

### CODE REVIEW

**Comment by yozik04** [comment]
Tests require fixing

**Comment by Koenkk** [comment]
How does this affect existing setups?

**Comment by yozik04** [comment]
Maybe re adding automatically discovered items... I am putting [WIP] tag. As I did not got it fully working yet.

**Comment by yozik04** [comment]
I will make it fully working with current OpenHAB implementation, and see what damage it makes to existing setups. First commit in this pull request does not break anything...

**Comment by yozik04** [comment]
I think this is all changes that are required for compatibility with openhab 2.4. I have tested on HASS and all devices continued to work without any issues.

There is more work pending on Openhab side.

**Comment by Koenkk** [comment]
I've confirmed that it has no regression with HASS. 

Once the integration with openhab is fully completed, please also update:
- https://github.com/Koenkk/zigbee2mqtt.io/blob/master/index.md#integration
- https://github.com/Koenkk/zigbee2mqtt/blob/master/README.md#integrations

Thanks!

**Comment by yozik04** [comment]
Sure. Thank you.

**Comment by matfiz** [comment]
@yozik04 do you have any suggestions on how to efficiently use zigbee2mqtt with OpenHab 2.4? Is autodiscovery possible?

**Comment by yozik04** [comment]
**From zigbee2mqtt side:** Auto discovery already works in `dev` branch.
**From Openhab side:** Improvements are in https://github.com/openhab/openhab2-addons/pull/4927 pull request, maybe this will get to Openhab 2.5.

**Comment by matfiz** [comment]
Awesome, thx for the news @yozik04!

**Pull request merged**
