### PR TITLE
Another Fork

### PR DESCRIPTION
**Pull request by oskarn97**
Hey,
we were seeing that you are also working on a fork with features, we also implemented.
If you like have a look at [my fork](https://github.com/oskarn97/xiaomi-zb2mqtt) with a different number of other features like a firmware such as an increased device limit from 20 to 48, support for battery status messages, automatic port selection, yaml config, MQTT commands and other cool stuff :)

### CODE REVIEW

**Comment by dgomes** [comment]
Hi @Koenkk!

I'm also integrating with home-assistant.io, I'm running a testing version with MQTT discovery implemented into xiaomi-zb2mqtt.

I've contributed to @oskarn97 repository since at the time I forked he had the most active fork, and since another developer has also contributed.

I'm all in for your current plan and can help out although I'm not a nodejs native programmer (more python here)

**Comment by dgomes** [comment]
We should decide wether we merge with @oskarn97 repository or start an organisation and a common repository.

**Comment by Koenkk** [comment]
I'm fine with starting an organisation. 

However I first want to complete the refactoring step because this has quite an impact on the current code (to avoid merge conflicts).

**Comment by Koenkk** [comment]
I've made quite some progress today on both the code & wiki. Todo issue: https://github.com/Koenkk/xiaomi-zb2mqtt/issues/2.

**Comment by juliojs** [comment]
Wow impressive work!
As @dgomes did, I've also contributed to @oskarn97 repository but it's good to see that the code is moving again!

I just [added](https://github.com/juliojs/xiaomi-zb2mqtt/commit/600e7e3127a10689b442b659be78845f4c23a529) an option to send remote click commands to wall switches. I would be happy to contribute and see that feature soon on a merged version! :)

**Comment by Koenkk** [comment]
@juliojs Thanks! I'm happy to merge things in. 

I'm done with refactoring the code now. 
Let's create issues for things we want to add!

**Pull request closed without merging**
