### PR TITLE
Added xiaomi cube

### PR DESCRIPTION
**Pull request by ciotlosm**
There seem to be a few problems:

- I did not return the analog value for the rotate
- I don't know what does data['65285'] mean 
- There seems to be a bug where if you rotate and then flip, for some reason you get direction attribute on flip in mqtt - probably bug with code somewhere else
- I need to identify one more conversion for status updates (probably battery) - gets received on a timer around every 30 minutes

PS: @kirovilya should be mentioned in credits for the algorithm for the cube. I took that from his file (main.js)

### CODE REVIEW

**Comment by ciotlosm** [comment]
Based on what I see in logs, this is visible also for the temperature sensor:
```
2018-5-7 22:57:20 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0001fa5c9d', payload: '{"temperature":26.86}'
2018-5-7 22:57:20 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0001fa5c9d', payload: '{"temperature":26.86,"humidity":36.63}'
2018-5-7 22:57:20 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0001fa5c9d', payload: '{"temperature":26.86,"humidity":36.63,"pressure":970}'
```

I assume the above was supposed to be individual values

**Comment by tb-killa** [comment]
Please Add the Source from your Code Blocks: 
I think a Mention would be great:
https://github.com/kirovilya/ioBroker.zigbee

**Comment by ciotlosm** [comment]
@tb-killa I just added i the original description. He should be added to contributors for the algorithm

**Comment by tb-killa** [comment]
@ciotlosm Yes i think it's absolutely fair to point to the github repo (source).

**Comment by ciotlosm** [comment]
@tb-killa in his comments and based on code he assume a level position on rotate when 500, but on testing that is not correct. I can rotate the cube on flat surface and not always get 500 back on data['65285'].

**Comment by tb-killa** [comment]
@ciotlosm Please provide some example values. Maybe we need some sort of calibration table .?

I wait for my cube, mine will arrive in a few weeks.

**Comment by tb-killa** [comment]
I found another Cube integration.
Look at this: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/cube/device.js

**Comment by ciotlosm** [comment]
Found so far:
```
{ cid: 'genBasic',
  data: 
   { '65281': 
      { '1': 3015,
        '3': 24,
        '4': 17320,
        '5': 232,
        '6': [Array],
        '10': 0,
        '151': 0,
        '152': 159,
        '153': 19,
        '154': 3 } } }
{ cid: 'genBasic',
  data: 
   { '65281': 
      { '1': 3015,
        '3': 24,
        '4': 17320,
        '5': 232,
        '6': [Array],
        '10': 0,
        '151': 0,
        '152': 159,
        '153': 19,
        '154': 3 } } }
{ cid: 'genBasic',
  data: 
   { '65281': 
      { '1': 3015,
        '3': 24,
        '4': 17320,
        '5': 232,
        '6': [Array],
        '10': 0,
        '151': 0,
        '152': 159,
        '153': 19,
        '154': 3 } } }
{ cid: 'genBasic',
  data: 
   { '65281': 
      { '1': 3015,
        '3': 25,
        '4': 17320,
        '5': 232,
        '6': [Array],
        '10': 0,
        '151': 0,
        '152': 159,
        '153': 19,
        '154': 3 } } }
```

I didn't have time to see what each means.

**Comment by Koenkk** [comment]
It support battery status: 

````
   { '65281': 
      { '1': 3015, #  = Current voltage
````

So  'MFKZQ01LM' should be added on https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/converters/zigbee2mqtt.js#L46

**Comment by ciotlosm** [comment]
Added battery support.

**Comment by ciotlosm** [comment]
@tb-killa I will leave the analog input for rotate for a different PR, just to get functionality in for basic stuff for the moment.

**Comment by Koenkk** [comment]
Ok, to clarify things, the `genMultistateInput` parser fully works and the `genAnalogInput` still needs some attention?

**Comment by ciotlosm** [comment]
Yes. genAnalogInput is also working, as you get action: rotate and direction: left or right but you don't get angle values as 3rd parameter.

**Comment by Koenkk** [comment]
`supports: 'TODO'` in `devices.js` should be:

`supports: 'shake, wakeup, fall, tap, slide, flip180, flip90, rotate_left, rotate_right'`

Then this can be merged in! :smile:

**Comment by tb-killa** [comment]
Damn:
Today i received this Email :
Thank you for contacting Gearbest about your order. 


This is an update about the following item: 183222001*1,Original Xiaomi Mi Magic Controller


We are sorry to inform you that this item is no longer available and has been discontinued. 

So sad, i need to buy this device from another distri.

**Comment by ciotlosm** [comment]
@Koenkk ready for merge I think

**Comment by Koenkk** [comment]
Yes, thanks! @ciotlosm

**Pull request merged**
