### PR TITLE
Provide options to controller

### PR DESCRIPTION
**Pull request by apiel**
Hi, would be great to be able to inject different dependency in your controller.

In my case, I would like to use zigbee2mqtt without mqtt. Right to solve this, I have to mock lib/mqtt.js but it's not optimal. In this PR I give the possibility to inject the 4 main dependencies of the controller (but actually we could give the possibility to inject even more, like extensions...)

### CODE REVIEW

**Comment by Koenkk** [comment]
Loading additional extensions is already possible with: https://github.com/Koenkk/zigbee2mqtt/issues/3297. 

What is your use case for this? As I feel both disabling MQTT and using `controller.js` as an API are not in scope of the zigbee2mqtt project.

**Comment by apiel** [comment]
Your zigbee interface is very nice, but in my case I don't want to use MQTT. I just want to call directly zigbee from your controller. Right now, I have to do very hacky thing to use your middleware without MQTT:

```js
const mock = require('mock-require');
const { join } = require('path');
const events = require('events');

const devices = require('./devices');
const { action } = require('./action');
const { emitter } = require('./emitter');

process.env.ZIGBEE2MQTT_DATA = join(__dirname, 'data');

const addresses = Object.values(devices).map((device) => device.addr);

class MQTT extends events.EventEmitter {
    constructor() {
        super();
    }
    on(name, value) {
        console.log('on', { name, value });
    }
    async connect() {}
    async disconnect() {}
    async publish(topic, payload, ...rest) {
        if (addresses.includes(topic)) {
            action(topic, JSON.parse(payload));
        } else {
            console.log('pub', { topic, payload, rest });
        }
    }
    subscribe(topic) {
        // console.log('sub', topic);
    }
    isConnected() {
        return true;
    }
    onMessage(topic, message) {
        console.log('onMessage', { topic, message });
    }
}
mock('zigbee2mqtt/lib/mqtt', MQTT);

// must stay after mock
const Controller = require('zigbee2mqtt/lib/controller');
const controller = new Controller();
controller.start();

emitter.on('message', (data) => {
    console.log('on emitter message', data, this.emit);
    controller.onMQTTMessage(data);
});

```

**Comment by Koenkk** [comment]
I understand, but making such modifications for non supported use cases doesn't feel right.

Reading the code, I think it's already possible to achieve what you want with:

```
let controller = new Controller();
controller.mqtt = MY_MOCK_MQTT
```

**Comment by apiel** [comment]
No it doesn't feel right at all :-/

I already tried `controller.mqtt = MY_MOCK_MQTT` but doesn't work because of the extensions.

**Comment by Koenkk** [comment]
> but doesn't work because of the extensions

What fails?

**Comment by apiel** [comment]
image

**Comment by Koenkk** [comment]
Can you check if overriding the functions work? e.g.

```js
let controller = new Controller();
controller.mqtt.subscribe =() => {}
```

If that doesn't work replacing the `mqtt.js` file is the only option.

I'll close this PR for the reason mentioned in https://github.com/Koenkk/zigbee2mqtt/pull/3843#issuecomment-653669674, hopefully the above helps.

**Comment by apiel** [comment]
Or you could let us doing dependencies injection on the controller. Actually the best would be that you extract your zigbee controller inside a separate library so people could use it without mqtt. For example some people (like me) would like to use rest or graphql.

**Comment by Koenkk** [comment]
I don't have any plans to do this, actually most of this is already in zigbee-herdsman which is meant to be used as a library.

**Pull request closed without merging**
