### PR TITLE
Fix loading external converters

### PR DESCRIPTION
**Pull request by nurikk**
This fixes Error: Cannot find module 'zigbee-herdsman-converters'
Caused by requiring converter from folder which is located outside z2m sources folder (ZIGBEE2MQTT_DATA)

### CODE REVIEW

**Comment by nurikk** [comment]
FYI @ciotlosm

**Comment by ciotlosm** [comment]
@nurikk anything special that I should add to the add-on? The previous suggested fix worked when tested.

**Comment by nurikk** [comment]
> @nurikk anything special that I should add to the add-on? The previous suggested fix worked when tested.

No, now everything should work out of the box. Can you please verify?

**Comment by ciotlosm** [comment]
@nurikk Seems this was tested on the version of the add-on without the env variable and now it works out of the box 🎉

**Pull request merged**
