### PR TITLE
Added pictures for _TZE204_ncti2pro (ZSVIOT PN6)

### PR DESCRIPTION
**Pull request by vitkuzmenko**
Pull request for supporting device:

https://github.com/Koenkk/zigbee-herdsman-converters/pull/7840

### CODE REVIEW

**Comment by Koenkk** [comment]
Please remove the `.jpg` and rename to png to `PN6.png`

**Comment by vitkuzmenko** [comment]
> Please remove the `.jpg` and rename to png to `PN6.png`

Done.

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
I just noticed this PR was done against the wrong repo, could you make it against https://github.com/Koenkk/zigbee2mqtt.io/

**Pull request merged**
