### PR TITLE
Change zigbee2mqtt logger output format

### PR DESCRIPTION
**Pull request by tb-killa**
Bring zigbee2mqtt logger output confirm to zigbee-shepherd debug output.

image

### CODE REVIEW

**Comment by Koenkk** [comment]
Great!

I think we can leave out the `-->`, for zigbee-shepherd it adds value (indicating an incoming or outgoing request), but for zigbee2mqtt it doens't.

**Comment by tb-killa** [comment]
I bring it in for optic ;)
What im also thinking about is giving user Option via settings file to show or hide the date stamp.

I will remove like you mentioned the ``-->`` as you wish.

BTW do you know how we could bold the Text on start?

**Comment by Koenkk** [comment]
Winston 3.0 seems to contain some formatting options: https://github.com/winstonjs/winston#creating-custom-formats but this seems to apply for different log levels only.

**Comment by tb-killa** [comment]
Okay thanks. i would say .. lets merge ;)

**Pull request merged**
