### PR TITLE
colors for network map

### PR DESCRIPTION
**Pull request by andreasbrett**
I added some colors to the nodes and edges to make the map even clearer. I also added a node containing the creation timestamp. Not sure if this is okay with you but I thought it would be good to know what point in time the map pictures.

Colors can be re-defined in `configuration.yaml`.

NOTE: I removed the `textRoutes` labels from a previous commit by @clockbrain as they were somehow crashing my zigbee2mqtt instance. I haven't had the time to investigate why this happened.

### CODE REVIEW

**Comment by Koenkk** [comment]
Let's fix the textRoute part first, what errors/crashes do you see? (logs please).

**Comment by andreasbrett** [comment]
> Let's fix the textRoute part first, what errors/crashes do you see? (logs please).

I'd love to help with something meaningful but logs did not show a lot of useful info (at least to me). Not even in debug mode. In order to find the causing line I had to test manually by commenting out lines and without the textRoute line it worked right away.

Those are the last lines right before zigbee2mqtt restarted itself and created a new log file (of course without resuming the network scan): https://pastebin.com/7vT0EjrN

Checking further it is not **lib/zigbee.js** and the **networkScan** method that caused the crash but rather the call to `e.routes.map((r) => ...` within **lib/extension/networkMap.js**. If I removed that line from networkMap.js the log would show exactly the same but with a mqtt publish of the network map (digraph....): https://pastebin.com/5vc3z9rR

Those errors with rtg scans are on either one or both of my OSRAM Smart+ plugs. In my first example the rtg errors were with both of them. In the second example it's only one of them.

**Comment by clockbrain** [comment]
If you start z2m manually with npm start then you may see additional error messages from a crash that don't show in the log files.

I've just tried a blend of your code and the text routes bit and this works fine here:
```
                const lineStyle = (device.type=='EndDevice') ? 'style="dashed", '
                    : (!e.routes.length) ? 'style="dotted", ' : '';
                const lineWeight = (!e.routes.length) ? `weight=0, color="${rInactiveColor}", `
                    : `weight=1, color="${rActiveColor}", `;
                const textRoutes = e.routes.map((r) => `0x${r.toString(16)}`);
                const lineLabels = `label="${e.lqi}\\n[${textRoutes.join(']\\n[')}]"`;
                text += `  "${e.parent}" -> "${device.ieeeAddr}" [${lineStyle}${lineWeight}${lineLabels}]\n`;
```
Note that the order of line arrow changed to parent->device so the routes make sense.

Also, I don't think you need the timestamp node as the last_seen timestamp on the coordinator (now) shows when the map was created.

Good work though - colored map looks good.

**Comment by andreasbrett** [comment]
I don't know why but now it worked with those blended lines of code.

**Comment by Koenkk** [comment]
I've refactored the code a little bit, @andreasbrett can you verify it is still working? Then it's ready to merge.

**Comment by andreasbrett** [comment]
> I've refactored the code a little bit, @andreasbrett can you verify it is still working? Then it's ready to merge.

Can confirm it's still working nicely.

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
