### PR TITLE
mqtt listener to rename last paired device.

### PR DESCRIPTION
**Pull request by dusanmsk**
Allow to rename last paired device without knowledge of its original name.

Send zigbee2mqtt/bridge/config/rename_last with payload containing new name and last paired device will be renamed.

### CODE REVIEW

**Comment by dusanmsk** [comment]
Could you please review this and if interested create test for that? My JS knowledge is poor so I am afraid I am not able to complete this PR 100%.

Thx

**Comment by Koenkk** [comment]
What would be the use case of this? You can easily grab the last paired device via the log zigbee2mqtt topic.

**Comment by Kryzek** [comment]
If I'd rename devices on Z2M side I would like using generic command without a need to know device ID to get item renamed. I can see use for this quality-of-life-feature.

**Comment by dusanmsk** [comment]
My usecase - i have mqtt app on android phone. I click on 'pairing' button, it sends permit_join true. Now I press button on zigbee device (for example temperature sensor which i am gooing to put to livingroom) and pair. I dont wanna to check logs or something else because 1. i dont care and 2. have no access to the rpi where bridge is installed. I know that what i paired previously was 'livingroom/temperature'. So i use android app again to send new name with one click without parsing logs/mqtt messages and copying/pasting device id.

**Comment by Koenkk** [comment]
I see, thanks!

**Pull request merged**
