### PR TITLE
#3352 Apply brightness_percent before others

### PR DESCRIPTION
**Pull request by sjorge**
As mentioned, simply adding brightness_percent seems to fix the problem.

I'll look into doing the reverse if the state is off when I have more time.

### CODE REVIEW

**Comment by sjorge** [comment]
@Koenkk I also found a way to apply the color(_temp) before turning off the bulb, which is nice... but I find the solution kind of ugly.

I moved the isOn const out of the homeassistant block and added this below the current sort.

```
        // execute color and color_temp changes first if bulb is on
        if (isOn) entries.sort((a, b) => (['color', 'color_temp'].includes(a[0]) ? -1 : 1));
```

With this extra stuff in place the behavior is now:

1. state and brightness* are moved to head of Array
2. if the bulb is on (and can take color changes) move color & color_temp to head of queue

This results in sending `{"state": "off", "color": "#FF0000"}` to apply the color first. If I then use a remote to turn on the bulb, it turns on red as expected. But this is rather short sighted I guess.

I wasn't able to figure out how to do:
- bulb is on
  - do everything except brightness* and state, then do brightness, then do state
- bulb is off
  - do brightness* and state, then do everything else

better yet is to only move brightness/state to the end of the list when the bulb is on, if the new state/brightness would turn off the bulb, but that got complex rather quick.

I guess the simple fix in this PR will have to do.

**Comment by Koenkk** [comment]
Thanks

Regarding the order of state and brightness, this doesn't matter for bulbs as they are handled by the same converter and a converter will never be used twice. So it doesn't matter which attribute triggers it. (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L331)

> I also found a way to apply the color(_temp) before turning off the bulb, which is nice... but I find the solution kind of ugly.

What functional issues does this currently have?

**Comment by sjorge** [comment]
> Regarding the order of state and brightness, this doesn't matter for bulbs as they are handled by the same converter and a converter will never be used twice. So it doesn't matter which attribute triggers it. (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L331)

Ah good to know!

> What functional issues does this currently have?
Mostly inconsistencies between bulbs that report and those that don't (e.g. trådfri vs hue vs innr).

I set off + color=red om both
- hue: off + color=red published over mqtt
- trådfri: off + color=red published over mqtt, after attReport the same payload get published again (reports both on/off and color)
- innr: off + color=red published, attReport happens off + color=previous color published

If I then turn them on using a bound remote:
- hue: on with old color (no updated message via mqtt, so it still 'red')
- trådfri: on with red color (update from attReport with state=on)
- innr: on with old color (update from attReport with state=on)

However if with some fiddling we apply color before we apply state/brightness... all bulbs behave the same.

Both trådfri and innr publish an attReport with state and color (red), both turn on with red color.
Hue doesn't report anything ofcourse, but it does turn on with color red!

**Comment by Koenkk** [comment]
That's a valid use case indeed, could you make another pr?

**Comment by sjorge** [comment]
Yeah, I had a slightly better idea while taking my daily look.
I'll do another PR today or tomorrow

**Pull request merged**
