### PR TITLE
Add possibility to override execution command at runtime

### PR DESCRIPTION
**Pull request by bg-master**
The possibility to override execution command is really usefull durig dev, the entrypoint script initialize container data at runtime and then CMD defines the default executable that can be overridden at runtime.

### CODE REVIEW

**Comment by bg-master** [comment]
I reproduced the behaviour described in #3367 in case of missing execution permission on entrypoint script, so to prevent errors added the setting during building. Tested the PR with portainer 1.24.0 works as expected.
I think is useful the possibility to override the execution command, for example with an interactive shell, to make live settings and testing them without the need of restart the container.

**Comment by Koenkk** [comment]
Thanks for checking this!

**Comment by qm3ster** [comment]
@bg-master what prevents you from using `--entrypoint` argument of docker run?
You can just `--entrypoint=/bin/sh` and then run `npm start&` or `docker/run.sh&` inside whenever you need?

Do you currently have a usecase that is not covered by any of the following?
- `docker run --entrypoint=/bin/sh koenkk/zigbee2mqtt`
- `docker start -ai z2m`
- `docker exec z2m sh`

**Comment by bg-master** [comment]
Of course, your solutions do the job. The choice is largely an artistic one but the entrypoint/cmd pattern with the last one as default overridable, looks supported by the [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) and also most diffused.

**Pull request merged**
