### PR TITLE
Configuration: Option to retain every device globally

### PR DESCRIPTION
**Pull request by tuga49**
Hi. Actually we have an option to retain MQTT messages of devices (default false), however, it need to be done one by one. What about add a new option to be possible retain: true by default for every device, instead of add retain: true in every device, one by one. And for example, if we have 30 devices, and wan't 28 of them retain: true, write this retain: true globally to be the default, and in the other 2 devices, write retain: false inside the device, to override the default one.

Thank's

### CODE REVIEW

**Comment by Koenkk** [comment]
I expect this can already be done with: https://www.zigbee2mqtt.io/information/configuration.html#changing-device-type-specific-defaults

**Comment by tuga49** [comment]
> I expect this can already be done with: https://www.zigbee2mqtt.io/information/configuration.html#changing-device-type-specific-defaults

I've seen that but I can't understant. Can you send me an example of retain: true by default to every device? For what I've seen, it is to be used inside every device. Thank's

**Comment by Koenkk** [comment]
Add this to your configuration.yaml

```yaml
device_options:
  retain: true
```

**Comment by tuga49** [comment]
> Add this to your configuration.yaml
> 
> ```yaml
> device_options:
>   retain: true
> ```

oh damn. I did early this:
```
devices:
  retain: true
```
but the correct way is:
```
device_options:
  retain: true
```
thank's bro ;) have a good day!

**Pull request closed without merging**
