### PR TITLE
Add device availability functionality for HASS based on router devices ping and attribute reporting also available on battery-powered devices

### PR DESCRIPTION
**Pull request by ugrug**
- Router devices ping available by set in `configuration.yaml: advanced/availability_interval`
- Additionally availablitiy of battery-powered devices with attribute reporting possible by listening for incoming messages. For these devices report interval can be set in `configuration.yaml: devices/device_ID/attribute_report_interval`
- For working ping functionality fixing the callback of the `zigbee-stephard/Controller.prototype.checkOnline` function needed. Related to this, created a pull request for it. For testing, available at: https://github.com/Koenkk/zigbee-shepherd/pull/8

### CODE REVIEW

**Comment by Koenkk** [comment]
Great, could you open the zigbee-shepherd PR here? https://github.com/koenkk/zigbee-shepherd

**Comment by ugrug** [comment]
PR moved to https://github.com/Koenkk/zigbee-shepherd/pull/8

**Comment by ugrug** [comment]
It is great you merged this feature! 👍 
One question related this: As I see you dropped the availability for non-router devices based per device value can be set based on attribute reporting interval (`configuration.yaml: devices/device_ID/attribute_report_interval`). Do you have better idea to handle this?

**Comment by Koenkk** [comment]
@ugrug we dont need the last seen attribute, I prefer to just keep track of this by handling zigbee messages in the handleZigbeeMessage function. Lets keep extensions as standalone as possible.

I`m still struggeling with the availabillity of battery based devices as we dont really know how often a sensor could report. A good guess would be 1 day, however this is probably not alwys right, perhaps there should be some devive specific option to disable it for that device.

**Comment by waiweng83** [comment]
Hi, I'm new to zigbee2mqtt and i find that the availabillity of battery based devices is pretty important especially for some sensors like smoke alarm, water leakage sensor, etc.

I know that different devices will have different report/heartbeat interval. Like @Koenkk just commented, perhaps just make it configurable for each device? Any plan to include this feature? If not, what is the best way to monitor this in home assistant?

Sorry for commenting on the Closed thread. I'm not sure whether this is the correct way to do it.

**Comment by Koenkk** [comment]
@waiweng83 the correct place is #775

**Comment by waiweng83** [comment]
Thanks

**Pull request merged**
