### PR TITLE
Mention the hassio addon

### PR DESCRIPTION
**Pull request by keesschollaart81**
I did not know about the hassio addon for this project and it's not mention anywhere other than in a closed issue so I thought it made sense to reference it here.

### CODE REVIEW

**Comment by dgomes** [comment]
Hmm I think the right place is the Wiki, and given the importance of this matter to many users, add it to the README

**Comment by Koenkk** [comment]
Thanks!

**Comment by ciotlosm** [comment]
@Koenkk maybe as @dgomes would be good to add "Popular integrations" to the Readme.md

**Comment by Koenkk** [comment]
@ciotlosm I'm fine with that, mind opening a PR?

**Comment by ciotlosm** [comment]
Will do that later today

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
Added https://github.com/Koenkk/zigbee2mqtt/pull/91

**Pull request merged**
