### PR TITLE
[RFC] RISC-V support

### PR DESCRIPTION
**Pull request by stintel**
This PR updates the Alpine base container to Alpine 3.20, which supports the RISC-V architecture, and enables 64-bit RISC-V builds in Github actions.

I understand this probably won't be merged soon, due to the Alpine bump and the potential for regressions, but like this people who have RISC-V hardware lying around, can give it a try. I'm personally running a locally built zigbee2mqtt container on the [VisionFive 2](https://www.starfivetech.com/en/site/boards) for the past week and it's been working rather well.

### CODE REVIEW

**Comment by Koenkk** [comment]
Does it also work with Alpine 3.18? We currently cannot migrate to 3.20 since this makes the Docker build hang.

**Comment by stintel** [comment]
> Does it also work with Alpine 3.18? 

It does not, Alpine 3.20 is the first version that supports the RISC-V architecture.

**Comment by Koenkk** [comment]
Then I will hold this until the bug in Node 20 is fixed (Alpine 3.18 is the last to use Node 18 which doesnt have this bug)

**Comment by stintel** [comment]
Understood! Out of curiosity, is there any issue for that bug in Node 20?

**Comment by Koenkk** [comment]
Ci succeeds because it doesnt build the container (which is what fails for armv7 and 6 platforms on node 20)

**Comment by Nerivec** [comment]
`serialport` currently does not provide support or prebuilds for riscv64.
https://serialport.io/docs/guide-platform-support#supported-platforms-and-architectures

**Comment by stintel** [comment]
@Koenkk had to add `adapter: zstack` to configuration.yaml but seems to be working fine now. This is awesome, thank you!

**Pull request merged**
