### PR TITLE
Added some endpoint names 

### PR DESCRIPTION
**Pull request by xyzroe**
added endpointNames wifi, ds, bme
wifi for future devices
ds and bme are using in DIYRuZ_Flower

### CODE REVIEW

**Comment by Koenkk** [comment]
I don't think this is needed yet, AFAIK only required when controlling is needed.

**Comment by xyzroe** [comment]
Indeed, they are only needed for controlling. I was inattentive.
I am making a converter for a device in which there are two communication modules (wifi and zigbee), so is it possible to add an endpoint 'wifi' for it so it would be possible to turn on / off the wifi module?

**Comment by Koenkk** [comment]
Could you provide some more details about this wifi devices, do you also have an external converter config prepared already?

**Comment by xyzroe** [comment]
https://sprut.ai/client/companies/default/50 (sorry but only in Russian yet)
We are testing converter right now. 
[Drivent.js.txt](https://github.com/Koenkk/zigbee2mqtt/files/6329796/Drivent.js.txt)
Wifi control use third endpoint with onOff cluster and onOff attribute. 
At this moment there is exposes 'wifi' with endpoint 3, but we want to make 'state' with endpoint 'wifi'.

**Comment by Koenkk** [comment]
I don't see wifi used as and endpoint here, are you sure it's really needed to add this?

**Comment by xyzroe** [comment]
Yesterday I sent a converter in which endpoint 3 is marked with a number. We are using it now.

But we want to define the 3rd endpoint with the word 'wifi'. 
Then the converter will look something like this [Drivent.new.js.txt](https://github.com/Koenkk/zigbee2mqtt/files/6331920/Drivent.new.js.txt)

**Comment by Koenkk** [comment]
Ok, added the wifi one.

**Comment by xyzroe** [comment]
thanks

**Pull request merged**
