### PR TITLE
Async expose

### PR DESCRIPTION
**Pull request by vk496**
Hello,

Following the features of https://github.com/Koenkk/zigbee2mqtt/pull/10132, one of the things I need is able to read cluster/attributes at the very first stage, during the expose step.

There is a vendor specific attribute that give me the information of the operating mode of the device. And with that configuration, I can expose the correct labels to the end user.

However, it seems to me that reading from `exposes` directly doesn't work for some reason. Maybe I missing something...

### CODE REVIEW

**Comment by vk496** [comment]
Btw, I require to use `options` inside configure() anyway.

The integration has automatic detection, but it allows to the user override it with custom settings. Since attributes are exposed dynamically and can be overrided, that must be in `configure()` too in order to suscribe just for the attributes that are really needed

**Comment by Koenkk** [comment]
> one of the things I need is able to read cluster/attributes at the very first stage, during the expose step.

Can this be done in the `configure()` and later act on this based on the `exposes`? Example how to retrieve a cluster attribute value after it has been read: https://github.com/Koenkk/zigbee-herdsman-converters/blob/8273a7663568790b6e39d53cceb126b655987354/converters/fromZigbee.js#L407

**Comment by vk496** [comment]
Hi,

Sorry for not clarifying it. The `exposes` steps occurs before `configure`, which propagate the attributes to mqtt. I'm not sure if is ok to propagate them when they really should not be used.

Moreover, the `exposes` is consumed in other parts of the code (like for HA stuff), so I think is very important to maintain the consistency no matter from where the list of attributes are requested

**Comment by sjorge** [comment]
Perhaps the `exposes` step should not be called for devices that have not been fully interviewed and have not had `configure` run yet? If that is enforced you can be sure configure has happened by the time exposes is called.

**Comment by vk496** [comment]
> Perhaps the `exposes` step should not be called for devices that have not been fully interviewed and have not had `configure` run yet? If that is enforced you can be sure configure has happened by the time exposes is called.

That may not work some times. Specifically, when `configure` failed (for example, when not all reportings was configured because the device is sleeping or something else). If configure step was done partially (just half of reportings were configured), right now the device can work.

But I don't know so much of Z2M architecture, so maybe I'm wrong...

**Comment by sjorge** [comment]
Unless I am mistake the failed configure will be imediatly retried next time the device is seen, so I think that would still work out.

It’s probably also a safe assumption that a device should be successfully configure before it is considered ‘ready for use’.

**Comment by Koenkk** [comment]
The problem that I'm having with the async expose it that it can potentially block z2m. 
- `expose()` could potentially be called many times, so every time a read will be done = overkill
- external requests can time out (mostly after 10 seconds), this will create a huge delay

**Comment by vk496** [comment]
There is a sync call for read a attribute? At least with a timeout, that would be enough for my case

**Comment by Koenkk** [comment]
> There is a sync call for read a attribute? At least with a timeout, that would be enough for my case

I mean that we shouldn't make external requests in expose. Imagine a situation where you have 20 devices paired which all do a read requests in the `expose()` (which can be called many times), this would create huge delays.

**Comment by vk496** [comment]
ah, ok. Catched. 

In my side I limit that request to just when no attribute is available. But is sure that it will be a possible scenario in the future. I will think/test other ways. Thnks

**Comment by vk496** [comment]
At least, I would need expose options (optional) in `configure`, so no reporting is configured for not used attributes (user specific config overrides the automatic detection)

https://github.com/Koenkk/zigbee2mqtt/pull/10791

**Pull request closed without merging**
