### PR TITLE
Support hard reset ZNP

### PR DESCRIPTION
**Pull request by dzungpv**

### CODE REVIEW

**Comment by dzungpv** [comment]
@Koenkk Relate to this PR https://github.com/Koenkk/zigbee2mqtt/pull/1890 , you add it to zigbee-herdsman lib but not here.

**Comment by Koenkk** [comment]
Yes I still need to check this, but after the hard reset, does zigbee2mqtt restart? I think currently it will require a manual restart after this, so that should still be fixed.

**Comment by dzungpv** [comment]
We have any command to re11start the software?

**Comment by Koenkk** [comment]
No, but before this zigbee.stop() and after reset zigbee.start() should be called

**Comment by dzungpv** [comment]
Yes, you can improve my code, and i don't know why all test passed but it still show build error.

**Comment by Koenkk** [comment]
i will look into it after my holiday 🎅

**Pull request closed without merging**
