### PR TITLE
A few small fixes to permit zigbee2mqtt to be installed as a module

### PR DESCRIPTION
**Pull request by MatAtBread**
Tested with node v16.17.1

### CODE REVIEW

**Comment by Koenkk** [comment]
> to be installed as a module

Can you give some more context?

**Comment by MatAtBread** [comment]
Sure. What would you like to know?

The `require.resolve` call correctly locates the dependency target than assuming it's directly underneath zigbee2mqtt.

The test for `require.module` in the main index.js means another module/app can `npm I zigbee2mqtt` and then `start()` the whole module under the control of the other app, rather than just building/starting on the first reference.

The `export Controller` similarly permits TS to safely reference the type from the including app.

The overall context is that I'm working on an app that integrates zigbee2mqtt together with aedes and an alternative frontend so it can be quickly and easily installed in a single command, and remotely updated.

None of the changes should have any effect on current usage

**Comment by Koenkk** [comment]
Thanks, checked locally and still works 😄

**Comment by MatAtBread** [comment]
Thanks 👍

**Comment by mweinelt** [comment]
Running `node ./cli.js` now simply returns on 1.28.1. In wonder if this is a regression from this change, given that `cli.js` is the main module in that case and it isn't doing anything else.

**Comment by MatAtBread** [comment]
@mweinelt - yep, that'll break. I didn't know about that script and it passed the tests.

It's a hack, but this reverses the behaviour.

[index.js:128](https://github.com/Koenkk/zigbee2mqtt/blob/master/index.js#L123)
```
- if (require.main === module) {
+ if (require.main === module || require.main.filename.endsWith(path.sep + 'cli.js')) {
```

I'd generate a PR, but my code base has deviated quite a way away from this repo.

**Comment by mweinelt** [comment]
Noticed via https://github.com/Koenkk/zigbee2mqtt/blob/master/package.json#L105.

**Comment by MatAtBread** [comment]
A very fair observation, tho I made the changes so I could import and drive it from another script, hence I never ran the cli.

**Comment by Koenkk** [comment]
Pushed the fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Cyberbeni** [comment]
This was also an issue when installing with the following command:
```
sudo npm install --location=global zigbee2mqtt@latest
```
And then running:
```
zigbee2mqtt start
```

If I install from dev with the following command:
```
sudo npm install --location=global https://github.com/Koenkk/zigbee2mqtt/tarball/dev
```
then trying to start it, I get an error that tsc is not available, so I assume that fix will work for this method too.

**Pull request merged**
