### PR TITLE
Reduce the verbosity of MQTT publish logs

### PR DESCRIPTION
**Pull request by joshuaspence**
MQTT publish logs are very noisy. For my installation, over 99% of log entries are from this.

### CODE REVIEW

**Comment by Koenkk** [comment]
I'm not sure if this should be debug logging, it is very handy to see what is publised to MQTT

**Comment by joshuaspence** [comment]
Thanks for the pointer @sjorge, I realized that I hadn't described the problem I am trying to solve and you led me to a better solution which I will push up shortly.

So the problem is that really I only want to see warning and error logs but I changed my log level to info because I wanted to see the device pairing and OTA update progress notifications in the frontend. So probably a better solution would be to ensure that these log messages are written to MQTT even if the file/console/syslog log level is warning or error.

**Comment by Koenkk** [comment]
Since the frontend log level is now always set to `info`, `debug` messages don't appear there anymore:

Screenshot 2022-01-29 at 10 16 19


Also involving @pypb  here because of https://github.com/Koenkk/zigbee2mqtt/issues/11050. 

The reason why, in my opinion, MQTT publish should be `info` is because it is extremely helpful once you get started with z2m to see what is published (since the default log level is also `info`). I'm convinced that if the MQTT publishes are logged as debug many users can get confused since it might appear that Z2M isn't doing anything. However I also recognise that once you have a stable system, you might not be interested in this logging anymore (but are info the other info messages) so this logging gets spammy.

I see 2 possible solutions for this:
1. Add a dedicated option to log MQTT publishes as debug instead of info
2. Add a new log level (`info_minimal` ?) which logs everything except the MQTT publish messages

Option 1 might look the best for now, option 2 allows for more extension in the future

**Comment by pypb** [comment]
> I see 2 possible solutions for this:
> 
> 1. Add a dedicated option to log MQTT publishes as debug instead of info
> 2. Add a new log level (`info_minimal` ?) which logs everything except the MQTT publish messages

I like option 2, like you said it may give you some more flexibility in the future. But instead of calling it `info_minimal`, you could go for something similar to the syslog levels which has `notice` as a level between `warning` and `info`. That would, of course, involve changing the log level of everything currently at level `info`, except for the MQTT publishes.

**Comment by Gimlir** [comment]
+1 vote for option 2. Something like info_minimal is exactly what i also wanted to ask

**Comment by joshuaspence** [comment]
> However I also recognise that once you have a stable system, you might not be interested in this logging anymore (but are info the other info messages) so this logging gets spammy

Drop MQTT publish messages to debug but also change the default log level to debug?

**Comment by joshuaspence** [comment]
Good point. My preference would be https://github.com/Koenkk/zigbee2mqtt/pull/10922#issuecomment-1024918557 then. It looks like Winston supports the `notice` log level already.

**Comment by joshuaspence** [comment]
@Koenkk How did you want to proceed?

**Pull request closed without merging**
