### PR TITLE
Add autodiscovery support for Sylvania MR16

### PR DESCRIPTION
**Pull request by philhawthorne**
Adds auto discovery support for the MR16 smart bulbs from
Osram/Sylvania.

### CODE REVIEW

**Comment by philhawthorne** [comment]
These are working in my setup, however they're rather buggy.

Sometimes the lights don't turn on/off, with zigbee2mqtt complaining the bulb is offline.

```
zigbee2mqtt:error 2018-10-1 12:03:17 Zigbee publish to '0xf0d1b800000097b3', genLevelCtrl - moveToLevel - {"level":229,"transtime":0} - null failed with error Error: AF data request fails, status code: 233. MAC no ack.
zigbee2mqtt:error 2018-10-1 12:05:47 Zigbee publish to '0xf0d1b80000009723', genOnOff - off - {} - null failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.
```

Sometimes, there's a whole bunch of errors about changing the color temp

```
zigbee2mqtt:error 2018-10-1 12:03:17 Zigbee publish to '0xf0d1b800000097be', lightingColorCtrl - moveToColorTemp - {"colortemp":500,"transtime":0} - null failed with error Error: rsp error: 17
```

I'm not sure if there's another converter I should be using in Koenkk/zigbee-shepherd-converters#94 ?

**Comment by Koenkk** [comment]
Thanks for the pr.

No ack means that the connection between the bulb and the zigbee network is bad. Try improving your network by placing routers.

**Comment by philhawthorne** [comment]
Thanks @Koenkk 

I have two ZNCZ02LM plugged in at opposite ends of the house (with the controller in the middle), and around 20 of these MR16 bulbs (which should also be routers, right?). Also 6 or so Hue bulbs around the house, which should also be routers.

I'm guessing for whatever reason, everything is connecting straight to the controller instead of meshing around each router. The Xiaomi and Hue devices work great. Just these bulbs that seem to struggle.

These bulbs were a bit of a PITA even with the official Lightify gateway, but slightly more reliable. Might have to go back to that gateway for these bulbs. Was hoping a "super" zigbee network combining Xiaomi, Hue and Lightify would mean no drop outs :(

Could the no-routing through routers be related to Koenkk/zigbee2mqtt#331 ?

**Comment by Koenkk** [comment]
Could you post your zigbee network map: https://github.com/Koenkk/zigbee2mqtt/issues/252 ?

**Comment by philhawthorne** [comment]
I've done it with the Native zigbee2mqtt graphviz approach, if thats the same?

```
digraph G {
  "0x00158d0002365b11" [label="helen_electric_blanket (0x00158d0002365b11 - online)"];
  "0x00158d0002365b11" -> "0x00124b0014d9e3a4" [label="19"]
  "0x001788010361e509" [label="Sconce Left (0x001788010361e509 - offline)"];
  "0x001788010361e509" -> "0x00124b0014d9e3a4" [label="42"]
  "0xf0d1b8000000978a" [label="Bathroom South (0xf0d1b8000000978a - online)"];
  "0xf0d1b8000000978a" -> "0x00124b0014d9e3a4" [label="12"]
  "0xf0d1b80000009809" [label="Hall North (0xf0d1b80000009809 - offline)"];
  "0xf0d1b80000009809" -> "0x00124b0014d9e3a4" [label="18"]
  "0xf0d1b80000009792" [label="Ensuite Sink (0xf0d1b80000009792 - offline)"];
  "0xf0d1b80000009792" -> "0x00124b0014d9e3a4" [label="0"]
  "0xf0d1b800000097b3" [label="Kitchen Front (0xf0d1b800000097b3 - offline)"];
  "0xf0d1b800000097b3" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b800000097b9" [label="Kitchen Center (0xf0d1b800000097b9 - offline)"];
  "0xf0d1b800000097b9" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b800000096ec" [label="Kitchen Sink South (0xf0d1b800000096ec - offline)"];
  "0xf0d1b800000096ec" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b800000097be" [label="Kitchen South (0xf0d1b800000097be - offline)"];
  "0xf0d1b800000097be" -> "0x00124b0014d9e3a4" [label="1"]
  "0x00158d0002366cc0" [label="Wax Warmer (0x00158d0002366cc0 - online)"];
  "0x00158d0002366cc0" -> "0x00124b0014d9e3a4" [label="42"]
  "0x8418260000004466" [label="Patio Light (0x8418260000004466 - offline)"];
  "0x8418260000004466" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b8000000984d" [label="Living Back Left (0xf0d1b8000000984d - offline)"];
  "0xf0d1b8000000984d" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b80000009723" [label="Kitchen Sink North (0xf0d1b80000009723 - offline)"];
  "0xf0d1b80000009723" -> "0x00124b0014d9e3a4" [label="1"]
  "0x0017880102e05fa5" [label="Wardrobe Light (0x0017880102e05fa5 - online)"];
  "0x0017880102e05fa5" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b80000009f56" [label="Living Front Right (0xf0d1b80000009f56 - online)"];
  "0xf0d1b80000009f56" -> "0x00124b0014d9e3a4" [label="19"]
  "0xf0d1b80000009d94" [label="Bathroom North (0xf0d1b80000009d94 - online)"];
  "0xf0d1b80000009d94" -> "0x00124b0014d9e3a4" [label="67"]
  "0x0017880100ecee59" [label="Living Room Lamp Top (0x0017880100ecee59 - online)"];
  "0x0017880100ecee59" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b80000009d3f" [label="Entry (0xf0d1b80000009d3f - offline)"];
  "0xf0d1b80000009d3f" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b8000000976b" [label="Hall South (0xf0d1b8000000976b - offline)"];
  "0xf0d1b8000000976b" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b80000009f49" [label="Hall Center (0xf0d1b80000009f49 - offline)"];
  "0xf0d1b80000009f49" -> "0x00124b0014d9e3a4" [label="1"]
  "0xf0d1b800000097e9" [label="Living Back Right (0xf0d1b800000097e9 - online)"];
  "0xf0d1b800000097e9" -> "0x00124b0014d9e3a4" [label="13"]
  "0xf0d1b800000096eb" [label="Office North (0xf0d1b800000096eb - offline)"];
  "0xf0d1b800000096eb" -> "0x00124b0014d9e3a4" [label="1"]
  "0x0017880110460d3f" [label="Living Room Lamp Bottom (0x0017880110460d3f - online)"];
  "0x0017880110460d3f" -> "0x00124b0014d9e3a4" [label="1"]
  "0x0017880103407970" [label="Sconce Right (0x0017880103407970 - offline)"];
  "0x0017880103407970" -> "0x00124b0014d9e3a4" [label="84"]
  "0x0017880100bfbb52" [label="Study Lamp (0x0017880100bfbb52 - offline)"];
  "0x0017880100bfbb52" -> "0x00124b0014d9e3a4" [label="1"]
}
```

It doesn't look like any battery devices are reported in this layout. They may not have woken up or something for them to be reported yet.

**Comment by Koenkk** [comment]
Looks that they are offline, could you try repairing the device (without moving it to a different place)?

**Comment by philhawthorne** [comment]
Hmm, unfortunately that didn't work either. Some of them were able to pair, but only the ones that could connect to the controller.

**Pull request merged**
