### PR TITLE
Iterate objects recursively and support array output

### PR DESCRIPTION
**Pull request by spraot**
Note that there is no checks for self-referencing objects, but I don't think those should occur in this context.

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks for the PR, could you also expand this test case? (https://github.com/Koenkk/zigbee2mqtt/blob/master/test/controller.test.js#L94)

**Comment by rachetfoot** [comment]
Sure, I've done it now and fixed the eslint errors. However, I'm wondering if splitting e.g. colors into 3 separate topics is bad. Are there conventions for this sort of thing?

**Comment by Koenkk** [comment]
In Home Assistant (https://www.home-assistant.io/components/light.mqtt/#rgb_state_topic) they parse it as `r,g,b`. So perhaps we could do the same (one topic, with comma separated rgb values).

**Comment by rachetfoot** [comment]
Yeah, that looks like a better solution. I made a special case for color and made array support in general follow that pattern. I also moved the recursive function to a method since it was getting a bit long.

If we can imagine there being other special cases, would you consider adding a more general approach? I'm thinking some way that the device drivers could specify both JSON and non-JSON output.

In fact, I think this would already be possible with something like the following:

```
const payloadMessage = {color: [1,2,3]}
color.toJSON = function() {return {r: this[0], g: this[1], b: this[2]}
```

**Comment by Koenkk** [comment]
When this is needed we can opt for are more general approach, but this is good for now. Thanks!

**Comment by andreasbrett** [comment]
You reverted my https://github.com/Koenkk/zigbee2mqtt/pull/1462 with this PR.

**Comment by rachetfoot** [comment]
@andreasbrett not really. There should still be no quotes on ON and OFF, etc. Is there a different case that is broken now?

**Comment by andreasbrett** [comment]
> @andreasbrett not really. There should still be no quotes on ON and OFF, etc. Is there a different case that is broken now?

Sorry, I was wrong and deleted my comment quickly after realizing that. Please just ignore it...

**Pull request merged**
