### PR TITLE
Implement cli version of z2m

### PR DESCRIPTION
**Pull request by nurikk**
This commit implements z2m as generic cli application. After publishing this package, users will be able to install z2m as generic npm package (no need to bother with git clone/pul/npm ci etc)

`npm install -g zigbee2mqtt`

and launch using `zigbee2mqtt` command. 
Default data folder is located in users HOME directory and called `.z2m`

example: `/Users/nur/.z2m`

CLI respects `ZIGBEE2MQTT_DATA` env variable.

### CODE REVIEW

**Comment by Koenkk** [comment]
Cool, thanks!

**Comment by nurikk** [comment]
@ciotlosm FIY now you can install z2m only using npm
`npm install --force --production -g Koenkk/zigbee2mqtt#dev`

**Comment by ciotlosm** [comment]
@nurikk for stable, the correct install line is the below?

```
npm install --force --production -g Koenkk/zigbee2mqtt@1.16.1
```

**Comment by nurikk** [comment]
> zigbee2mqtt

it's not yet ready in stable version, but starting from next stable release you can use:

installation from npm registry
```
npm install --production -g zigbee2mqtt@1.16.1
```

installation from github tag
```
npm install --force --production -g Koenkk/zigbee2mqtt#1.16.1
```

**Comment by ciotlosm** [comment]
@nurikk Cool, I will wait for next release before redoing the docker build scripts, so I can do it consistently for both. Currently I unified the Dockerfile to build for both dev and stable, so would like to do it once. I will pin this PR so I don't forget on next release. 

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/dev/common/Dockerfile

**Pull request merged**
