### PR TITLE
Add Schwaiger ZHS-15/SPW35Z-D0 power socket

### PR DESCRIPTION
**Pull request by mario-1024**
add Zigbee power socket with measurement that has been discussed in the forums on issue #393 and a variant under #2467

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by mario-1024** [comment]
Did not see the message here. Thank you for merging this so quickly.
Tested for some month now and it works.
There seems to be a change in the ampere rating coming from a later commit, which fixed the wrong ampere measures I had before.
Only issue is a -32768W power measurement that appears randomly, which I did not find out where it comes from.

**Comment by travelography** [comment]
Hi @mario-1024 , does your power socket work with the current entry in the devices.js? I get only the state and according to https://github.com/Koenkk/zigbee2mqtt/issues/2467 there has been a change in the API that caused the plug to stop working properly. Which version of the zigbee herdsmann converters (https://github.com/Koenkk/zigbee-herdsman-converters) are you using?

**Comment by mario-1024** [comment]
I did not check the current version. Basically it works with the following limitations:
- I get correct power and voltage ratings, but from time to time, the power rating is a large negative number.
- Three of my devices went into update mode (purple light flashing) and did not recover. So I am down to one device at the moment. (I think I filed this as an issue alredy)
I am using zigbee2mqtt from the current hassio default installation.

**Comment by mario-1024** [comment]
I just checked my device and I could not access it. I removed it from the network, which was logged by zigbee2mqtt, but now I cannot join the network.

**Pull request merged**
