### PR TITLE
Add compatibility tests gh action

### PR DESCRIPTION
**Pull request by nurikk**

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
I'm seeing some errors: https://github.com/Koenkk/zigbee2mqtt/runs/6535610927?check_suite_focus=true

**Comment by nurikk** [comment]
> https://github.com/Koenkk/zigbee2mqtt/runs/6535610927?check_suite_focus=true

it looks like a random fluke https://github.com/Koenkk/zigbee2mqtt/actions/runs/2362362846

**Comment by Koenkk** [comment]
@nurikk I see, great 😄

**Pull request merged**
