### PR TITLE
Add support for Osram Smart Switch 4x

### PR DESCRIPTION
**Pull request by hgiesenow**
See https://github.com/Koenkk/zigbee-herdsman-converters/pull/1112 for
the converter

### CODE REVIEW

**Comment by dreimer1986** [comment]
Any news here?

**Comment by Jogobo** [comment]
I would like to see this in the master branch too.

**Comment by Koenkk** [comment]
Sorry for taking so long!

**Comment by dreimer1986** [comment]
Well, I cannot test anymore as my Lightify Switch seems to be dead now. Reset works (10x green blinking and then 3x fast), pairing somehow not. Not even on the original gateway from Osram though... It blinks a few times in blue and nothing is sent... Hopefully it works for the rest here though.

**Pull request merged**
