### PR TITLE
Add namespace-specific levels support to logger

### PR DESCRIPTION
**Pull request by Nerivec**
Adds the ability to alter levels for specific namespaces.
Also:
- Bring "MQTT publish" lines back to `info` level and add `z2m:mqtt` namespace for whole MQTT class, to allow changing the level for that namespace specifically
- Replace `warn` for `warning` (with automatic remap if `warn` still used in config) to match syslog levels used
- Use settings for logger-related values throughout the code instead of repeating them
- Short-circuit winston if determined level won't end up logging anything (performance gain since all transport levels are synced, no need to go through that logic)
- Remove `json` option from File Transport, not supported (stale value?)

Example use:

```yaml
advanced:
  log_namespaced_levels:
    z2m:mqtt: warning
    zh:ember:uart:ash: info
```

TODO
- [x] frontend support for new setting (object with unknown string keys mapped to log level values)
- [x] docs

### CODE REVIEW

**Comment by Nerivec** [comment]
@sjorge This, in combination with the debug-level regex should provide good customization for the logs. Let me know if you have any suggestions. With a bit of refactoring on the logger, and the fact this only looks up levels by key (namespace), it ends up way faster than the old calls in "filtered" scenario (noop), and about the same performance for "not filtered" scenario, so I think we're good on that end.
This setting should be more user-friendly, and the regex for `debug` more tailored for devs to filter out any which way they want.

**Comment by sjorge** [comment]
> * Bring "MQTT publish" lines back to `info` level and add `z2m:mqtt` namespace for whole MQTT class, to allow changing the level for that namespace specifically

<3

> This setting should be more user-friendly, and the regex for `debug` more tailored for devs to filter out any which way they want.

I started using this when that got implemented, it's working well for my needs. (I still have most info I care about and I can easily restart z2m when I need the info I filter out)

I'll try the other way when this gets added though, as I do indeed filter out 2 namespaces and nothing else.

Also I think your example in the PR comment is wrong? Looking at the diff should it not be:
```yaml
advanced:
  log_namespaced_levels:
    'z2m:mqtt': warning
    'zh:ember:uart:ash': info
```

**Comment by Nerivec** [comment]
Good catch, forgot a step on the ladder!

**Comment by Koenkk** [comment]
Created a PR for the [docs](https://github.com/Koenkk/zigbee2mqtt.io/pull/2750). @Nerivec please check if all OK and move out of draft, then I can merge it.

**Comment by martyzeq** [comment]
looks promising, thank you guys !

**Pull request merged**
