### PR TITLE
Rework ci and use package-lock.json instead of npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by nurikk**

### CODE REVIEW

**Comment by Koenkk** [comment]
https://github.com/Koenkk/zigbee2mqtt/blob/05975109a4186895428b96f14edfadacad151ef2/update.sh#L21 should also be updated

**Comment by nurikk** [comment]
> https://github.com/Koenkk/zigbee2mqtt/blob/05975109a4186895428b96f14edfadacad151ef2/update.sh#L21
> 
> should also be updated and
> https://github.com/Koenkk/zigbee2mqtt/blob/05975109a4186895428b96f14edfadacad151ef2/docker/Dockerfile#L11

done!

**Comment by nurikk** [comment]
Done here! Don't forget to squash :)

@Koenkk

**Comment by Koenkk** [comment]
Looks good, I'll merge this after the release on Wednesday.

Note to self: also update the docs.

**Pull request merged**
