### PR TITLE
Poll brightness/state after recalling scene

### LINKED ISSUE #8304: Group polling with direct binding not working for Hue bulb
## What happened

I have created a direct binding between my scene switch (Busch-Jaeger RB01) and a ZigBee group. The following clusters are bound to the group:

* LevelCtrl
* Scenes

Members of the ZigBee group are:

* Philips Hue Lux LWB004

Activating a scene within that group through that switch is working perfectly, however neither the Hue bulb's on/off state nor the group state is updated within zigbee2mqtt.

The Z2M docs regarding group bindings say that Zigbee2MQTT polls the devices for updates after remote events, however opening a bug report might be required as that is not enabled for all devices. So here is that bug report. :smile: 

## What did you expect to happen

I know from the binding docs that Hue bulbs do not report on/off state changes when controlled through a direct binding. However the docs also say that this can be worked around by putting the bulbs into a group.

So I expected the bulb and group state to update.

## How to reproduce it (minimal and precise)

1. Put Hue bulb in group "group_test" and define some scenes within that group
2. Bind scenes cluster from switch to "group_test"
3. Activate scene through switch
4. Lamp physically turns on according to scene, however zigbee2mqtt is not aware of that

## Debug info
Zigbee2MQTT version:     1.21.0
Adapter hardware: slae.sh stick (CC2652RB)
Adapter firmware version: 20210120

### PR DESCRIPTION
**Pull request by froogl**
When a ZigBee Scene Controller is recalling a scene through a direct binding
we need to poll for changed state and brightness.

Closes #8304

### CODE REVIEW

**Comment by sjorge** [comment]
That should already be handled here https://github.com/Koenkk/zigbee-herdsman-converters/blob/eb7bc618fb2238b58d86ec06f6e621fcf42f713b/converters/toZigbee.js#L4556

**Comment by froogl** [comment]
> That should already be handled here https://github.com/Koenkk/zigbee-herdsman-converters/blob/eb7bc618fb2238b58d86ec06f6e621fcf42f713b/converters/toZigbee.js#L4556

@sjorge As far as I can see the code you are referring to is used for recalling a scene through the API. That's not what my change is about - it's about polling for changes when a scene was recalled through a direct binding (without Z2M knowing). Not all ZigBee devices support reporting so Z2M uses this little polling hack for selected devices.

Or did I get your comment wrong?

**Comment by sjorge** [comment]
I see what you’re trying to do now. You can disregard my previous comment.

I wonder if we should also be reading the color information in the case of sceneRecall… as scenes commonly  also change those… 🤔

**Comment by Koenkk** [comment]
We should also read the color indeed (its in the `lightingColorCtrl` cluster)

**Comment by sjorge** [comment]
> We should also read the color indeed (its in the `lightingColorCtrl` cluster)

Probably need to do a similar trick as in the color to figure out what to read as not all bulbs support the same. Do we have acces to the device meta here?

**Comment by froogl** [comment]
Checking for color makes sense. I think I can check for `endpoint.supportsInputCluster` within `poll` to check if a particular cluster is present. But how do you check the supported attributes? Or can we read unsupported attributes without errors?

**Comment by sjorge** [comment]
There is a function for that in zhc, but I'm not sure this is available here
https://github.com/Koenkk/zigbee-herdsman-converters/blob/70498ad6ac633d63b8c1bbc8aa0839a65b19206d/lib/light.js#L11

It's a bit tricky as we store some of the info in the device definitions meta and we basically need color_mode + all the supported attribute so it z2m can calculate the color payload correctly

**Comment by Koenkk** [comment]
The best way to determine what color capabilities a device has is through the `colorCapabilities` attribute, from the spec:

Screenshot 2021-08-31 at 19 25 57

This can be achieved by adding to https://github.com/Koenkk/zigbee2mqtt/blob/05b19117cfc8a7759fa0f3681cd5b793b3c84fc9/lib/extension/bind.js#L29 `colorHueSaturation: colorTemperature: (value & 1<<0) > 0` and then use `getColorCapabilities` similar to https://github.com/Koenkk/zigbee2mqtt/pull/8585/files#diff-c9c7bbae896c037e703308efb924523e3c4ab4981e8ca5e462d5f4d1b5718436R43

**Comment by sjorge** [comment]
> The best way to determine what color capabilities a device has is through the `colorCapabilities` attribute, from the spec:
> 
> Screenshot 2021-08-31 at 19 25 57
> 
> This can be achieved by adding to
> 
> https://github.com/Koenkk/zigbee2mqtt/blob/05b19117cfc8a7759fa0f3681cd5b793b3c84fc9/lib/extension/bind.js#L29
> `colorHueSaturation: (value & 1<<0) > 0` and then use `getColorCapabilities` similar to https://github.com/Koenkk/zigbee2mqtt/pull/8585/files#diff-c9c7bbae896c037e703308efb924523e3c4ab4981e8ca5e462d5f4d1b5718436R43

Remember the [discussion](https://github.com/Koenkk/zigbee-herdsman-converters/issues/2037) a few months ago, colorCaps is incorrect on a lot of bulbs :( mostly they advertise enhancedHue support while they don't actually have it.

**Comment by Koenkk** [comment]
Ah forgot about that.

In that case a `const re = this.zigbee.resolveEntity(..)` should be done, the definition can then be accessed via `re.definition`

**Comment by froogl** [comment]
Currently regular reporting is only being set up for `currentX`, `currentY`and `colorTemperature`. That's why I have implemented polling only for these attributes for now. This can be adjusted as required.

There is one issue however: I do not have any devices supporting colors for testing. That's why the second commit is completely untested. I don't know if anybody wants to take over from here. We have 3 possibilities I guess:

1. Only merge my original changes with brightness and state polling
2. Test my changes (I don't even know if the codepath can be reached) and give me feedback/make edits.
3. Drop this PR and keep the original issue (#8304) open

**Comment by sjorge** [comment]
Lets see what @Koenkk says but maybe go for 1 and I'll try to look into color reading on sceneRecall once I got some time, I  got a bunch of color bulbs for testing but bit busy this week so it will be a bit before I can take a look at it.

**Comment by Koenkk** [comment]
This is a good starting point so can be merged in my opinion. 

Could you also add a test case (you can use https://github.com/Koenkk/zigbee2mqtt/blob/eb5750d968bbea8b61e50fc07e62e345c61aee3e/test/bind.test.js#L578 as an example). Make sure all code is covered, that is why checks are currently failing (check locally by running `npm run test-with-coverage`.

**Comment by froogl** [comment]
@ Koenkk Which approach do you mean can be merged? The current state (with untested color handling) or just the initial commit with just brightness/state polling? In the latter case the coverage actually remains untouched, as there are no code/logic changes.

**Comment by Koenkk** [comment]
The current approach (with the color reading)

**Comment by froogl** [comment]
I got a "semi-broken" color Hue bulb from a friend and tested my code with it. It is working properly :tada: 

I have also added a test for this, but I don't understand the coverage report. It says lines 135-139 in `bind.js` are uncovered, which is simply not true. These lines are covered by my test, otherwise the test would be failing. And putting a debug print in one of these lines also shows that the test suite is actually going over the code path... I am a little lost right there.

**Comment by Koenkk** [comment]
Fixed that, thanks!

**Pull request merged**
