### PR TITLE
`endpoint` in definition.toZigbee can be an array of string

### PR DESCRIPTION
**Pull request by Zitrium31**
This change is required for [PR #8190](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8190) to correct [issue #24352](https://github.com/Koenkk/zigbee2mqtt/issues/24352).

`endpointNames : string[]` used in [moderExtend.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/modernExtend.ts) may includes more that 1 endpoint. Array of `endpointNames` being recorded in definition.toZigbee, converter filtering in `publish.ts` must now be able to find the given `endpointName` within an array of string (and not only a string).

This PR in addition to [PR #8190](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8190) have been finally sucessfully tested on a diy device made of the following 4 endpoints:
- Endpoint 8 : genBasic, genIdentify, msTemperatureMeasurement.
- Endpoint 10 : closuresWindowCovering ( `ep1` ) --> It uses key `state`
- Endpoint 12 : genOnOff ( `relay` ) --> It uses also key `state`
- Endpoint 14 : genOnOff ( `relay2` ) --> It uses also key `state` and the cluster `genOnOff`

and the following external definition:
```javascript
const {deviceEndpoints, temperature, onOff, windowCovering} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['GADORC2407'],
    model: 'GADORC2407',
    vendor: 'MyDiyZigbee',
    description: 'Garage Door Lock Remote Control',
    extend: [
        deviceEndpoints({"endpoints":{'ep1':10, 'relay':12, 'relay2':14}}),
        temperature(),
        onOff({"powerOnBehavior":false, "endpointNames":['relay', 'relay2']}),
        windowCovering({"controls":['lift'], "coverInverted":true, "stateSource":'lift', "coverMode":false, "endpointNames":['ep1']})
        ],
};
module.exports = definition;
```

### CODE REVIEW

**Comment by Zitrium31** [comment]
Last ci / tests failed due to `Tz.Converter.endpoints` renamed and type changed to `string[]` not yet pulled here. See  [PR #8190](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8190) / commit [Simplify Tz.Converter.endpoints type to string[] array only](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8190/commits/4ab773a57ef294ed0796442e45256d6b00b3dbf2)

**Comment by Koenkk** [comment]
Thanks!

**Comment by Zitrium31** [comment]
I found the regression bug comes from [devices/gledopto.ts](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/gledopto.ts#L120) at [line 120](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/gledopto.ts#L120) :
```javascript
    result.toZigbee = utils.replaceInArray(
        result.toZigbee,
        [tz.light_onoff_brightness, tz.light_colortemp, tz.light_color, tz.light_color_colortemp],
        [
            tzLocal.gledopto_light_onoff_brightness,
            tzLocal.gledopto_light_colortemp,
            tzLocal.gledopto_light_color,
            tzLocal.gledopto_light_color_colortemp,
        ],
        false,
    );
``` 
It seems `tz.light_onoff_brightness` is not found/replaced anymore by function `replaceInArray()`
I am trying to find a fix to make this compatible with the `{...tz.light_onoff_brightness, endpoints: args?.endpointNames}` introduced in `modernExtend.ts` with but without success up to now.

**Comment by Koenkk** [comment]
Fixed!

**Pull request merged**
