### PR TITLE
Make logging transports configurable

### PR DESCRIPTION
**Pull request by wilmardo**
Hi Koen!

First of all thanks for all the awesome work on this project!

### Reasoning for the change
This PR makes the logging transports configurable, the user now has the choice to do only stdout logging or disable logging altogether (define an empty list). I personally do not need file logging since the stdout is captured by Kubernetes. Same point applies for running on Docker Swarm, the container logs are saved by the daemon. No need to save them separately :)

I use my own Docker image for Kubernetes, since Zigbee2mqtt isn't k8s compatible out of the box. My Docker build compiles zigbee2mqtt to a static binary and moves this to a scratch container and the binary is run as a non root user (better security and should allow a readonly filesystem in the container). Files needed for persistence are symlinked to /data by the entrypoint.
https://github.com/LANsible/docker-zigbee2mqtt

Might write a blogpost about the steps I took to get it to run on Kubernetes :)

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks for the pr, could you add the test (so that the CI/CD succeeds?)

**Comment by wilmardo** [comment]
Yes check! Forgot to ask about the tests, what should I run and where should I look?
Could not find a contributing guide :)

**Comment by Koenkk** [comment]
You can check at https://dev.azure.com/koenkk/zigbee/_build/results?buildId=469. It currently fails because the test coverage is below 100%, so you need to add some tests to cover the new code. (e.g. https://github.com/Koenkk/zigbee2mqtt/blob/dev/test/logger.test.js)

**Comment by wilmardo** [comment]
@Koenkk I did my best but I am completely stuck on the tests. Based on #2400 I tried to implement some of the tests but I cannot get it to work:

```javascript
    it('Set logging to console only', async () => {
        settings.set(['advanced', 'log_output'], ['console']);
        await controller.start();
        expect(logger.info).toHaveBeenCalledWith(`Logging to console only`);
    });
```
It fails because `settings.advanced.log_output` still is set to file and console when I print it during the tests. 

```
    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "Logging to console only"
    Received
           1: "'Test:' console,file"
           2: "Logging to directory: 'undefined'"
           3: "Starting zigbee2mqtt version 1.7.1+dev (commit #616cc7e)"
```
So the first statement doesn't seem to work but it seems to work in all the earlier tests.

Do you have some pointers? I have no previous experience with NodeJS, the application code was an easy one to figure out but the tests are a whole other level :')

**Comment by Koenkk** [comment]
Test for the logger are indeed very tricky, fixed now. Thanks!

**Pull request merged**
