### PR TITLE
Adding Philips Adore lights to Home Assistant integration

### PR DESCRIPTION
**Pull request by LagaV**
Adding Philips Adore lights to Home Assistant integration

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!

**Comment by LKLHA** [comment]
Hi, @Koenkk I have a Adore ligth with model 3417711P6 which should be similar to the other non-bluethoot Adroe ligths. Id there a easy fix to this?
I tried adding it on my own, but I had no luck. Too unexperienced. Will continue to try

**Comment by Koenkk** [comment]
@LKLHA can you provide the data/database.db entry of your device?

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by LKLHA** [comment]
Wow! Thanksm I will buy you a couple of beers :)

**Pull request merged**
