### PR TITLE
Discovery fix on restart HASS + adding the timestamp of last received zigbee message visible in HASS

### PR DESCRIPTION
**Pull request by ugrug**
- On restarting Home Assistant, resending device discovery information
- Add timestamp on receiving message from Zigbee
- Add last_message into MQTT info for devices

### CODE REVIEW

**Comment by Koenkk** [comment]
why do you rediscover on hass startup? these messages are retained by the mqtt broker.

**Comment by ugrug** [comment]
On restarting hass without restarting zigbee2mqtt causes my zigbee devices disappear. If this only issue on my configuration, possible caused by using rabbitmq.

**Comment by Koenkk** [comment]
Can you view the retained MQTT messages?

**Comment by ugrug** [comment]
I think this issue only on using another broker instead of hass internal mqtt broker.

**Comment by Koenkk** [comment]
I use an external mosquitto which works without problems.

**Comment by ugrug** [comment]
MQTT discovery rely on persistence not enabled in my configuration. I'll move adding timestamp to separate request.

**Pull request closed without merging**
