### PR TITLE
Persist state cache if a devices leaves, until the system is stopped

### PR DESCRIPTION
**Pull request by MatAtBread**
This setting does not remove a device from State if it leaves the network.

The reasoning is that some of my devices (mainly Tuya smart TRVs) keep leaving & re-joining after a short period, and their state is lost and not available via a query (they don't respond to a "get").

The obvious downsides are:
* If a device *really* leaves, it will remain in the saved state.
* The saved state might become incoherent with the actually device state, which can of course change for any number of reasons.
....however in my network this is unlikely and the frequent disappearance of a device's state makes my application unusable.

It occurs to me that this might be better done by a setting that is device (or model) specific, and that a "timeout" might be preferable (for example, delete the device from the state if and only if it doesn't re-join with `n` seconds). In this case, the setting would be an integer number of seconds, where `0` would be the default (delete immediately).

@Koenkk - I'd be grateful for your input/suggestions/opinions here.

### CODE REVIEW

**Comment by Koenkk** [comment]
@MatAtBread maybe we can clean the state on shutdown? Then we don't need an option for this, it can be done here: https://github.com/Koenkk/zigbee2mqtt/blob/52e545f900c799377a69b1a991577c7ccdf641ec/lib/controller.ts#L191

**Comment by MatAtBread** [comment]
Update to action pending deletions on system shutdown.

I've left the setting and made it a timeout. In this way, even if set a device that has genuinely left the network will (after the timeout) eventually disappear from the state.

**Comment by Koenkk** [comment]
If this is just done on shutdown it is good enough (and much more simpler). Then the option can also be removed.

**Comment by MatAtBread** [comment]
I'm happy to make that change, but are you not concerned that the change in behaviour with affect existing users whose devices will keep their state of they leave the network? Perhaps there should be some method to flush the deletions without shutting down the system?

**Comment by Koenkk** [comment]
I currently do not see any issue with that and it also makes it very explicit. I prefer to start simple and in case people have issues with it improve later (this prevents unnecessary code and complexity). 

I think another improvement would be to move all the code to https://github.com/Koenkk/zigbee2mqtt/blob/52e545f900c799377a69b1a991577c7ccdf641ec/lib/state.ts#L34 . For this the state constructor has to be updated to accept a `zigbee` instance.

**Comment by MatAtBread** [comment]
You're the boss :) I'll simplify & update the PR later today

**Comment by Koenkk** [comment]
Thanks for the updates, I think it can be simplified a bit more. With the following (pseudo) code it is not necessary anymore to register the handlers:

```js
Object.keys(this.state).filter((k) => typeof k === 'string' && !this.zigbee.resolveDevice(k)).forEach((k) => delete this.state[k]);
```

**Comment by MatAtBread** [comment]
Updated as requested

**Comment by Koenkk** [comment]
Thanks!

**Comment by RubenKelevra** [comment]
@Koenkk 

> If this is just done on shutdown it is good enough (and much more simpler). Then the option can also be removed.

Cleaning up on shutdown isn't enough I think, as this maybe happens every other month or so.

I think it would be good to clean up if the device becomes unavailable by Zigbee2MQTT's settings - meaning that timeouts configured are reached for active/passive devices regarding the last received message.

This way it at least gets cleaned up after a while if a device runs out of battery, instead showing it apparently "online".

**Pull request merged**
