### PR TITLE
fix!: Home Assistant: remove duplicate `sensor`/`select` for `select`/`number`/`button` entities

### PR DESCRIPTION
**Pull request by Drafteed**
### Breaking changes
This removes duplicate `sensor` for `select` and `number` entities in Home Assistant. 
Additionally, it removes duplicate `select` for `button` entities.
It also removes removes duplicate `sensor` for `text` entities.

Based on https://github.com/Koenkk/zigbee2mqtt/discussions/24198#discussioncomment-10867605

### CODE REVIEW

**Comment by Koenkk** [comment]
I initially agreed to this and even made the change in one of the PRs, but since this has never been deprecated properly (no option to disable it) I think we should not put this in 2.0.0

**Comment by mundschenk-at** [comment]
How would you even deprecate it? Add another legacy setting that defaults to on for some versions? To follow semantic versioning, you'd have to remove it only in a 3.0.0 version that's probably very far beyond the horizon.

Personally, I think the switch from 1.x to 2.x allows "binary breaks" even without a formal deprecation period (and wasn't this also mentioned in the big PR/discussion for several weeks at least?).

**Comment by Drafteed** [comment]
> I initially agreed to this and even made the change in one of the PRs, but since this has never been deprecated properly (no option to disable it) I think we should not put this in 2.0.0

These sensors have long been disabled by default in HA. I believe it's nearly safe to remove them given the current scope of breaking changes. I think this should be in 2.0.0.

**Comment by Koenkk** [comment]
> These sensors have long been disabled by default in HA. I believe it's nearly safe to remove

That's very true indeed, then let's merge this into 2.0.0

Before merging:
- Could you also cleanup this one: https://github.com/Koenkk/zigbee2mqtt/blob/71e163fcc3332a61983c12c87dcbca9ab61c266f/lib/extension/homeassistant.ts#L1152
- Can we easily generate a list of devices/sensors that are affected by this such that it can be added to https://github.com/Koenkk/zigbee2mqtt/discussions/24198 ?  This [test case](https://github.com/Koenkk/zigbee2mqtt/blob/5b907f2f77490cfcff1a39f5b731d508d0344663/test/homeassistant.test.js#L69) calls the discover method for all supported devices, I think by adding some `console.log` it should be possible to create a list?

**Comment by Drafteed** [comment]
> * Can we easily generate a list of devices/sensors that are affected by this such that it can be added to [Zigbee2MQTT 2.0.0 breaking changes #24198](https://github.com/Koenkk/zigbee2mqtt/discussions/24198) ?  This [test case](https://github.com/Koenkk/zigbee2mqtt/blob/5b907f2f77490cfcff1a39f5b731d508d0344663/test/homeassistant.test.js#L69) calls the discover method for all supported devices, I think by adding some `console.log` it should be possible to create a list?

Sure 😄 You can try to parse them as you like :)

[Removed `sensor` entities in favour of `select` entities](https://github.com/user-attachments/files/18031979/1.json)
[Removed `select` entities in favour of `button` entities](https://github.com/user-attachments/files/18031984/2.json)
[Removed `sensor` entities in favour of `text` entities](https://github.com/user-attachments/files/18031987/3.json)

I think we can just make a note that duplicate entities have been removed from the HA.

**Comment by Koenkk** [comment]
Thanks! Added the following to https://github.com/Koenkk/zigbee2mqtt/discussions/24198

> - Removed duplicate `sensor`/`select` for `select`/`number`/`button` entities, the full list of removed entities per model can be found [here](https://gist.github.com/Koenkk/7499edc879b7398213438c6e837ceb2c).

**Comment by Ellghe** [comment]
Seems like it does not pick up  "zigbee2mqtt/SOMRIG shortcut button/action" and it is the asme for all IKEA buttons. Can anybody HELP?

**Pull request merged**
