### PR TITLE
Update how_to_secure_network.md

### PR DESCRIPTION
**Pull request by Bruceforce**
Make clear that the key consists of 16 hex values and gave an example how to generate a key with command line tools.

### CODE REVIEW

**Comment by andreasbrett** [comment]
Oh cool, didn't know that `configuration.yaml` also takes hex values. So I could also use ` network_key: [0x07, 0x03, 0x05, 0x07, 0x09, 0x0B, 0x0D, 0x0F, 0x00, 0x02, 0x04, 0x06, 0x08, 0x0B, 0x0C, 0x0D]` instead of ` network_key: [7, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 11, 12, 13]`?

That would be great as other tools mostly use hexadecimal representation and not having to convert between dec and hex reduces errors.

**Comment by Koenkk** [comment]
@andreasbrett @Bruceforce good idea, can you combine them?

**Comment by Bruceforce** [comment]
@andreasbrett @Koenkk I tried to combine both but fucked up 😞 I think( sorry). If you want you can merge @andreasbrett writing and I'll open a new pr or fix this one with the example on how to generate a valid key.

**Comment by Koenkk** [comment]
@Bruceforce you need to rebase your `patch-1` branch with the latest `master`.

**Comment by Bruceforce** [comment]
@Koenkk I thought I just did that. https://github.com/Koenkk/zigbee2mqtt/compare/master...Bruceforce:patch-1 doesn't show any difference besides the one of the how_to_secure_network.md

**Comment by andreasbrett** [comment]
Looks good to me, not sure how you come to the conclusion of having f*ed this up.

**Comment by Bruceforce** [comment]
I commited with my gitlab account by accident then rebased from the wrong branch and tried to merge your stuff and was really confused in the end and wasn't sure if that what I did was right.

**Comment by Koenkk** [comment]
Thanks @Bruceforce @andreasbrett !

**Pull request merged**
