### PR TITLE
Add device remove

### PR DESCRIPTION
**Pull request by ciotlosm**
Addresses https://github.com/Koenkk/zigbee2mqtt/issues/35

### CODE REVIEW

**Comment by ciotlosm** [comment]
@kirovilya

**Comment by ciotlosm** [comment]
Maybe it needs also correspondent for https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/util/settings.js#L21 ?

**Comment by Koenkk** [comment]
Yes, we also need a `removeDevice()` in `settings.js` so that the device is removed from `configuration.yaml`.

**Comment by ciotlosm** [comment]
@Koenkk implemented

**Comment by Koenkk** [comment]
Ready for merge I think, @ciotlosm can you do a final check?

**Comment by ciotlosm** [comment]
Will check soon and report back. I will setup the stick in my prod env after for the interval sensitivity check

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
A new bug was introduced. If by any chance someone cleaned manually a device from `database.db` you can't remove it using mqtt from configuration.yaml. On my version this use case worked.

**Comment by Koenkk** [comment]
These cases are now possible, thanks!

**Comment by marcgarciamarti** [comment]
Guys, I'm very new to gtihub. Just wondering what this above really means. Is my understanding right when I say you are still working on it? I see Koenkk merged commit into Koenkk:master, but I'm not sure what that means.

**Comment by Koenkk** [comment]
@marcgarciamarti merged means that the functionality is available, see https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttbridgeconfigremove

**Comment by goldiiii** [comment]
> 
> 
> @marcgarciamarti merged means that the functionality is available, see https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttbridgeconfigremove

Link changed:
https://koenkk.github.io/zigbee2mqtt/information/mqtt_topics_and_message_structure.html

**Pull request merged**
