### PR TITLE
Remove device extended #169

### PR DESCRIPTION
**Pull request by tb-killa**
Implemented Remove Device with Parameter ``ReJoin`` for https://github.com/Koenkk/zigbee2mqtt/issues/169

Json Structure (only reJoin!) like https://github.com/zigbeer/zigbee-shepherd/wiki#removeieeeaddr-cfg-callback
```
cfg (Object):

reJoin (Boolean): Set to true if device is allowed for re-joining, otherwise false. Default is true.
```

**Attention**
If ``controller.js`` jump to ``_forceRemove`` the ``ReJoin`` Param is rejected and ignored.
So ``ReJoin`` Param only work if zigbee-shepherd ``remove`` function work at first step!!

### CODE REVIEW

**Comment by Koenkk** [comment]
I tested with a WXKG01LM  but this device always falls back to the force remove where the reJoin parameter is not used. Does this work for you?

```bash
2018-7-31 21:57:12 WARN Failed to remove '0x00158d0001d8e1d2', trying force remove...
2018-7-31 21:57:12 INFO Successfully removed 0x00158d0001d8e1d2
```

**Comment by tb-killa** [comment]
Sadly i got this only work with the ecozy device.
Every other ones jump to force remove
```
2018-7-31 22:08:11 DEBUG Recieved mqtt message on topic 'zigbee2mqtt/bridge/config/remove' with data '{"friendlyName":"0x0017880103caab06","reJoin":"false"}'
  zigbee-shepherd:request REQ --> ZDO:mgmtLeaveReq +15s
2018-7-31 22:08:21 WARN Failed to remove '0x0017880103caab06', trying force remove...
2018-7-31 22:08:21 INFO Successfully removed 0x0017880103caab06
2018-7-31 22:08:21 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"device_removed","message":"0x0017880103caab06"}'
```
I´v search for the ``devbox`` function or the ``NedDB`` function who sign the remove command to the ``database.db``.
Maybe we could add the database-remove to our force remove function.?

This looks like this: ``{"$$deleted":true,"_id":"IN32H3eGbwSlaLA7"}``

**Comment by tb-killa** [comment]
Okay i think i got it.
The ``database.db`` content fillout from ``devbox``.

The original function look like this:
```
ZShepherd.prototype._unregisterDev = function (dev, callback) {
    return Q.ninvoke(this._devbox, 'remove', dev._getId()).nodeify(callback);
};
```
Maybe we have to push the original ``ZShepherd.prototype.remove`` again after "force-remove" to bring device for real in leaving mode
```
return this.request('ZDO', 'mgmtLeaveReq', reqArgObj).then(function (rsp) {
```
because acutally it seems that the force-remove function only delete content from ``devbox`` and ``database.db`` and the device doesn´t get the ``levereq`` in reality....

**Comment by tb-killa** [comment]
@Koenkk: It seems to be that this is a general Problem: https://github.com/zigbeer/zigbee-shepherd/issues/14

**Comment by Koenkk** [comment]
I see, would it be possible to also have the `reJoin` thing with the force remove?

**Comment by tb-killa** [comment]
the problem would be follow: If device isn´t only we couldn´t send the ``request('ZDO', 'mgmtLeaveReq', reqArgObj)`` with ``jejoin=false``, because this option is on device side i think.

What we could do is follow: Implement check for devicejoin with https://github.com/zigbeer/zigbee-shepherd/wiki#acceptdevincomingdevinfo-callback so we ``Accept or reject the device join the network. Overridable.``. Maybe we extend the ``configuration.yaml`` file and the per ``devices`` section with attribute ``joinable`` ??

**Comment by Koenkk** [comment]
@tb-killa yes that would indeed be a solution for this. In this way users can also unban devices.

**Comment by tb-killa** [comment]
@Koenkk What about building remove.queue who first check if device is online, if not do ping so maybe device is wakeup. after that we do remove function.. if failed .. lets tray again, maybe max 4 stepps.
after that we would do force remove .. the queue is if somebody would remove multiple devices in near time.

**Comment by Koenkk** [comment]
Does the ping wakeup the device?

**Pull request closed without merging**
