### PR TITLE
Eurotronic thermostat improvments

### PR DESCRIPTION
**Pull request by sti0**
- Setting temperature_command_topic to current_heating_setpoint for Eurotronic thermostat
- Thermostat function to dynamically publish values to HA

### CODE REVIEW

**Comment by Koenkk** [comment]
Instead of changing the topic; isn't it more logical to just change https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/toZigbee.js#L1316 to `occupied_heating_setpoint`?

**Comment by sti0** [comment]
As mentioned in the docs (https://eurotronic.org/wp-content/uploads/2019/01/Spirit_ZigBee_BAL_web_DE_view_V9.pdf) at page 15 the device has both attributes. Changes at the physical Eurotronic device are published as the current temperature set point (0x4003). If we change it in toZigbee we must change it in fromZigbee as well https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L2291

Im my opinion it's better to change the topic because this matches the behavior of the device. Otherwise we put both attributes in one drawer. Maybe there is a use case for both?

**Comment by sti0** [comment]
@Koenkk last build test fails on test/bridgeConfig.test.js. I don't understand what this has to do with my PR. Is this a bug?

```
FAIL test/bridgeConfig.test.js
  ● Bridge config › Should handle when remove fails

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 0
    Received number of calls: 1

      276 |         expect(device.removeFromNetwork).toHaveBeenCalledTimes(1);
      277 |         expect(settings.getDevice('bulb_color')).toStrictEqual({"ID": "0x000b57fffec6a5b3", "friendlyName": "bulb_color", "friendly_name": "bulb_color", "retain": false})
    > 278 |         expect(MQTT.publish).toHaveBeenCalledTimes(0);
          |                              ^
      279 |     });
      280 | 
      281 |     it('Should handle when ban fails', async () => {

      at Object.toHaveBeenCalledTimes (test/bridgeConfig.test.js:278:30)
```

**Comment by Koenkk** [comment]
> Im my opinion it's better to change the topic because this matches the behavior of the device. Otherwise we put both attributes in one drawer. Maybe there is a use case for both?

I think that for all thermostat we should set the same value, either `current_heating_setpoint` or `occupied_heating_setpoint`.

Which one fits best with home assistant?

**Comment by sti0** [comment]
For Home Assistant it's irrelevant. `current_heating_setpoint `is a special Eurotronic behavior. Devices like eCozy don't support this.

Problem is if you change the temperature at the device its pushed to the `current_heating_setpoint `(0x4003) and not to the `occupied_heating_setpoint `(0x0012). On the old implementation a change in Home Assistant sets the `occupied_heating_setpoint `which ends up in a delayed delivery to the device (somehow `current_heating_setpoint ` is set, by the device if `occupied_heating_setpoint `is changed) In my investigations the `occupied_heating_setpoint `is sometimes set automatically (but I can't confirm this 100%). If you map now the `current_heating_setpoint `to `occupied_heating_setpoint `it will cause in a breaking change for some people who use both setpoints. 

More information on page 15 of the docs (https://eurotronic.org/wp-content/uploads/2019/01/Spirit_ZigBee_BAL_web_DE_view_V9.pdf)

**Comment by Koenkk** [comment]
If conceptually this is the same thing I think we should migrate both to the same topic.

That means that e.g. https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/converters/toZigbee.js#L748 should change to `key: ['current_heating_setpoint', 'temperature'],`, after this it will respond to both. 

Then the command topic can be changed to `temperature`.

**Comment by sti0** [comment]
Should we use , `heating_setpoint` instead of `temperature`?

But how to handle this for Eurotronic devices? Actually it supports both, `occupied_heating_setpoint ` (https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/devices.js#L3985) and `current_heating_setpoint`(https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/devices.js#L3989) . If we match the values for the keys `occupied_heating_setpoint `and `current_heating_setpoint `to `heating_setpoint `(or `temperature `as you proposed) then both will overwrite themselves every time (that's not the way I expect the device working). 

Please note that `occupied_heating_setpoint `!= `current_heating_setpoint `for Eurotronic devices. As I'm not the manufacture I'm not knowing anything about the `occupied_heating_setpoint `and how to use it. Only thing I investigated for setting temperature in Home Assistant is that the `current_heating_setpoint `is the right value.

Options:
1. Leave it as it is in that PR
2. Remove `tz.thermostat_occupied_heating_setpoint` and maybe `tz.thermostat_unoccupied_heating_setpoint `for Eurotronic devices and add the key `heating_setpoint` or `temperature `to the functions `thermostat_occupied_heating_setpoint()` and `eurotronic_current_heating_setpoint()` in toZigbee.js

As I mentioned I have no idea how to use the occupied_heating_setpoint for this device but maybe there are use cases. If we change it the 2. way it has impact for existing implementations for other tools like ioBroker etc. Therefore I recommend only to change this for HA.

**Comment by sti0** [comment]
Please note that a HA change for the published min + max temperature is also needed. (This is already included in this PR).
Example:
Eurotronic min/max. 5/30
eCozy min/max: 7/30

**Comment by sti0** [comment]
Found in the docs:
image

Translated:
> The transferred target temperatures such as Occupied/Unoccupied Heating Setpoint Attributes (0x0012 or 0x0014)
> **are copied** to the Current Temperature Setpoint attribute (0x4003) in order to set the TRV without manufacturer specific
> to be able to use attributes.

Which means we could do 2. option.

> Remove tz.thermostat_occupied_heating_setpoint and maybe tz.thermostat_unoccupied_heating_setpoint for Eurotronic devices and add the key heating_setpoint or temperature to the functions thermostat_occupied_heating_setpoint() and eurotronic_current_heating_setpoint() in toZigbee.js

@Koenkk what do you mean:

> Should we use , heating_setpoint instead of temperature?

**Comment by Koenkk** [comment]
Forget my comment about using the `temperature` to set the `occupied_heating_setpoint` , if we change this we should also update the current fromZigbee converters which would lead to a breaking change (https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L2237), and I doubt now if this makes it easier at all.

Does this mean that by setting the `occupied_heating_setpoint` we can set the `current_temperature_setpoint`? (docs states that it can be controlled trough these?)

**Comment by sti0** [comment]
If you change the setpoint on the physical device it publishes the current heating setpoint. Occupied heating setpoint will published some minutes later and not immediately. 
If you set occupied heating setpoint (overz2m) it should copy this value to current heating but I'm not sure if this happens directly. 

As a change on the physical device not reported as occupied heating setpoint immediately we need to us the current heating setpoint else the implementation is like it is actually.

**Comment by Koenkk** [comment]
Yes I see, after this discussion I agree with you that this is the best solution. Thanks!

Did some small refactoring, can you check if this is still OK? Then it can be merged.

**Comment by sti0** [comment]
Your optimizations are working. This PR is ready 4 merge.

Just an example for conclusion:
zigbee2mqtt:info  2019-10-16T21:10:09: MQTT publish: topic 'zigbee2mqtt/climate_buro', payload '{"`**current_heating_setpoint":14.5,**`"eurotronic_system_mode":1,"local_temperature":21.58,**`"occupied_heating_setpoint":12`**,"unoccupied_heating_setpoint":7,"eurotronic_error_status":0,"pi_heating_demand":0,"battery":100,"linkquality":131,"system_mode":"heat"}'

=> changed temperature at the physical device. current_heating_setpoint changed to 14.5...I can't remember when I set a 12 degree temperature (occupied_heating_setpoint) ^^

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
