### PR TITLE
LLKZMK11LM Supports power, temperature and consumption

### PR DESCRIPTION
**Pull request by yozik04**
LLKZMK11LM already sends power, temperature and consumption in mqtt json.

```
info  2020-01-02 20:06:20: MQTT publish: topic 'zigbee2mqtt/front_outdoor_lights', payload '{"state_l1":"ON","linkquality":54,"state_l2":"OFF","power":35.1,"consumption":2.89,"temperature":33}'
```

Not sure in which units `consumption` is. Not adding right now.

### CODE REVIEW

**Comment by sjorge** [comment]
Probably watt or kwatt, depending on what is plugged in you should be able to guess.

e.g. a hair dryer usually is 1000watt (1kwatt) or more.

**Comment by yozik04** [comment]
I almost sure it is kwh.
It changed to 3.07 since yesterday. I have 35 watt bulb grid load. They worked around 5 hours in total. So it matches.

**Comment by sjorge** [comment]
Ah yeah that makes sense, power = current usage, consumption = total usage over X time.
So for that kwh would make more sense! I wonder what the time periode is.

**Comment by yozik04** [comment]
Not sure what icon to put for power consumption: I've put `mdi:power-plug`.  Any better options?

**Comment by yozik04** [comment]
Maybe `credit-card-clock`?
https://cdn.materialdesignicons.com/4.5.95/

**Comment by sjorge** [comment]
mdi-flash, mdi-chip or mdi-network could also potentially work.

**Comment by yozik04** [comment]
`mdi-flash` is better.

**Comment by Koenkk** [comment]
Thanks!

**Comment by julien-w** [comment]
In the xiaomi app, I'm quite sure there is a different power and a consumption for each channel. Not for the temperature.
But i can't look, I've migrated everything on zigbee2mqtt ;)

**Comment by yozik04** [comment]
Power and consumption in current case are sum of both channels. Just tested. No idea about Xiaomi app. Temperature is useless as it measures temperature inside the box. It shows 33 C when out of the box is around 12-15.

**Comment by zladukas** [comment]
Temperature is very useful to cut-off on too high load. Going to test it some time later.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> In the xiaomi app, I'm quite sure there is a different power and a consumption for each channel. Not for the temperature.
> But i can't look, I've migrated everything on zigbee2mqtt ;)

How sure are you that this relay do measure power consumption for each channel in the xiaomi app?
I see this screenshot here and ask myself if it could be possible that we can get individual consumptions (watt) from both channel:
https://www.domoticz.com/forum/viewtopic.php?p=234559&sid=e6298adb0d939cc122b64100bf05b0c1#p234559

**Pull request merged**
