### PR TITLE
Update thermostat function

### PR DESCRIPTION
**Pull request by Heronimonimo**
Update thermostat function to have 0.5 degree steps and add cool mode so TRVs who support it can use it (like the eCozy). Fixes the cool mode in #3727

### CODE REVIEW

**Comment by Heronimonimo** [comment]
Hmm, it did seem to work for a short period, but now I can't get it to run anymore.

**Comment by Koenkk** [comment]
@Heronimonimo do you see any error in the zigbe2mqtt log when setting the cool now?

**Comment by Heronimonimo** [comment]
Not getting any error back. Could it be that the cool function is not supported by the device? The documentation seems quite different to what the device seems to support.

**Comment by Koenkk** [comment]
@Heronimonimo I don't have/know about this device so not able to judge that

**Comment by Heronimonimo** [comment]
The documentation seems to be based on the generic hvacThermostat definition of the Zigbee standard. As far as I can see the eCozy only seems to support a limited subset.

Is there a way to find out which device specific registers (like the Eurotronic thermostat has) there are?

**Comment by Koenkk** [comment]
@Heronimonimo device specific commands/attributes are most of the time reversed engineered from communication with the original bridge.

**Pull request closed without merging**
