### PR TITLE
Update pairing_devices.md

### PR DESCRIPTION
**Pull request by djpollum**
As discussed in #185 I'd like add a tip for pairing devices when mentioned pairing tips are failing.
- pair your Xiaomi device to the original (Aqara) Hub via the MiHome app. After that unplug your Hub and pair your Xiaomi device again to your CC25xx device.

This can be added to the [pairing_devices.md](https://github.com/Koenkk/zigbee2mqtt/blob/master/docs/getting_started/pairing_devices.md#xiaomi)
on the line:
NOTE: When you fail to pair a device, try replacing the battery, this could solve the problem.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you rebase this pr?

**Comment by djpollum** [comment]
> 
> 
> Could you rebase this pr?

Sorry @Koenkk , but I don't know how to do this.
Can you please do this for me?

Mercikes!

**Comment by Koenkk** [comment]
I'm not sure how you made this pr, could you provide a link to your commit?

**Comment by eddeandres** [comment]
Just another tip I’ve found as well is that you can long press the pairing button on the device for about 20 seconds to switch it off. When switched on again it seems to be able to pair with zigbee mqtt fine.

**Pull request merged**
