### PR TITLE
Support hard reset ZNP/Coordinator

### PR DESCRIPTION
**Pull request by dzungpv**
Me and many other user sometimes must re-flash the Coordinator to fix network problem, it take time and hard for some user, so hard reset has been support.
So hard reset trigger the hardware reset (SoC resets), and clear NVRAM
```
zigbee2mqtt/bridge/config/reset
Hard reset the ZNP (CC2530/CC2531/CC2538/CC2652R1).
```
@Koenkk It is just Lint error for space, you can edit it

### CODE REVIEW

**Comment by Koenkk** [comment]
When the coordinator crashed, it doesn't communicate at all anymore, how could we send the reset command?

**Comment by dzungpv** [comment]
@Koenkk may be we make the web control panel for it, but now i only want it work when not crash, sometimes znp could not add more device, i must plug it to debugger/programmer to clear the nvram and reflash the firmware, and after that it work, so with hard reset, i just send hard reset command, and restart z2m and everything work fine.

**Comment by Koenkk** [comment]
@dzungpv I see, I will integrate this after #1888 because this code also has to be adapted to zigbee-herdsman.

**Comment by Koenkk** [comment]
Unstale

**Comment by CodeFinder2** [comment]
I have observed a (possibly) similar issue: sometimes I am not able to pair new devices. I then need to reboot my host/entire system or, much quicker, have to stop zigbee2mqtt and unplug and replug the CC2531 USB stick. Afterwards, pairing works (35+ device, source routing firmware 2019-06-08).

Is it related to what is addressed in this PR?

**Comment by dzungpv** [comment]
@CodeFinder2 it has been release in software level, but i am not sure about hardware level.

**Comment by enishoca** [comment]
@dzungpv @Koenkk do you have to pair all the devices after hard reset.  Would be great if the documentation tells you what this does and how 'destructive' it is or not?

**Pull request closed without merging**
