### PR TITLE
Added ZB-SmartPlug-1.0.0

### PR DESCRIPTION
**Pull request by dgomes**
Smart Plug sold by Portuguese Energy Provider EDP under the power management package REDY

### CODE REVIEW

**Comment by Koenkk** [comment]
Good!

2 comments:
- I see to you added `homeassistant.sensor_power` but there is no corresponding power parser in `zigbee2mqtt.js`, perhaps adding to https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/converters/zigbee2mqtt.js#L295 will work.
- [Is this the device?](https://www.worten.pt/casa-escritorio-e-bricolage/smart-home/sensores-de-temperatura/plug-edp-re-dy-6099538) Then please change to:

```js
     // EDP
    'ZB-SmartPlug-1.0.0': {
        model: 'PLUG EDP RE:DY', // is there a model ID on the device itself??
        vendor: 'EDP',
        description: 'Plug EDP re:dy',
        supports: 'on/off, power measurement',
        homeassistant: [homeassistant.switch, homeassistant.sensor_power]
    },
```

**Comment by Koenkk** [comment]
Another question, how did you pair this device? Needed for: https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge#2-pairing-devices

**Comment by dgomes** [comment]
Yes it is the same. The smart plug has no information in the device.

**Comment by dgomes** [comment]
About energy sensor:
- It simply does not report... :(
- With the original hub it does get power readings, maybe it works with a pool command. Any ideas ?

**Comment by dgomes** [comment]
I get this when I switch ON the plug:

https://hastebin.com/ulohudafiq.go

**Comment by Koenkk** [comment]
after turning on, are there any messages reported on an interval? Like when you change the power consumption by turning on a light which is connected to the switch?

**Comment by dgomes** [comment]
Nothing :(

That's why I'm betting it is pooled

**Comment by Koenkk** [comment]
Hmm strange you have to sniff the packages in order to support this. However im OK with merging this without power measurements.

**Comment by dgomes** [comment]
Switch is working perfectly.

I too want to support energy monitoring ...

**Comment by Koenkk** [comment]
When looking at the `data/database.db` do you see any values that could be the power consumption?

**Comment by dgomes** [comment]
Did find something interesting (seMetering)

https://hastebin.com/ererevedek.json

Where should I support this ?

**Comment by Koenkk** [comment]
seMetering looks like where we are searching for, is this value updated when you change the power consumption of the plug?

**Comment by dgomes** [comment]
In the logs I don't find anything... I only found it in the database :(

**Comment by Koenkk** [comment]
Lets try if we can poll it.

Can you add the following code (ofcourse with changing the `ID`)

```
        const ID = '0x00158d0001b79111'
        const device = devices.find((d) => d.ieeeAddr === ID);
        device.epList.forEach((ep) => {
            const dev = this.shepherd.find(ID, ep);
            setInterval(() => {
                dev.read('seMetering', 'currentSummDelivered', function (err, data) {
                    if (!err) {
                        console.log('GOOD!', data);
                    }
                    else {
                        console.log('ERROR', err);
                    }
                });
            }, 2000)
        });
```

below: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/zigbee.js#L65

**Comment by Koenkk** [comment]
Good! I think we should use https://github.com/zigbeer/zigbee-shepherd/wiki#reportcid-attrid-minint-maxint-repchange-callback this will setup the device to report a certain attribute at a specified interval.

```
        const ID = '0x00158d0001b79111'
        const device = devices.find((d) => d.ieeeAddr === ID);
        device.epList.forEach((ep) => {
            const dev = this.shepherd.find(ID, ep);
            dev.report('seMetering', 'instantaneousDemand', 3, 5, 1, (err) => console.log(err));
        });
```

**Comment by dgomes** [comment]
OK works, but needs to go in a more stable place... (and looks like a big refactor meanwhile)

In where should the report() go ?

**Comment by dgomes** [comment]
I'm preparing a new "clean" PR and just noticed that the plug now sends the updates without the report() command...

Don't know for how long will it hold the configuration

**Comment by Koenkk** [comment]
To which ep ID of 

```
        device.epList.forEach((ep) => {
            console.log(ep);
            const dev = this.shepherd.find(ID, ep);
            dev.report('seMetering', 'instantaneousDemand', 3, 5, 1, (err) => console.log(err));
        });
```

Did it bound?

We should add an attribute on the device like: 
```'report': [{
          'cid': 'seMetering',
          'attr': 'instantaneousDemand',
          'ep': 1,
       }]
```

In that way zigbee2mqtt can automatically setup reporting for devices.

**Comment by dgomes** [comment]
ep ID = 85

**Comment by Koenkk** [comment]
Closing this one because of #53

**Pull request closed without merging**
