### PR TITLE
Add color_mode to group updates

### PR DESCRIPTION
**Pull request by sjorge**
If you use the group topic for a group of lights, it is missing color_temp. Add it to the allowed list.

### CODE REVIEW

**Comment by sjorge** [comment]
Hmmm looks I am still missing something else as they are not coming throu

**Comment by Koenkk** [comment]
I rebased with dev, can you check again?

**Comment by sjorge** [comment]
I was testing on dev, just opened the PR wrong.

If the bulb already has a color_mode, doing /get/color_mode wont add it to the group topic. You need to remove color_mode from state.json or force it to change color_mode before it shows up.

**Comment by Koenkk** [comment]
@sjorge that is indeed expected, only changed properties will be added. So once you change from xy -> color_temp it should be there.

**Pull request closed without merging**
