### PR TITLE
Added ETOP HT-08 Thermostat and HT-10 TRV

### PR DESCRIPTION
**Pull request by hacker-cb**
References:
* https://github.com/Koenkk/zigbee2mqtt/issues/4185
* https://github.com/Koenkk/zigbee2mqtt/issues/1856
* https://github.com/Koenkk/zigbee2mqtt/issues/4486
* http://www.etopcontrols.com/thermostat/detail/HT-08.html

### CODE REVIEW

**Comment by Hacker-CB** [comment]
I also added HT-10 TRV

**Comment by Koenkk** [comment]
Thanks!

**Comment by Koenkk** [comment]
I've merged this but this will break the TS0601 as it has no away_mode converter (https://github.com/Koenkk/zigbee-herdsman-converters/blob/7c53df8f2576bc66f81420a660c188029ec079b4/devices.js#L1479)

**Comment by Hacker-CB** [comment]
How about to rename "away" mode to "away_mode" in TS0601?
HA never push "away" preset because it is special mode.
I can do that if you agree.

**Comment by Koenkk** [comment]
Why not add away_mode converter to TS0601, this sounds like a better solution.

**Comment by Hacker-CB** [comment]
I can do that, but without tests. I don't have TS0601

**Comment by Koenkk** [comment]
Yes no problem, please make a PR I will double check

**Comment by silkysmile89** [comment]
Any chance to add the Parameter Setting menu (M+UP) for the HT-10 to have additional features like local temp calibration or open window function ?? OR this is something done only manually on the valve ??

**Comment by hacker-cb** [comment]
As I know, this parameters are not available on zigbee parts. You can only adjust them directly on the device

**Pull request merged**
