### PR TITLE
Add install code support

### PR DESCRIPTION
**Pull request by Koenkk**
Related:
- https://github.com/Koenkk/zigbee2mqtt/issues/13520
- https://github.com/Koenkk/zigbee2mqtt.io/pull/1540
- https://github.com/Koenkk/zigbee-herdsman/commit/cdb6e8e9bca557f59c60880a3879d3ce13614164

CC: @kirovilya

### CODE REVIEW

**Comment by nurikk** [comment]
> @nurikk can you add support for this in the frontend?

added to the latest dev. `Settings -> Tools -> Add install code`

**Comment by KRGhost** [comment]
I'm getting this error while trying to add the QR code from the frontend.
`MQTT publish: topic 'zigbee2mqtt/bridge/response/install_code/add', payload '{"data":{},"error":"Add install code is not supported","status":"error,"transaction":"7anb7-1"}'"`

Device: Bosch Radiator thermostat 2 BTH-RA

**Comment by KRGhost** [comment]
> @KRGhost what adapter are you using, this is currently only supported for the TI CC2652 and CC1352

@Koenkk I'm using the deconz adapter.

**Comment by Koenkk** [comment]
I see, that doesn't support the install codes.

@chrishae does the Conbee II firmware support install codes?

**Comment by ChrisHae** [comment]
> @ChrisHae does the Conbee II firmware support install codes?

Not yet. ETA: early 2023

**Comment by Roxxor91** [comment]
I guess this is only slightly on topic, but does this mean that all the Bosch devices may get supported now? Or are there only specific ones which use zigbee? ( I would really like the room thermostats for water floor heating, do they use zigbee?)

**Comment by jonasled** [comment]
Hi, does someone know when the Silicon Labs EFR32MG21 Chip supports this features (used in the sonoff ZBBridge)

**Comment by kirovilya** [comment]
@jonasled yes. supported in dev(edge) version

**Comment by kirovilya** [comment]
> Edge version of the Firmware or edge version of Z2M?

Z2M

**Pull request merged**
