### PR TITLE
Binding to new clusters

### PR DESCRIPTION
**Pull request by smartboxchannel**
Binding to new clusters. This is necessary for new EFEKTA devices.

### CODE REVIEW

**Comment by smartboxchannel** [comment]
Tell me someone!!! In order to add new clusters to the support of the bind, I still need to add code to the bind.test files.js, zigbee Herdsman.js ... probably somewhere else. By changing the bind file.js locally on my machine, it worked very well for me.

**Comment by Koenkk** [comment]
The tests need to be fixed (you can run them locally by executing `npm test` in the z2m dir)

**Comment by nurikk** [comment]
Fixed test

**Comment by Koenkk** [comment]
Thanks!

**Pull request merged**
