### PR TITLE
Feedback requested: add polling for commandOn & commandOff

### PR DESCRIPTION
**Pull request by docbobo**
As part of the work & experiments I did around https://github.com/Koenkk/zigbee-herdsman-converters/pull/879, I ran into the following problems:

- Binding the getOnOff of the switch to a group enables switching of lights even when zigbee2mqtt is not running.
- Devices that are part of that group which do not support reporting - e.g. lots of older Philips Hue devices - will be controlled properly, however the state update won't get reflected in zigbee2mqtt.

Now, I believe this PR creates more communication overhead than necessary, and I'd be happy to rework it. For example, it could limit the polling to messages that originate from an RM01. Other ideas?

When using groups together with devices that do not support reporting, this is needed
to have the new state reflected.

### CODE REVIEW

**Comment by Daniel0984** [comment]
Wouldn't it be nice to add the B&J manufacturer ID to the condition as well? The lights themselves also do not report their state if I am not mistaken.

**Comment by docbobo** [comment]
Which lights are you referring to?

**Comment by Daniel0984** [comment]
> Which lights are you referring to?

Lights attached to a relais /dimmer insert. They are technically a light / dimmable light with B&J as vendor.

**Comment by docbobo** [comment]
> Lights attached to a relais /dimmer insert. They are technically a light / dimmable light with B&J as vendor and have no reporting capability.

That should already be covered by https://github.com/Koenkk/zigbee-herdsman-converters/pull/879 - there is code that polls the switch every five seconds.

**Comment by Koenkk** [comment]
Im wondering why this is needed, our current experience is that hue bulbs support on/off reporting. If thats not always the case this is indeed needed. https://www.zigbee2mqtt.io/information/report.html#support

**Comment by docbobo** [comment]
That's what I had assumed as well, but for some reason it's not working for any of my Hue bulbs. And I have everything from the oldest to the newest, all on the latest available firmware. Could that be related to me using the CC26X2R1 here?

**Comment by Koenkk** [comment]
I dont think its related, what dates/versions do you see in database.db for the bulbs?

**Comment by docbobo** [comment]
Well, right now, I am getting the following exceptions upon startup, which I believe are the reasons why I don't see reporting:

>  zigbee2mqtt:error 2020-01-17 14:39:53: Failed to setup reporting for '0x0017880102aeaad2' - Error: AREQ - ZDO - bindRsp after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)
>  zigbee2mqtt:error 2020-01-17 14:40:03: Failed to setup reporting for '0x0017880102aeabe1' - Error: Timeout - 14882 - 11 - 4 - 6 - 7 after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)
>  zigbee2mqtt:error 2020-01-17 14:40:06: Failed to setup reporting for '0x001788010288676b' - Error: Timeout - 21707 - 11 - 5 - 6 - 7 after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)
>  zigbee2mqtt:error 2020-01-17 14:40:13: Failed to setup reporting for '0x00178801047a41a8' - Error: Timeout - 17910 - 11 - 6 - 6 - 7 after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)
>  zigbee2mqtt:error 2020-01-17 14:40:16: Failed to setup reporting for '0x0017880103819d07' - Error: Timeout - 32047 - 11 - 7 - 6 - 7 after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)
>  zigbee2mqtt:error 2020-01-17 14:40:23: Failed to setup reporting for '0x0017880100bad414' - Error: Timeout - 29413 - 11 - 8 - 6 - 7 after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)
>  zigbee2mqtt:error 2020-01-17 14:40:26: Failed to setup reporting for '0x00178801033417b7' - Error: Timeout - 58491 - 11 - 9 - 6 - 7 after 10000ms
>      at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>      at ontimeout (timers.js:436:11)
>      at tryOnTimeout (timers.js:300:5)
>      at listOnTimeout (timers.js:263:5)
>      at Timer.processTimers (timers.js:223:10)

The corresponding devices are ass follows:

> "0x0017880102aeaad2"
> "LST002"
> "5.127.1.26420"
> "20181121"
> 
> "0x0017880102aeabe1"
> "LST002"
> "5.127.1.26420"
> "20181121"
> 
> "0x001788010288676b"
> "LCT010"
> "1.46.13_r26312"
> "20181115"
> 
> "0x00178801047a41a8"
> "LLC020"
> "5.127.1.26420"
> "20181121"
> 
> 0x0017880103819d07"
> "LCT015"
> "1.46.13_r26312"
> "20181115"
> 
> 0x0017880100bad414"
> "LCT001"
> "5.127.1.26581"
> "20181129"
> 
> "0x00178801033417b7"
> "LTC002"
> "1.46.13_r26312"
> "20181115"

**Comment by Koenkk** [comment]
@sjorge what bulb versions do you have (as on/off reporting worked in your case)?

**Comment by sjorge** [comment]
Pretty old, 20170908 1.29.0_r21169
I was disappointed the only thing that seems to get reported was on/off. Hence the work around we added a while back for brightness

**Comment by Koenkk** [comment]
Yes, but for now it seems that some even don't support on/off reporting :(

**Comment by sjorge** [comment]
*crosses fingers* let hope IKEA fixes there green color then, they are great side greens.
I was going to try and pick up a 2nd hand hue bridge to update them... but if I am going to lose on/off reporting I might just not update.

**Comment by Koenkk** [comment]
In that case I propose to merge this PR, @docbobo do you have any other questions before I merge this?

**Comment by docbobo** [comment]
I do appreciate your willingness to integrate that, but it seems to be puzzling that none of my Philips devices seem to support reporting. If you don't mind, I'd like to do a quick comparison with a CC2351 that I have lying around.

**Comment by sjorge** [comment]
Looks like deconz will read on/off, level and color at certain intervals for hue bulbs.

So I guess reading all 3 on a change makes sense, if the bulb reports, that good... if it doesn't we alteast have up to date info after a remote sends a command to the bulb.

Cases where we send a command to it ourself, should already be covered I think.

**Comment by Koenkk** [comment]
@sjorge cases were zigbee2mqtt sends the command is already covered indeed.

@docbobo shouldn't make a different, but no problem if you want to do a final check.

**Comment by sjorge** [comment]
@Koenkk maybe we should also read from GLEDOPTO bulbs in this way, as according to my little reporting table they don't report anything either.

**Comment by Koenkk** [comment]
@sjorge yes of course! This can be done in a separate PR after this has been merged.

**Comment by Koenkk** [comment]
More people seem to have issues with this (see #2882) so I will merge this.

**Pull request merged**
