### PR TITLE
fix: Generate pan_id for new installations

### PR DESCRIPTION
**Pull request by Koenkk**
As discussed in https://github.com/Koenkk/zigbee2mqtt/pull/18357

### CODE REVIEW

**Comment by bharvey88** [comment]
just to confirm, you are also adding ext_pan_id auto generation now too right?

**Comment by Koenkk** [comment]
No it's not generated (also don't think it is needed after reading https://community.silabs.com/s/article/what-is-an-extended-pan-id-and-how-is-it-used-x?language=en_US)

**Comment by bharvey88** [comment]
> No it's not generated (also don't think it is needed after reading https://community.silabs.com/s/article/what-is-an-extended-pan-id-and-how-is-it-used-x?language=en_US)

In this documentation i do not see anything explicitly stating not to randomly generate it. Can you explain your reasoning why you believe it is not a good idea to randomly generate it? what is/are the downsides? - for reference - zha randomizes network_key, pan_id, and ext_pan_id and from what i understand there is no downside. Thanks.

**Comment by Koenkk** [comment]
@bharvey88 I wasn't aware that ZHA also does this, so looks like a good practice. Implemented this in https://github.com/Koenkk/zigbee2mqtt/pull/18596

**Pull request merged**
