### PR TITLE
Fix issue #229: router devices can't be managed by zigbee2mqtt

### PR DESCRIPTION
**Pull request by sebastianheierhoff**
This should fix https://github.com/Koenkk/zigbee2mqtt/issues/229

### CODE REVIEW

**Comment by sebastianheierhoff** [comment]
Not yet final/ Travis CI build fails. Will fix later.

**Comment by Koenkk** [comment]
great, let me know once your finished.

**Comment by sebastianheierhoff** [comment]
Finished & ready to be merged.

**Comment by Koenkk** [comment]
Great, thanks!

**Pull request merged**
