### PR TITLE
Rename configuration to include "example"

### LINKED ISSUE #10657: [Problem]: Configuration file overwritten when updating
### What happened?

Well, my config was overwritten. Not much more to say. Among hundreds of them I haven't seen an install package that doesn't provide a config named as "example" in years, or probably even a decade? So how was I supposed to expect when overwriting my existing installation that this would also overwrite my config? Who on earth would provide such a packet? Seriously, it's such a simple thing :-(

Fortunately I got a backup, but it's still so annoying and unnecessary...

### What did you expect to happen?

I overwrite my existing installation and my config stays untouched, because the config file in the package is named something with ".example".

### How to reproduce it (minimal and precise)

Overwrite an existing installation, lose your config, ta-dah.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

Not relevant

### Adapter

Not relevant

### Debug log

Not relevant

### PR DESCRIPTION
**Pull request by minemalox**
Fixes #10657

### CODE REVIEW

**Comment by YorVeX** [comment]
Yes pleeeeeeaaaaaaaaseeeeeee

**Comment by Koenkk** [comment]
This breaks existing setup, since they will get a merge conflict on the file rename, what problem does this fix?

**Comment by sjorge** [comment]
I suppose if z2m copies configuration.yaml.example to configuration.yaml if the later doesn’t exist, it would not break existing installs.

Although it’s been like this for so long, it might confuse existing users that the file in the repo is now just the example file.

**Comment by sjorge** [comment]
> This breaks existing setup, since they will get a merge conflict on the file rename, what problem does this fix?

I wonder if this can be done in multiple steps?
1. add configuration.yaml to .gitignore
2. add a new configuration.yaml.example (well old file really but in a seperate commit)
3. make z2m copy configuration.yaml.example -> configuration.yaml if configuration.yaml is missing ?

**Pull request closed without merging**
