### PR TITLE
Create docker-compose.yml

### PR DESCRIPTION
**Pull request by pixeldoc2000**

### CODE REVIEW

**Comment by Koenkk** [comment]
As the content of this docker compose file highly depends on the user situation (e.g. device path). I think we should add this to https://github.com/Koenkk/zigbee2mqtt.io/blob/master/information/docker.md instead.

**Comment by pixeldoc2000** [comment]
Of cause it (very) user specific, but the same is true for example the configuration.yaml.

I believe it should be on git as an example with Wiki link to it as most projects do it this way (AFAIK).

But it's up to you.

**Comment by Koenkk** [comment]
That's the best thing to do I guess, could you also make a PR to update the documentation?

**Comment by pixeldoc2000** [comment]
Yes, will update the WIKI.

**Pull request merged**
