### PR TITLE
Fix Bosch window_open entity for Home Assistant.

### PR DESCRIPTION
**Pull request by danielpetrovic**
This entity was already used by Bosch thermostats, and is supposed to be a Switch within Home Assistant.
This changes fixed the error now present with Bosch Radiator/Room Thermostats.

Related to: https://github.com/Koenkk/zigbee2mqtt/issues/21208

### CODE REVIEW

**Comment by GatoPharaoh** [comment]
problem with this change is that while it fixes the window_open switch for bosch thermostats, it will break the window_open binary sensor for aqara thermostats.

we acutally need a general decision for z2m which of window_open and window_detection is the switch and which is the binary_sensor.

**Comment by Koenkk** [comment]
All should be binary sensor which is currently already the case for Bosch BTH-RA and Aqara SRTS-A01

**Comment by GatoPharaoh** [comment]
> which is currently already the case for Bosch BTH-RA and Aqara SRTS-A01

maybe I am misunderstanding something but currently Bosch BTH-RA and Bosch BTH-RM230Z expose `window_open` only as a switch to Home Assistant while Aqara SRTS-A01 exposes `window_open` as a binary_sensor and `window_detection` as a switch. you can `/set` `window_open` for the Bosch devices but you can't for Aqara SRTS-A01

due to the changes in #20746 ( line 654 `window_open: {device_class: 'window'}` was added ) the window_open switch for Bosch BTH-RA and Bosch BTH-RM230Z doesn't work anymore.

**Comment by danielpetrovic** [comment]
BTH-RA, BTH-RM and BTH-RM230Z use the same window_open switch, as you can manually trigger it.

When you use the thermostat with the Bosch SHC II you need to link a contact sensor for the Window Open detection, so the thermostats don’t have their own “sensor” to trigger a window open message.

**Comment by Koenkk** [comment]
sounds good, @GatoPharaoh  or @danielpetrovic  could you make a PR to fix it

**Comment by simplyRoba** [comment]
here the PR just to link them https://github.com/Koenkk/zigbee-herdsman-converters/pull/7029

**Comment by danielpetrovic** [comment]
> here the PR just to link them [Koenkk/zigbee-herdsman-converters#7029](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7029)

No it does not. The PR you are linking to is not related to that. It is related to accidentally including the Heating Valve which is not present in the Battery version of the Room Thermostat.

**Comment by danielpetrovic** [comment]
> sounds good, @GatoPharaoh or @danielpetrovic could you make a PR to fix it

I am not sure if I have enough experience to make this big change. I've only done some changes for one device before which now works as expected with PR 7029. The window_open function is linked in a lot of places in the Bosch.ts file.

**Comment by danielpetrovic** [comment]
This PR can be closed as it is not the fix for this. It should be fixed in the Bosch.ts file inside the herdsman-converters . @GatoPharaoh do you have time to make this PR over there?

**Pull request closed without merging**
