### PR TITLE
Add device support for iCasa Zigbee 3.0 Dimmer

### PR DESCRIPTION
**Pull request by sheyden**
Add support for iCasa Zigbee 3.0 Dimmer (https://www.wifimedia.eu/nl/icasa-dimmer.html)

The converter pull request linked to this device can be found here: https://github.com/Koenkk/zigbee-shepherd-converters/pull/206

### CODE REVIEW

**Comment by james-fry** [comment]
This looks like a rebadged version of this:
https://www.sunricher.com/zigbee-ac-phase-cut-dimmer-sr-zg9101sac-hp.html

I think sunricher is the OEM.

A UK company is selling this too: https://arc-led.co.uk/controller/609-arc-led-ac-phase-cut-dimmer-with-zigbee-control-interface-white.html
Im considering to buy one and, if I do, I will report back if it is supported by the same PR.

@Koenkk BTW what is the process to update the wiki for supported devices - when I searched for dimmers I didnt find this one...

**Comment by Koenkk** [comment]
This is automatically updated, but only the dev version uses this zigbee-shepherd-converters version: https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/information/supported_devices.md#icasa

**Comment by james-fry** [comment]
This is good info. I didnt use zigbee2mqtt for a good few months (work commitments reducing my time). It has moved on a lot... Great work! I can see that some of my devices are supported in the dev version (e.g. Hue BR30) so I will change to use that (via hassio addon edge).
How often are dev changes merged to stable?

**Comment by Koenkk** [comment]
@james-fry this is not a regular schedule, but I expect zigbee2mqtt 1.1 at the end of this month.

**Pull request merged**
